### ISSUE TITLE
Issues Triage August 8, 2023

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1030]
Issues we discussed and assigned.

## Completed since last triage
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/838 - @zzap 
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/818 - @zzap 
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/715 - @jomarieminney
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/428 - @zzap 
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/282 - @shabnam611
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/871 - @Leonardus-Nugraha
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/498 - @zzap 

### Todo
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/935 - @sagargurnani99
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/278 - @cgarofalo
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/463 - @anandau
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/464 - @femkreations 
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/973 - @Leonardus-Nugraha

### Ready to review
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/934 - @atachibana 

### To do
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/901 - @zzap 

### Ready for review
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/694 - @Leonardus-Nugraha
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/672 - @shabnam611
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/469 - @pekkakortelainen
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/427

### In progress
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/430 - @emmyoungg

## For review
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/300 - @zzap 

-----------------------------------------------------------------------------

For other issues, please refer to previous [triage](https://github.com/WordPress/Documentation-Issue-Tracker/labels/triage) sessions:
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/873
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/844
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/819
