### ISSUE TITLE
WordCamp US Contributor Day, 24 August 2023

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1060]
https://us.wordcamp.org/2023/contributor-day/

## Everyone

**If you attend this Contributor Day, please comment below with your WordPress.org username.** 

When you find the issue you'd like to work on, please leave a comment on that issue so that we can assign you and avoid more people working on the same issue. If you know which docs the project issue belongs to, you can tag [the project rep](https://make.wordpress.org/docs/handbook/the-team/) as well.

For a quick fresh WordPress install, you can use WordPress Playground by going to https://playground.wordpress.net/
---------------------------------------------------------------------------------------------------------------------------------------------------------------

## New contributors

If this is your first time contributing to the Documentation team, please make sure you have the following accounts:
- [WordPress.org account](https://login.wordpress.org/register).
- [WordPress Slack account](https://make.wordpress.org/chat/) (wordpress.org account is needed).
- [GitHub account](https://github.com/signup) – connect [your GitHub account to your WordPress.org profile](https://make.wordpress.org/core/2020/03/19/associating-github-accounts-with-wordpress-org-profiles/).

Make sure you join [#docs](https://wordpress.slack.com/archives/C02RP4WU5) Slack channel. Once there, just wave :) 

The following videos/onboarding sessions can be helpful for performing the tasks we plan to work on:
- [General overview](https://make.wordpress.org/docs/handbook/get-involved/onboarding-sessions/overview/)
- [End user documentation](https://wordpress.tv/2022/06/21/milana-cap-end-user-documentation-onboarding-for-wordpress-documentation-team/)
- [Updating screenshots](https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/)
- [All Documentation team onboarding sessions](https://make.wordpress.org/docs/2022/06/13/live-onboarding-sessions-for-the-documentation-team/)

For general details on how GitHub works, check out [GitHub’s Getting Started Guide](https://docs.github.com/en/get-started/quickstart/hello-world).

When you find issue you'd like to work on in the [Docs Team Issue Tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) here on GitHub:

1.  Please leave a comment in that issue so that we can assign you and to avoid more people working on the same issue, and
2. In that comment, also be sure to tag the [team rep responsible for the handbook](https://make.wordpress.org/docs/handbook/the-team/) that your chosen task is about.

For example, if your task is for the Block Editor End-User documentation, you would tag @femkreations.

Check out the [Team page in the Documentation Team Handbook](https://make.wordpress.org/docs/handbook/the-team/) for a list of team reps.

---------------------------------------------------------------------------------------------------------------------------------------------------------------

### Task list for new(er) contributors

For those who wish to contribute who are new(er) to the team, once you have taken a look at the onboarding material above, please feel free to take a look at our project boards that have issues labeled as a "good first issue":

- 6.3 Docs -- [Good first issue](https://github.com/WordPress/Documentation-Issue-Tracker/issues?q=is%3Aopen+is%3Aissue+label%3A6.3+label%3A%22good+first+issue%22+label%3A%22%5BStatus%5D+To+do%22+) 

### 1. Updating block editor end-user documentation 
- WordPress 6.3 - [High priority](https://github.com/orgs/WordPress/projects/108/views/13)
- WordPress 6.3 - [Medium priority](https://github.com/orgs/WordPress/projects/108/views/14)
- WordPress 6.2 - [all](https://github.com/orgs/WordPress/projects/67/views/2)

### 2. New mobile app documentation 
- [Mobile app content review board](https://github.com/orgs/WordPress/projects/89/views/1)
- [Promote Helping to Documentation team with Mobile Apps docs #219](https://github.com/WordPress/Marketing-Team/issues/219)

### 3. Content review for older documentation 
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/372
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/470
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/469
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/458
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/457
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/455
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/443
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/442
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/438
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/430
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/429
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/427
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/426 
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/420
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/418
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/371
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/190

### 4. Rewriting articles that are moved to the new [Advanced Administration Handbook](https://developer.wordpress.org/advanced-administration/) 

[Advanced administration handbook issues](https://github.com/WordPress/Advanced-administration-handbook/issues)

### 5. Block editor developer documentation

https://docs.google.com/document/d/1eZ_mzrc0UY2M2A1o4Wxm-Ri9vPs3jzu98OZHXJUurnY/edit?usp=sharing

### 6. Anything you like

If the above list doesn't satisfy you, we have plenty of other issues you can work on:

- https://github.com/WordPress/Documentation-Issue-Tracker/labels/high%20priority
- https://github.com/WordPress/Documentation-Issue-Tracker/labels/good%20first%20issue
- https://github.com/WordPress/Documentation-Issue-Tracker/labels/developer%20documentation%20%28DevHub%29
- https://github.com/WordPress/Documentation-Issue-Tracker/labels/user%20documentation%20%28HelpHub%29
- https://github.com/WordPress/Documentation-Issue-Tracker/labels/advanced%20administration
- https://github.com/WordPress/Documentation-Issue-Tracker/labels/contributor%20documentation
- and many more.. just take a look at [all the labels](https://github.com/WordPress/Documentation-Issue-Tracker/labels).

**Comment by karks88** [comment]
My WP.org username is karks88

**Comment by mpiccorossi** [comment]
Hi - my WordPress.org username is mpiccorossi

**Comment by bobmatyas** [comment]
WordPress.org name:

lastsplash

**Comment by jhimross** [comment]
WordPress.org - jhimross

**Comment by Kenshino** [comment]
@kenshino

**Comment by pekkakortelainen** [comment]
I'll review the suggested changes of this one: https://github.com/WordPress/Documentation-Issue-Tracker/issues/427

wp.org username: [pekkakortelainen](https://profiles.wordpress.org/pekkakortelainen/)

**Comment by ktyfuller604** [comment]
My wp.org username is [ktyfuller](https://profiles.wordpress.org/ktyfuller/)

**Comment by emmasophieyoung** [comment]
hiyo - sorry i closed the issue :D 
wp - emmaht

**Comment by kkoppenhaver** [comment]
kkoppenhaver

**Comment by bacoords** [comment]
bacoords

**Comment by aurooba** [comment]
aurooba

**Comment by Leonardus-Nugraha** [comment]
wp.org: leonnugraha

**Comment by femkreations** [comment]
wp.org: femkreations

Reviewed, updated the content, closed #948

**Comment by zzap** [comment]
wp.org: milana_cap

**Comment by janmckell** [comment]
wp.org: greeninkerry

**Comment by Leonardus-Nugraha** [comment]
Reviewed and closed #694 , #973 , #947 , #936 , #937 , #941 , #975
