### ISSUE TITLE
Migrating block editor end user docs issues from Trello to GitHub

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#109]
## Context

Before we created this repository, block editor end user documentation was managed in [Trello board](https://trello.com/b/JnTCzOsL/gutenberg-end-user-docs) and team's [Google Drive folder](https://drive.google.com/drive/folders/1Nc4ePFxDsSREZimEcqy4n16z5NqUaMwQ?usp=sharing). The way it was managed is recorded in [this video](https://wordpress.tv/2021/05/25/birgit-pauli-haack-milana-cap-preparing-block-editor-end-user-documentation-for-wordpress-releases/).

Now we want to migrate all relevant Trello cards here.

## Steps to get involved

1. Watch the video and familiarise yourself with the content of the Drive folder.
2. If you still want to get involved, check your read/write access to Trello board - I have created it a long time ago and permissions are funky.
3. Check your read/write access to Google Drive folder.
4. State your interest to be involved and the level of your access to items 2 and 3 in the comments below.

## Why don't we use automated tools for migrating Trello cards into GutHub issues?

Because we need a human to review Trello card and associated docs in Drive, compare it to the actual page at [wordpress.org/support](https://wordpress.org/support) and confirm that a card is still valid. 

We can, however, use something like Zapier's Create issue in [GitHub when card moved to list in Trello](https://workflows.zapier.com/?attempt_id=794a98c6-afdb-4807-8a2a-30e907027bf6&template=11696&context=1619061# ) (you have to be logged into Zapier to see it), which would be incorporated to move the card to the "GitHub issues" or something when the card is verified by a human as still valid. Archive card otherwise.

 ## The board looks overwhelming, where to start?

Cards are labeled with WordPress versions, amongst other labels and can be filtered out. At the moment there are 5.8, 5.7 and 5.6 version labels. My suggestion is to start from 5.8 and go backwards. Once we're out of version cards we'll see what's left and act accordingly.

- [ ] [WP 5.8](https://trello.com/b/JnTCzOsL/gutenberg-end-user-docs?filter=label:5.8,label:WP5.8)
- [ ] [WP 5.7](https://trello.com/b/JnTCzOsL/gutenberg-end-user-docs?filter=label:WP%205.7)
- [ ] [WP 6.5](https://trello.com/b/JnTCzOsL/gutenberg-end-user-docs?filter=label:WP5.6)
- [ ] The rest

**Comment by santanainniss** [comment]
Working on 5.8 Widget Screen: https://trello.com/c/E74yu6Ua/104-widget-screen?filter=label:5.8,label:WP5.8

**Comment by santanainniss** [comment]
> 

5.8 widget screen is all good.

**Comment by santanainniss** [comment]
@zzap working on 5.8 Query Loop Block

**Comment by santanainniss** [comment]
> * Query Loop Block

Did not have a linked live document --> https://trello.com/c/aRyoj9sq/115-query-loop-block?filter=label:5.8,label:WP5.8 or corresponding /core doc. 

I did find --> https://wordpress.org/support/article/query-loop-block/ published on the same day referenced by @annezazu and it looks all good!

This Trello card can be closed.

**Comment by santanainniss** [comment]
@zzap working on 5.8 Block Pattern

**Comment by santanainniss** [comment]
> @zzap working on 5.8 Block Pattern

https://wordpress.org/support/article/block-pattern/ Looks great! Changes referenced reflected and live.

**Comment by santanainniss** [comment]
@zzap Reviewed 5.8 Block Pattern Directory. There isn't any context or source to compare on Trello (https://trello.com/c/fvlMKyyO/117-block-pattern-directory?filter=label:5.8,label:WP5.8), but the [Block Pattern Directory ](https://wordpress.org/support/article/block-pattern-directory/) article is live on /support

**Comment by zzap** [comment]
All cards with 5.8 label are reviewed and, where needed, migrated to GitHub issues: #118, #119, and #120.

**Comment by zzap** [comment]
All cards with 5.7 label are reviewed and, where needed, migrated to GitHub issues (or updated existing ones): #121, #122, #123, #120, #124, #125, #126, and #119.

**Comment by zzap** [comment]
Trello board has been completely migrated and closed. From now on block editor end user docs issues will be worked on through GitHub issues here.

![Gutenberg End User Docs _ Trello](https://user-images.githubusercontent.com/1508963/153454767-60797518-90df-4d6f-b523-9b2e16f82f59.png)
