### ISSUE TITLE
[Codex] WordPress versions info (Tracking Issue)

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1095]
Information about WordPress versions can be found in various places.

Codex:

- https://codex.wordpress.org/Supported_Versions
- https://codex.wordpress.org/WordPress_Versions
- https://wordpress.org/documentation/wordpress-version/version-0-70/
- each version...

HelpHub:

- Article: https://wordpress.org/documentation/article/supported-versions/
- Article: https://wordpress.org/documentation/article/wordpress-versions/ - some versions link to the Codex ones
- CPT archive: https://wordpress.org/documentation/wordpress-versions/
- CPT single: https://wordpress.org/documentation/wordpress-version/version-6-3-1/
- each version..

Download:

- https://wordpress.org/download/releases/

Tasks:
- [x] All release note posts on Codex should be migrated, deprecated, and "redirected" to HelpHub.
	- [x] #1096
- [ ] Release note links in [this article](https://wordpress.org/documentation/article/wordpress-versions/) should be updated to link to HelpHub version posts OR we should deprecate this article and do development work on Versions CPT archive.
	- [ ] #1096
- [x] The content on "Supported Versions" page shall be migrated and redirect set.
	- [x] #1094

**Comment by zzap** [comment]
Related #1094

**Comment by stevenlinx** [comment]
related #1096
