### ISSUE TITLE
Issues Triage September 12, 2023

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1110]
Issues we discussed and assigned.

## Tasks completed since last triage
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/973 - @Leonardus-Nugraha
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/694 - @Leonardus-Nugraha
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/934 - @atachibana 
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/469 - @pekkakortelainen
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/935 - @sagargurnani99

# From previous triage meeting

##  WP 6.3 release Todo
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/278 - @cgarofalo
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/463 - @anandau
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/464 - @femkreations 

## General To do
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/901 - @zzap 

## General Ready for review
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/672 - @shabnam611
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/427

## General In progress
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/430 - @emmyoungg

## General For review
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/300 - @zzap 

-----------------------------------------------------------------------------

For other issues, please refer to previous [triage](https://github.com/WordPress/Documentation-Issue-Tracker/labels/triage) sessions:
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/1030
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/873
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/844
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/819
