### ISSUE TITLE
[HelpHub] [6.4] Verse Block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#1213]
Article:  https://wordpress.org/documentation/article/verse-block/

## Updates for 6.4
- [ ] Enable the line breaks. [52928](https://github.com/WordPress/gutenberg/pull/52928)

## Reference
- [ ] [Pls refer for the previous versions tasks here](https://github.com/WordPress/Documentation-Issue-Tracker/issues/964)

## General
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Good first issues
If you are looking for simpler tasks, take a look at related good first issues:

- [ ] Check ALT attributes: #1349  
- [ ] Check headings: #1350         
- [ ] Update screenshots: #1351       
- [ ] Update videos: #1352

**Comment by itsjustdj** [comment]
I'll take this one, @femkreations @abhansnuk !

**Comment by abhansnuk** [comment]
Thanks D.J. Assigned to you.

**Comment by itsjustdj** [comment]
Everything looks good on this one.

**Comment by andreawetzel** [comment]
Closing via https://github.com/WordPress/Documentation-Issue-Tracker/issues/2140
