### ISSUE TITLE
Issues Triage January 16, 2024

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#1411]
Issues we discussed and assigned.

## Tasks completed since the last triage
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/300 - @Leonardus-Nugraha
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/293 - @zzap 
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/203 - @sagargurnani99
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/463 - @Leonardus-Nugraha

#### Ready for review
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/427 - @estelaris 
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/716 - @anandau 
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/958 - @sagargurnani99

#### In progress
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/954 - @sagargurnani99
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/430 - @sagargurnani99

### Last 2 [6.0 issues](https://github.com/WordPress/Documentation-Issue-Tracker/labels/6.0):

- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/291 - @atachibana
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/278 - @zzap 

####  WP 6.3 release Todo
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/940
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/464 - @femkreations 

#### To do
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/901 - @zzap 

-----------------------------------------------------------------------------

For other issues, please refer to previous [triage](https://github.com/WordPress/Documentation-Issue-Tracker/labels/triage) sessions:
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/1398
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/1143
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/1110
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/1030
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/873
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/844
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/819
