### ISSUE TITLE
Issues Triage February 13, 2024

### ISSUE THREAD

**Issue by sagargurnani99** [WordPress/Documentation-Issue-Tracker#1460]
Issues we discussed and assigned.

## Tasks completed since the last triage
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/278 - @zzap
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/901 - @zzap 

#### In Review
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/958 - @Leonardus-Nugraha

#### Ready for review
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/427 - @estelaris 
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/716 - @anandau 

#### In progress
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/430 - @sagargurnani99
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/954 - @sagargurnani99

### Last 2 [6.0 issues](https://github.com/WordPress/Documentation-Issue-Tracker/labels/6.0):
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/291 - @atachibana

####  WP 6.1 release Todo
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/161 - @jennimckinnon 
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/464 - @Leonardus-Nugraha, @atachibana and @cgarofalo
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/490 - @jennimckinnon 
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/516 - @Leonardus-Nugraha 
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/940 - @zzap 

#### To do
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/901 - @zzap 

-----------------------------------------------------------------------------

For other issues, please refer to previous [triage](https://github.com/WordPress/Documentation-Issue-Tracker/labels/triage) sessions:
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/1411
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/1398
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/1143
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/1110
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/1030
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/873
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/844
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/819
