### ISSUE TITLE
Issues Triage April 09, 2024

### ISSUE THREAD

**Issue by sagargurnani99** [WordPress/Documentation-Issue-Tracker#1535]
Issues we discussed and assigned.

## Tasks completed since the last triage
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/430 - @sagargurnani99
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/954 - @sagargurnani99
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/958 - @Leonardus-Nugraha
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/291 - @atachibana
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/516 - @Leonardus-Nugraha 
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/901 - @zzap 

#### In Review
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/716 - @anandau 
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/427 - @estelaris 
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/490 - @sagargurnani99 
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/978 - @shawnco

#### Ready for review
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/161 - @jennimckinnon 

#### In progress
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/464 - @Leonardus-Nugraha, @atachibana and @cgarofalo
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/1466 - @estelaris and @pooja9712
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/1232 - @estelaris 

####  WP 6.1 release in progress
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/161 - @jennimckinnon 
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/940 - @zzap 

-----------------------------------------------------------------------------

For other issues, please refer to previous [triage](https://github.com/WordPress/Documentation-Issue-Tracker/labels/triage) sessions:
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/1460
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/1411
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/1398
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/1143
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/1110
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/1030
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/873
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/844
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/819
