### ISSUE TITLE
Monthly Planning (Triage) - May 14, 2024

### ISSUE THREAD

**Issue by Leonardus-Nugraha** [WordPress/Documentation-Issue-Tracker#1559]
Issues we discussed and assigned.

## Tasks completed since the last triage
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/490 - @sagargurnani99 
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/464 - @Leonardus-Nugraha, @atachibana and @cgarofalo
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/1466 - @estelaris and @pooja9712

#### From previous triage meetings
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/716 - reassigned to @sagargurnani99 
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/978 - reassigned to @sagargurnani99 
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/427 - @estelaris 
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/161 - @jennimckinnon 
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/1232 - @estelaris 
 
#### WP 6.5 Ready for 1st Review
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/1490 - @Leonardus-Nugraha 

#### WP 6.5 Ready for 2nd Review
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/1514 - @Leonardus-Nugraha 
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/1491 - @atachibana 

#### WP 6.5 New Document
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/1498 - @atachibana 
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/1499 - @Leonardus-Nugraha 

#### WP 6.4 Issues
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/1214 - @atachibana 

-----------------------------------------------------------------------------

For other issues, please refer to previous [triage](https://github.com/WordPress/Documentation-Issue-Tracker/labels/triage) sessions:
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/1535
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/1460
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/1411
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/1398
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/1143
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/1110
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/1030
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/873
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/844
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/819
