### ISSUE TITLE
[HelpHub] Embeds

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#161]
Article: https://wordpress.org/support/article/embeds/

## Updating for 6.1
- [x] Add a link to the new Pocket casts embed block variation article #494
- [x] Update the Embeds Changelog

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/SQzT09Tw/14-embeds

**Comment by femkreations** [comment]
moving this into the 6.2 Project board

**Comment by cgarofalo** [comment]
@femkreations @zzap

There is only one screenshot on this page, and while it is still accurate in 6.2, I feel that the demo Tumblr link should be replaced with a WordPress relevant one. We probably shouldn't be promoting a random Tumblr user's blog in documentation. 


![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/e778f065-f13e-4078-a507-e536b7a40991)

**Comment by zzap** [comment]
You are correct, @cgarofalo . People use these screenshots to include their personal URLs/profiles.

**Comment by cgarofalo** [comment]
Update: There is a Vimeo Embed documentation page, it seems out of date itself, but we can at least link it in the list:
https://wordpress.org/documentation/article/vimeo-embed/

**Comment by cgarofalo** [comment]
@femkreations @zzap Ready for review

**Comment by estelaris** [comment]
Added:

- On the list of sites section
- Added the link to the Vimeo Block


- In the Embeds changelog
- 6.1 - Added: Pocket Casts

Reviewed 6.1 to 6.6 and there are no updates to any Embed blocks.
