### ISSUE TITLE
[6.7 HelpHub]: Global Styles updates

### ISSUE THREAD

**Issue by ndiego** [WordPress/Documentation-Issue-Tracker#1778]
Article:  https://wordpress.org/documentation/article/styles-overview/

## Update for 6.7

- [ ] Add colors and typography to the browse styles section. ([63173](https://github.com/WordPress/gutenberg/pull/63173))
- [ ] Adding Font size presets UI. ([63057](https://github.com/WordPress/gutenberg/pull/63057))
- [ ] Add a typesets section to Typography. ([62539](https://github.com/WordPress/gutenberg/pull/62539))
- [ ] Background: Add background attachment to top level styles. ([61382](https://github.com/WordPress/gutenberg/pull/61382))
- [ ] Background images: Ensure appropriate default values. ([64192](https://github.com/WordPress/gutenberg/pull/64192)
- [ ]Background image: Move controls into a popover. ([60151](https://github.com/WordPress/gutenberg/pull/60151))
- [ ] Block background UI controls. ([60100](https://github.com/WordPress/gutenberg/pull/60100))
- [ ] Add custom CSS for block style variations. ([62526](https://github.com/WordPress/gutenberg/pull/62526))
- [ ] The document bar is now displayed when viewing the Style book and Style revisions ([#62669](https://github.com/WordPress/gutenberg/pull/62669))

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article.

**Comment by rollybueno** [comment]
- [x] Add colors and typography to the browse styles section. [#63173](https://github.com/WordPress/gutenberg/pull/63173)

#### Preset Color Palette

Starting with WordPress 6.7, the **Color** interface introduces a new preset color palette that provides a curated set of default colors designed to complement your theme’s design. These presets serve as a consistent foundation for applying color across blocks and global elements, helping to maintain visual harmony and accessibility throughout your site.

![Image](https://github.com/user-attachments/assets/8cd77b53-8100-4904-9873-29c730c00a8f)
ALT: Preset color palette option

### [Typography ](https://wordpress.org/documentation/article/styles-overview/#typography)

Preset typography options are now available in the Styles interface. These presets, defined by the theme, provide a curated set of font sizes, line heights, and other typographic values that help maintain consistency across your site.

![Image](https://github.com/user-attachments/assets/a3c4f1a5-3ae8-4de7-90dd-2ca09c4851d0)
ALT: Preset typography option

_PS: I already added another updates with up-to-date screenshots at https://github.com/WordPress/Documentation-Issue-Tracker/issues/1879_

**Comment by rollybueno** [comment]
- [x] Add custom CSS for block style variations. [#62526](https://github.com/WordPress/gutenberg/pull/62526)
This can be set on individual blocks, while Global style does not support it on 6.8
