### ISSUE TITLE
[HelpHub] Archives block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#268]
Article:  https://wordpress.org/support/article/archives-block/

## Updating for 6.0
- [x] Add transform between Calendar and Archives. [38324](https://github.com/WordPress/gutenberg/pull/38324)
- [x] Add yearly, weekly, and daily archive settings to the archives block. [38440](https://github.com/WordPress/gutenberg/pull/38440)

### Updating for 5.9
- [ ] Refer to the [tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues/155).

## General
- [x] Make sure all screenshots are relevant for the current version (6.0)
- [x] Make sure videos are up to date
- [x] Make sure the headings are in sentence case
- [x] Update the changelog at the end of the article

**Comment by leonidasmi** [comment]
I'm currently working on the screenshots for this :)

**Comment by leonidasmi** [comment]
_1st image(Here’s what it looks like when it’s embedded in the Editor):_
**Old:**
![image](https://user-images.githubusercontent.com/12400734/168256695-22c81a41-88e6-470e-89ab-3e7437ff79e8.png)
**New:**
![image](https://user-images.githubusercontent.com/12400734/168258054-3e59b0ba-71ac-4491-8755-e29b898be0fc.png)

_2nd image (Add Archives block with a slash command):_
**Old:**
![image](https://user-images.githubusercontent.com/12400734/168256545-6cb86a00-ad74-472a-86dd-327b3fcf9cd7.png)

**New:**
![image](https://user-images.githubusercontent.com/12400734/168256483-89bee819-ef5a-4298-a609-e581ba3c1773.png)

_3rd (Alignments controls for Archives block):_
**Old:**
![image](https://user-images.githubusercontent.com/12400734/168258592-2feba300-5416-45a3-8315-2064b53de29c.png)

**New:**
![image](https://user-images.githubusercontent.com/12400734/168258544-877d01d6-dac2-4847-af4f-6aff9fe6312f.png)

_4th image(Block Settings ) - New UX:_
**Old:**
![image](https://user-images.githubusercontent.com/12400734/168259687-3bf102aa-135c-435b-a3be-6fc6a8be349a.png)

**New:**
![image](https://user-images.githubusercontent.com/12400734/168259296-36946466-d2e1-4cf3-83ba-6c19fd3cac0a.png)

_5th image (Archives settings options for dropdown and post count):_
**Old:**
![image](https://user-images.githubusercontent.com/12400734/168260293-bae57c84-ad95-473c-8e60-311056f3d724.png)

**New:**
![image](https://user-images.githubusercontent.com/12400734/168260013-c55991f3-8ad7-4081-adc3-187da100f4cb.png)

_6th image (The advanced section lets you add a CSS class to your block) - I'm adding this for consistency even though I dont think it's that big of a change:_
**Old:**
![image](https://user-images.githubusercontent.com/12400734/168267866-8079ffba-adae-4279-bc48-d3d673e1661c.png)

**New:**
![image](https://user-images.githubusercontent.com/12400734/168267832-55405f94-6868-4e57-9d5a-c21f3a71d74b.png)

**Comment by zzap** [comment]
Thank you so much :heart:

**Comment by femkreations** [comment]
Thank you @leonidasmi. The page has been updated with the screenshots you added.

https://wordpress.org/support/article/archives-block/
