### ISSUE TITLE
[HelpHub] Buttons block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#270]
Article:  https://wordpress.org/support/article/buttons-block/

## Updating for 6.0
- [ ] Preserve styling from adjacent button blocks when inserting a new button block. [37905](https://github.com/WordPress/gutenberg/pull/37905)
- [ ] Add select-parent button to block toolbar "More options" menu. [40105](https://github.com/WordPress/gutenberg/pull/40105)

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Make sure videos are up to date
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

**Comment by leon-nugraha** [comment]
@femkreations i'd like to work on this

**Comment by leon-nugraha** [comment]
_[New explanation for adding an individual button and the style preservation. This comes after the explanation for adding the buttons block]_

The Buttons block will come with one individual button block by default, within which you can customize the text, link, and style for the button. To add more buttons, click the plus (+) icon in the Buttons block, and a new button will appear. Note that the new button will follow the same style as the existing button.

![wordpress-add-button](https://user-images.githubusercontent.com/108468349/183588562-c997cafc-63ca-4e6b-8fef-6fdef908dd1e.gif)

_[New explanation and screenshot replacement for the block toolbar’s “More options” menu]_

![Screenshot_58](https://user-images.githubusercontent.com/108468349/183588885-6022b6e4-4e0b-4451-b151-ecd4a23c6a1d.png)

### Select parent block
The select parent block option will move you to the parent block that contains the Buttons block.
### Lock
The lock option prevents users from moving or deleting the selected block. A pop-up window will appear to set the block locking attribute to the selected block. You can opt to disable movement, prevent removal, or both for the selected block.
### Make template part
The make template part allows you to create a new template from the selected block. A pop-up window will appear to name the template part and select the template area.

### Changelog:
- Updated 2022-08-xx
- Updated screenshots to 6.0
- Updated video to 6.0
- Added new explanation for adding individual buttons and style preservation
- Added new block toolbar options

**Comment by femkreations** [comment]
Thank you for your work on this page. @leon-nugraha I have updated the page with your info. Also added some missing details from the previous releases.

https://wordpress.org/support/article/buttons-block/
