### ISSUE TITLE
[HelpHub] Code block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#271]
Article:  https://wordpress.org/support/article/code-block/

## Updating for 6.1
- [ ] Add transformation to Paragraph. [43938](https://github.com/WordPress/gutenberg/pull/43938)
- [ ] Add missing typography supports to code block [43255](https://github.com/WordPress/gutenberg/pull/43255)

## Updating for 6.0
- [ ] Add paragraph in transforms option. [38295](https://github.com/WordPress/gutenberg/pull/38295)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by leonidasmi** [comment]
I'm working on the screenshots for this :)

**Comment by leonidasmi** [comment]
_1st image_
**Old:**
![image](https://user-images.githubusercontent.com/12400734/168276053-1fa0a406-779a-48e7-a55e-0f5ff8744b88.png)

**New:**
![image](https://user-images.githubusercontent.com/12400734/168275970-549198cf-a931-4df1-b322-ea99f14ae928.png)

_2nd image_
**Old:**
![image](https://user-images.githubusercontent.com/12400734/168276518-a2cdca4c-543b-445d-b77c-560b8f893a54.png)

**New:**
![image](https://user-images.githubusercontent.com/12400734/168276467-97509a66-918c-43e0-a253-ab7224051ad5.png)

_3rd image_
**Old:**
![image](https://user-images.githubusercontent.com/12400734/168277399-5ad0f2cc-3d9d-4a0b-b34d-80756df20899.png)

**New:**
![image](https://user-images.githubusercontent.com/12400734/168277341-bce75fbe-96a7-47dc-ae6d-8cd9106c74d1.png)

_4th image_
**Old:**
![image](https://user-images.githubusercontent.com/12400734/168277781-249db017-49f1-4813-bb5e-cb669bbef13d.png)

**New:**
![image](https://user-images.githubusercontent.com/12400734/168277720-2c08a209-ca9e-4c9b-8d2b-2514a2fca5ad.png)

_5th image_
**Old:**
![image](https://user-images.githubusercontent.com/12400734/168278179-9bf1e2d5-4cde-4d40-951e-c3d47fdb2507.png)

**New:**
![image](https://user-images.githubusercontent.com/12400734/168278147-ea637b40-6ca8-4ca8-bf91-c037038d403c.png)

_6th image:_
**Old:**
![image](https://user-images.githubusercontent.com/12400734/168278400-d100cc04-07d7-4413-956b-27534cd92f32.png)

**New:**
![image](https://user-images.githubusercontent.com/12400734/168278348-4a32d024-aea6-4d10-a566-7b7cabf3b3f3.png)

_7th image:_
**Old:**
![image](https://user-images.githubusercontent.com/12400734/168278771-d03c4e85-1dd9-417e-93bc-724be5466e0c.png)

**New:**
![image](https://user-images.githubusercontent.com/12400734/168278719-50fc542d-e26a-46db-a375-405bbca02044.png)

_8th image_
**Old:**
![image](https://user-images.githubusercontent.com/12400734/168279051-0b6d9f2a-8296-4c90-8ac4-ba90b7f91de7.png)

**New:**
![image](https://user-images.githubusercontent.com/12400734/168278914-e944d0e6-7653-4a9c-9992-476ef509c514.png)

_9th image_
**Old:**
![image](https://user-images.githubusercontent.com/12400734/168279208-c8d0e559-e202-4c15-8a6a-9c67aa712cba.png)

**New:**
![image](https://user-images.githubusercontent.com/12400734/168279175-9d847a6f-deb2-4d0c-9f9a-fdcb70fe6f4b.png)

**Comment by femkreations** [comment]
Adding 6.1 tasks.

## Notes
1. We are not adding updates for the Block settings as we are revamping the block settings for all the block articles 
2. Pls make 6.1 updates first and then move into 6.0.
3. For 6.0, you can pick the screenshots added in the comments previously.

**Comment by Ignasrimkunas** [comment]
@Leonardus-Nugraha I will take this

**Comment by emmasophieyoung** [comment]
https://docs.google.com/document/d/1tGFZsyHC6ZynXWdhNfs5q1q0GbIEhTZ44vTv5w1rXoA/edit#

first review done <3

**Comment by Leonardus-Nugraha** [comment]
Content updated!
