### ISSUE TITLE
[HelpHub] Categories block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#273]
Article:  https://wordpress.org/support/article/categories-block/

## Updating for 6.0
- [x] Add transform between Tag Cloud and Categories. [38566](https://github.com/WordPress/gutenberg/pull/38566)

### Updating for 5.9
- [x] Refer to the [tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues/154)

## General
- [x] Make sure all screenshots are relevant for the current version (6.0)
- [x] Make sure videos are up to date
- [x] Make sure the headings are in sentence case
- [x] Update the changelog at the end of the article

**Comment by suascat** [comment]
Working on updating the screenshots

**Comment by suascat** [comment]
Categories alignment:

![new-categories-align](https://user-images.githubusercontent.com/9716719/168283978-5fe3f2a6-2565-457d-ae19-8e919547b91c.png)

Additional menu items as per screenshot:

- None
- Wide width
- Full width

Categories settings:
![categories-block-settings](https://user-images.githubusercontent.com/9716719/168284385-bb60d81c-a25a-497f-a4dd-3bcf093e2950.png)

Additional menu items as per screenshot: 

- Show only top level categories

**Comment by evrpress** [comment]
I've added some screenshots in #154

**Comment by femkreations** [comment]
Thanks @evrpress and @suascat for your work.

This page has been updated for 6.0 with the screenshots.
https://wordpress.org/support/article/categories-block/
