### ISSUE TITLE
[HelpHub] Calendar block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#274]
Article:  https://wordpress.org/support/article/calendar-block/

## Updating for 6.0
- [x] Add transform between calendar and archives. [38324](https://github.com/WordPress/gutenberg/pull/38324)

### Updating for 5.9
- [x] Refer to the [tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues/156)

## General
- [x] Make sure all screenshots are relevant for the current version (6.0)
- [x] Make sure videos are up to date
- [x] Make sure the headings are in sentence case
- [x] Update the changelog at the end of the article

**Comment by leonidasmi** [comment]
I'm working on the screenshots for this! :)

**Comment by leonidasmi** [comment]
_1st image:_
**Old:**
![image](https://user-images.githubusercontent.com/12400734/168280427-674451e1-ebac-4236-aa5e-16abf1aa4700.png)

**New:**
![image](https://user-images.githubusercontent.com/12400734/168280358-2f52d369-0e00-404e-aabd-396e74bf4099.png)

_2nd image:_
**Old:**
![image](https://user-images.githubusercontent.com/12400734/168281103-121f9958-afb4-4579-8f55-65a11f5233e2.png)

**New:**
![image](https://user-images.githubusercontent.com/12400734/168281068-a2036e9b-b942-433a-9eb1-35c8e96861bb.png)

_3rd Image:_
**Old:**
![image](https://user-images.githubusercontent.com/12400734/168280194-ea6bd950-449b-4ec4-99c6-e25713cb1d26.png)

**New:**
![image](https://user-images.githubusercontent.com/12400734/168280160-6ff0cd3f-2099-4f15-a3c0-40c54adb16e4.png)

_4th image:_
**Old:**
![image](https://user-images.githubusercontent.com/12400734/168281741-ba422f12-54b4-4dee-850c-dfd6bcc96176.png)

**New:**
![image](https://user-images.githubusercontent.com/12400734/168281698-c34c8c56-fdbe-4b39-8b08-cbb1f40c6372.png)

_5th image:_
**Old:**
![image](https://user-images.githubusercontent.com/12400734/168281969-aa51094d-1d23-4970-9016-d500c2ed6302.png)

**New:**
![image](https://user-images.githubusercontent.com/12400734/168281924-dc43a6e7-639b-4237-bf79-d0ba79d41749.png)

_6th image:_
**Old:**
![image](https://user-images.githubusercontent.com/12400734/168282108-03159f92-9f05-4f7d-ab41-e5a25ee76605.png)

**New:**
![image](https://user-images.githubusercontent.com/12400734/168282061-a164afe7-4e15-4bdf-9a73-ad207fddcc22.png)

_7th image:_
**Old:**
![image](https://user-images.githubusercontent.com/12400734/168282292-fa85db7c-683e-4d74-86e7-6e65fe887bb3.png)

**New:**
![image](https://user-images.githubusercontent.com/12400734/168282257-da34b518-6d72-44af-912c-2bf5820e9376.png)

**Comment by femkreations** [comment]
Thank you @leonidasmi This page has been updated with the 6.0 screenshots.

https://wordpress.org/support/article/calendar-block/
