### ISSUE TITLE
[HelpHub] Cover block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#275]
Article:  https://wordpress.org/support/article/cover-block/

## Updating for 6.0
- [ ] Makes cover block dynamic and adds featured image binding. [39658](https://github.com/WordPress/gutenberg/pull/39658)
- [ ] Mention the upload error. [39428](https://github.com/WordPress/gutenberg/pull/39428)

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Make sure videos are up to date
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

**Comment by femkreations** [comment]
Added tasks for 6.1

**Comment by alianschiavoncini** [comment]
These are new screenshots for the Dimensions.

![cover-dimensions-1](https://user-images.githubusercontent.com/42210724/201321517-f72c8861-a247-4a99-8fcc-dddd685f7676.png)


![cover-dimensions-2](https://user-images.githubusercontent.com/42210724/201321522-d7e97ee2-471e-4214-84c8-cc7c25026a4d.png)

**Comment by alianschiavoncini** [comment]
New screenshot for Media settings.
![cover-media-settings](https://user-images.githubusercontent.com/42210724/201328581-5087536d-35cf-49c2-b05c-67c943d21f14.png)

**Comment by Thelmachido** [comment]
Hi @femkreations can you please assign me to this one?

**Comment by femkreations** [comment]
@Thelmachido All yours! Thanks for picking this one

**Comment by Thelmachido** [comment]
@femkreations I have updated the Cover Block with new screenshots and I have added the Duotone Filter.

**Comment by femkreations** [comment]
@Thelmachido Pls note I have added two issues related to the 6.2 updates to this page. Let me know if you have any questions.

**Comment by femkreations** [comment]
Awesome work @Thelmachido That was quick! I'll review once I am through with adding all the 6.2 tasks

**Comment by abhansnuk** [comment]
I have been going through this ready for when second review is needed, will follow on when you have done first review @femkreations . Great job @Thelmachido and Femy on GitHub in general.

**Comment by annezazu** [comment]
Reviewing this now and will update shortly depending on whether we can publish this outright or not!

**Comment by annezazu** [comment]
Made an update to the short video on using a featured image in the cover block and added more information in around the HTML element as what was there before was too simplified to be understandable for an end user ("HTML element lets you choose the HTML element you want to be used for the Stack block’s wrapper in the HTML code."):

>HTML element lets you choose between these HTML elements: Div, header, footer, main, section, article, and aside. It will default to div if another option isn't selected. While more advanced, this option allows you to add semantic elements that can be used to define different parts of a web page. For example, if you're using the Cover block as part of your Header, it would make sense to define it as such. 

Before:

https://user-images.githubusercontent.com/26996883/228030368-fc7438b1-225c-4597-b220-a551eba02588.mov

After:


https://user-images.githubusercontent.com/26996883/228031030-bcb966d6-eaa6-4338-91f9-9f5c46fa67bc.mov

As you'll notice the original video jumped too quickly into the featured image option, not leaving enough time to really understand what one needs to do. 

Marking as done for 6.2.
