### ISSUE TITLE
[HelpHub] Gallery block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#276]
Article:  https://wordpress.org/support/article/gallery-block/

## Updating for 6.0
- [x] Move add/edit media to block toolbar. [38036](https://github.com/WordPress/gutenberg/pull/38036)
- [x] Auto-migration of v1 Gallery blocks to v2 format when edited [36191](https://github.com/WordPress/gutenberg/pull/36191)

**Explain the following features using video/screenshots:**
Use the gap support functionality in the Gallery block to create different looks – from adding spacing between all images, to removing spacing altogether.

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Make sure videos are up to date
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

**Comment by adamwoodnz** [comment]
The [docs for the Gallery Block](https://wordpress.org/support/article/gallery-block/) still include an `Edit as HTML` option, however this has been removed from the editor in 6.0, see PR https://github.com/WordPress/gutenberg/issues/39310.

Docs entry:
![Screen Shot 2022-05-31 at 4 52 17 PM](https://user-images.githubusercontent.com/1017872/171095401-ffc3cccb-ca3e-43be-813d-c4af5b965aef.png)

No Edit as HTML option in dropdown:
![Screen Shot 2022-05-31 at 4 54 53 PM](https://user-images.githubusercontent.com/1017872/171095666-32782d3a-30f2-455d-80c1-a13112b1b8eb.png)

The option should also be removed from the docs.

**Comment by femkreations** [comment]
This page has been updated:
Added 6.0 screenshots and videos.
Updated block toolbar with Add button and replace the info with the updated process for adding images to the gallery.
Reordered the info to separate the block toolbar and block sidebar.
Adding Dimensions to the block settings with video.
Updating the block settings for images.
Adding details for image customizations with content, screenshots and video.
Added ALT tags for images.

https://wordpress.org/support/article/gallery-block/
