### ISSUE TITLE
[HelpHub] Image block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#278]
Article:  https://wordpress.org/documentation/article/image-block/

## Updating for 6.3
- [x] Add image block aspect ratio control [51545](https://github.com/WordPress/gutenberg/pull/51545)
- [x] ~Image Lightbox: Add a reset button [51239](https://github.com/WordPress/gutenberg/pull/51239)~
- [x] Allow dragging-and-dropping images from the inserter to image blocks [49673](https://github.com/WordPress/gutenberg/pull/49673)
- [x] Display custom borders on placeholder [49569](https://github.com/WordPress/gutenberg/pull/49569)
- [x] Update alternative text labels and help text [49416](https://github.com/WordPress/gutenberg/pull/49416)
- [x] Replace "Image size" with "Resolution" in image size controls [49112](https://github.com/WordPress/gutenberg/pull/49112)
- [x]  [Inserter - Media tab]: Upload Openverse images when inserted [48501](https://github.com/WordPress/gutenberg/pull/48501)
- [x] ImageSizeControl: Remove the "Image Dimensions" label [49414](https://github.com/WordPress/gutenberg/pull/49414)
- [x] add block controls on the inspector [49838](https://github.com/WordPress/gutenberg/pull/49838)

## Updating for 6.2
- [x] Add toolbar button to add a caption. [44965](https://github.com/WordPress/gutenberg/pull/44965)
- [x] Update placeholder style [44190](https://github.com/WordPress/gutenberg/pull/44190)
- [x] Allow dropping an image on an empty paragraph block to create an image block [42722](https://github.com/WordPress/gutenberg/pull/42722)

## Updating for 6.1
- [x] Display transformation error notice using snackbars. [44031](https://github.com/WordPress/gutenberg/pull/44031)
- [x] Display upload error notices using snackbars. [43767](https://github.com/WordPress/gutenberg/pull/43767)
- [x] Polish placeholder radius and enable duotone on image setup state. [43425](https://github.com/WordPress/gutenberg/pull/43425)
- [x] Placeholder: Add blurred background to work in nested cases. [43379](https://github.com/WordPress/gutenberg/pull/43379)
- [x] Mark which attributes of the image should be considered content. [43280](https://github.com/WordPress/gutenberg/pull/43280)
- [x] Try different resting state for placeholder, alternate version [43180](https://github.com/WordPress/gutenberg/pull/43180)
- [x] Add an explicit error message if an image block fails to load the image. [40982](https://github.com/WordPress/gutenberg/pull/40982)
- [x] Add border block support for color, width, and style [31366](https://github.com/WordPress/gutenberg/pull/31366)
- [x] Add tooltip on replace image's URL [41504](https://github.com/WordPress/gutenberg/pull/41504)
- [x] Add new duotone filter icon [40435](https://github.com/WordPress/gutenberg/pull/40435)
- [x] Simpler clear button.  [40437](https://github.com/WordPress/gutenberg/pull/40437)
- [x] Remove redundant block name from "settings" panels [40275](https://github.com/WordPress/gutenberg/pull/40275)
- [x] Add ability to unset duotone in themes with default duotone set [39564](https://github.com/WordPress/gutenberg/pull/39564)

## Updating for 6.0
- [x] Reflect media deletion in the editor. [35973](https://github.com/WordPress/gutenberg/pull/35973)
- [x] Block Styles: Show style preview when hovered or focused. [34522](https://github.com/WordPress/gutenberg/pull/34522)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos are up to date
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by heyawhite** [comment]
A post author block for Admin
<img width="767" alt="post-author-block_blank" src="https://user-images.githubusercontent.com/2766281/171614165-2f41061b-cd51-4ddb-b444-3942af40cfb4.png">

Edit details of the post author block
<img width="277" alt="post-author-block_details" src="https://user-images.githubusercontent.com/2766281/171614168-9d7e0e09-ce3a-4245-8545-8fcc69a8704c.png">

Choose a color for the post author block
<img width="597" alt="post-author-block_color" src="https://user-images.githubusercontent.com/2766281/171614179-61e66e82-5e1b-4a2b-a0bf-9991a576c433.png">

Add a new block for post author
<img width="420" alt="post-author-block_plus" src="https://user-images.githubusercontent.com/2766281/171614188-c88de094-9560-4149-b381-794a399ad32c.png">

**Comment by heyawhite** [comment]
Advanced settings for the post author block
<img width="280" alt="Advanced settings" src="https://user-images.githubusercontent.com/2766281/171614441-de5e652a-3843-44f0-816a-8165dee3fb32.png">

**Comment by femkreations** [comment]
Added tasks for 6.1

**Comment by rumejan** [comment]
Hello! Can I work on this? WP.org username is @onlyincebu.

**Comment by rumejan** [comment]
The image under the line "The image block can be added to a page by clicking on the Add Block button" can be replaced with the one below to show both options to add a block. 

<img width="1004" alt="Screen Shot 2023-02-17 at 11 06 37 AM" src="https://user-images.githubusercontent.com/4752299/219547473-4f89259f-aee9-4b4a-bcd8-45b87334efeb.png">

**Comment by femkreations** [comment]
@rumejan I have added a few tasks for 6.2 related. Pls let me know if you have any questions.

**Comment by aurooba** [comment]
@femkreations I can get this handled for 6.2 once I have access to the docs site. :)

**Comment by femkreations** [comment]
Moving this task to 6.3 Project board and adding tasks related to 6.3. @aurooba Pls let me know if you want to continue the work on this.

**Comment by cgarofalo** [comment]
@femkreations Please assign me. Thanks!

**Comment by cgarofalo** [comment]
##New Screenshots for 6.3:

**Add an image block:**
<img width="1075" alt="add_image_block" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/acfc3ee3-585f-495a-9ef8-7927f1b1c7be">
**Add an image block `/image`:**
<img width="390" alt="add_image_block_type" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/7e64723b-c8b3-45c4-ad74-0b26dcd6e675">
**Block with toolbar:**
<img width="674" alt="image_block_with_toolbar" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/7a7baf4a-873e-4c1c-87a6-0e835f743468">
**Adding an image dialogue:**
<img width="675" alt="Image_Block_Dialogue" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/e17b6eaa-991e-40f4-ad5e-d54599b082eb">
**Media Library View:**
<img width="1889" alt="image_block_media_library" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/c0f24437-fe99-4965-94f3-d89ed7227ae3">

[More coming]

**Comment by zzap** [comment]
> Allow dropping an image on an empty paragraph block to create an image block https://github.com/WordPress/gutenberg/pull/42722


https://github.com/WordPress/Documentation-Issue-Tracker/assets/1508963/50e6cfc7-a224-41d7-9952-b3c0072bc58b

**Comment by zzap** [comment]
6.2 updates are completed

**Comment by zzap** [comment]
>Upload Openverse images when inserted


https://github.com/WordPress/Documentation-Issue-Tracker/assets/1508963/65f11bad-f5ab-468d-9d93-8fb26d6b6e7a

**Comment by zzap** [comment]
The lightbox seems to be dependent on theme.json settings, and the default theme doesn't have it, so we're not including it in the documentation to avoid frustrating users.
