### ISSUE TITLE
[HelpHub] Paragraph block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#279]
Article:  https://wordpress.org/support/article/paragraph-block/

## Updating for 6.0
- [ ] Merge text settings into typography panel. [36334](https://github.com/WordPress/gutenberg/pull/36334)
- [x] Add a link completer for inline links to posts. [29172](https://github.com/WordPress/gutenberg/pull/29172)

### Updating for 5.9
- [x] Refer to the [tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues/124)

## General
- [x] Make sure all screenshots are relevant for the current version (6.0)
- [x] Make sure videos are up to date
- [x] Make sure the headings are in sentence case
- [x] Update the changelog at the end of the article

**Comment by atachibana** [comment]
From #124 
- Add Keyboard Input inline format - https://github.com/WordPress/gutenberg/pull/26801

I created the draft document and will enhance it to the HelpHub article.

@zzap @femkreations 
Please feel free to comment below document or this issue.
https://docs.google.com/document/d/1Br4YavsM4kd2hG5e980WjbHgQkbZLCIfGeWF8T7kxwo/edit?usp=sharing

**Comment by zzap** [comment]
Hi @atachibana , great work on this, thank you so much :heart: 

I would just add one thing. Since block locking is for every block I'd create reusable block for that part. Once inserted into the article it **has** to be converted to regular block for two reasons:

- reusable blocks are not visible for locales on rosetta sites
- the screenshot can be safely updated to match the block name

**Comment by atachibana** [comment]
@zzap 
Thank you. Please feel free to modify the article or let me modify it when you are ready.
Also, I updated the article base on your comments on Google Docs. Thanks, again.

**Comment by femkreations** [comment]
@samxmunoz Pls take a look and review the article. Also pls make sure the content is updated for 6.0

**Comment by samxmunoz** [comment]
@femkreations - FYI - this has been reviewed and updated. I am marking it as "completed"

**Comment by samxmunoz** [comment]
I have reviewed everything - the first item "Merge text settings into typography panel #36334" is still being discussed, but otherwise everything is good to go.

**Comment by femkreations** [comment]
Thanks for reviewing @samxmunoz. Since we are moving the Typography Settings to a separate new page and revamping all the block articles by linking to the new page, #478 let's leave the "Merge text settings into typography panel #36334" item for now. Closing this issue.
