### ISSUE TITLE
[HelpHub] Post Excerpt block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#280]
Article:  https://wordpress.org/support/article/post-excerpt-block/

## Updating for 6.1
- [ ] Update the placeholder for post excerpt. [40178](https://github.com/WordPress/gutenberg/pull/40178)
- [ ] Remove redundant block name from "settings" panels [40275](https://github.com/WordPress/gutenberg/pull/40275)

## Updating for 6.0
- [ ] Add to and from Post Content transformations. [37651](https://github.com/WordPress/gutenberg/pull/37651)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by leonidasmi** [comment]
I'm picking this up to add screenshots for this :)

**Comment by leonidasmi** [comment]
Grabbed a video for the transformation:


https://user-images.githubusercontent.com/12400734/190127728-1de76f1a-4970-4c44-937d-eabcf5040313.mp4

**Comment by leonidasmi** [comment]
@zzap ☝️ 😃

**Comment by femkreations** [comment]
Adding 6.1 tasks

## Notes
1. Pls make 6.1 updates first and then move into 6.0.
2. For 6.0, you can pick the screenshots/video added in the comments previously.

**Comment by Ignasrimkunas** [comment]
@zzap Will take this

**Comment by Ignasrimkunas** [comment]
@zzap, both the 6.1 and 6.0 updated. Redid all the screenshots and videos. I also added explanations for the new functionalities and left only the placeholders for the Block Settings section 

https://docs.google.com/document/d/1IRKea-dgu4Ci6bp8KCwAPh1-K8Is2-YgiKTg4QM7sFk/edit?usp=sharing

**Comment by emmasophieyoung** [comment]
@femkreations 1st review done, ready for you

**Comment by femkreations** [comment]
Thanks @Ignasrimkunas and @emmasophieyoung for your awesome work. The content looks great. Here is the updated article. I have updated the Block settings section with links to the overview pages.
https://wordpress.org/support/article/post-excerpt-block/
