### ISSUE TITLE
[HelpHub] Post Content block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#281]
Article:  https://wordpress.org/support/article/post-content-block/

## Updating for 6.1
- [x] Update post content placeholder. [40177](https://github.com/WordPress/gutenberg/pull/40177)
- [x] Add typography supports. [43339](https://github.com/WordPress/gutenberg/pull/43339)
- [x] Add justification controls to constrained layout. [44065](https://github.com/WordPress/gutenberg/pull/44065)

## Updating for 6.0
- [x] Add to and from Post Content transformations. [37651](https://github.com/WordPress/gutenberg/pull/37651)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos are up to date
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

**Comment by jaz-on** [comment]
@zzap I'm taking this one

**Comment by zzap** [comment]
Hey @jaz-on , are you still working on this one?

**Comment by jaz-on** [comment]
Hi @zzap so sorry I forgot about this one! :/
Not sure I'll have time to finish it in the coming weeks... it may be better to release the ticket if someone else is available to handle it!

**Comment by femkreations** [comment]
Added 6.1 tasks

## Notes
1. We are not adding updates for the Block settings as we are revamping the block settings for all the block articles
2. Pls make 6.1 updates first and then move into 6.0.
3. Some of the PRs for 6.1 have great videos that can be added to the article (even for the Block settings section)

**Comment by alianschiavoncini** [comment]
The option justification has been added to Layout. This is a new screenshot.
![post-content-layout-justification](https://user-images.githubusercontent.com/42210724/201332520-943c1840-2e1c-4498-9052-2f604442fd51.png)

**Comment by Leonardus-Nugraha** [comment]
Content updated
