### ISSUE TITLE
[HelpHub] Post Date block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#282]
Article:  https://wordpress.org/support/article/post-date-block/

## Updating for 6.0
- [ ] Allow user to pick Site Default, a suggested date format, or a custom date format. [39209](https://github.com/WordPress/gutenberg/pull/39209)

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Make sure videos are up to date
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

**Comment by femkreations** [comment]
Added tasks for 6.1

## Notes
1. We are not adding detailed updates for the Block settings as we are revamping the block settings for all the block articles 
2. Pls make 6.1 updates first and then move into 6.0.
3. Some of the PRs for 6.1 have great videos that can be added to the article (even for the Block settings section)

**Comment by yogskr** [comment]
Hey @Leonardus-Nugraha, assign me this issue. Thank you!

**Comment by femkreations** [comment]
moving this into the 6.2 Project board

**Comment by cgarofalo** [comment]
I'd like to contribute to this!

**Comment by shabnam611** [comment]
Hi @zzap 
Can I work on this one?

**Comment by shabnam611** [comment]
Completed this one. Kindly set this for 2nd review
@zzap @femkreations @Leonardus-Nugraha @jennimckinnon

**Comment by femkreations** [comment]
Hi @shabnam611, Thank you for working on this one. I've added 1 task for 6.3. Can you pls add that to the page as well. The task has been moved to the 6.3 project board.

**Comment by shabnam611** [comment]
@femkreations 

Sure, I will update and confirm.

**Comment by shabnam611** [comment]
Hi @femkreations 

I have added the changes for 6.3. Kindly set this for 1st review.

**Comment by femkreations** [comment]
Thanks @shabnam611 Will review it soon.

**Comment by femkreations** [comment]
@shabnam611 Here are my comments
1: Pls update the block toolbar screenshots and relevant content under Block Toolbar (new screenshots have the pen icon) including the More Options.
2. Pls update the Block settings sidebar screenshots (Preview button has been updated in 6.3) and relevant content.
3. Include the "Post date block variation for post modified date" content as a note under "Last modified date" in the Block settings sidebar. The POst Date block changes into the Post modified block when you turn on this switch.

Thanks for working on these updates!

**Comment by shabnam611** [comment]
Hi @femkreations 

Thank you for the findings. Sorry about the missing changes.

**Comment by femkreations** [comment]
Awesome job! Everything looks great. I've scheduled the article to be published on Aug 8th.

**Comment by shabnam611** [comment]
Thank you @femkreations
