### ISSUE TITLE
[HelpHub] Query Loop block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#283]
Article:  https://wordpress.org/documentation/article/query-loop-block/

## Update for 6.2
- [x] Remove color block supports. [46147](https://github.com/WordPress/gutenberg/pull/46147)
- [x] Show pattern titles in setup [46688](https://github.com/WordPress/gutenberg/pull/46688)
- [x] Use BlockPatternsList component for Query block patterns modal [47366](https://github.com/WordPress/gutenberg/pull/47366)
- [x] Move block variation picker styles in the iframe [47109](https://github.com/WordPress/gutenberg/pull/47109)
- [x] Add help text on the HTML element for the Comments and Query Loop blocks [46989](https://github.com/WordPress/gutenberg/pull/46989)

## Updating for 6.1
- [x] Fix alignments for children of Query block [44144](https://github.com/WordPress/gutenberg/pull/44144)
- [x] Add justification controls to constrained layout [44065](https://github.com/WordPress/gutenberg/pull/44065)
- [x] Honour intended post type [43285](https://github.com/WordPress/gutenberg/pull/43285)
- [x] Try filters with ToolsPanel  [42629](https://github.com/WordPress/gutenberg/pull/42629)
- [x] Add parents filter [40933](https://github.com/WordPress/gutenberg/pull/40933)

## Updating for 6.0
- [x] Add multiple authors support. [38024](https://github.com/WordPress/gutenberg/pull/38024)
- [x] Add support for custom taxonomies filtering. [38063](https://github.com/WordPress/gutenberg/pull/38063)
- [x] Update query block creation and replacement flows. [38997](https://github.com/WordPress/gutenberg/pull/38997)
- [x] Link to the Pagination block page #237 for the pagination details

**Explain the following features using video/screenshot/note:**
customizing what is shown when there are no results (showing No Results in Query Loop).

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Pls make 6.2 updates first and then move to 6.1.
3. Some of the PRs have great videos that can be added to the article
4. For 6.1, you can pick the screenshots added in the comments previously, if they are relevant.

**Comment by femkreations** [comment]
Added 6.1 tasks

## Notes
1. We are not adding detailed updates for the Block settings as we are revamping the block settings for all the block articles 
2. Pls make 6.1 updates first and then move into 6.0.
3. Some of the PRs for 6.1 have great videos that can be added to the article (even for the Block settings section)

**Comment by nielsbroekzitter** [comment]
Wordking on justification controls video

**Comment by Ignasrimkunas** [comment]
Ready for 1st review https://docs.google.com/document/d/17YXlDU5rjyt3eLTH_G3FDRA3JzchNNc2WvQXO_GabkA/edit?usp=sharing

**Comment by sereedmedia** [comment]
clarifying: is the audience for this article the end user?

**Comment by femkreations** [comment]
@sereedmedia This is all part of the end user documentation so yes. The page goes into the end user documentation.

**Comment by emmasophieyoung** [comment]
First review done!

**Comment by Leonardus-Nugraha** [comment]
Thanks @Ignasrimkunas & @emmasophieyoung!
Content udpated: https://wordpress.org/documentation/article/query-loop-block/

**Comment by mrfoxtalbot** [comment]
Just noting that I have fixed the headings structure on this article. A lot of headings were missing and we had bold text paragraphs with custom sizes. Let's stick to headings 🙏 .

Thank you!
