### ISSUE TITLE
[HelpHub] Quote block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#284]
Article:  https://wordpress.org/support/article/quote-block/

## Updating for 6.0
- [x] Remove the Large style option from the quote block. [37580](https://github.com/WordPress/gutenberg/pull/37580)
- [x] Add color support to the quote block. [39899](https://github.com/WordPress/gutenberg/pull/39899)

### Updating for 5.9
- [x] Refer to the [tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues/141)

## General
- [x] Make sure all screenshots are relevant for the current version (6.0)
- [x] Make sure videos are up to date
- [x] Make sure the headings are in sentence case
- [x] Update the changelog at the end of the article

**Comment by michaelbriantina** [comment]
I'll check on this!

**Comment by michaelbriantina** [comment]
The 'Transform to' section how has 'columns' as an option, as well as the Styles section

![image](https://user-images.githubusercontent.com/30507511/168258929-91c7c77d-98ed-4f9f-8d75-bccdca0fc5dc.png)

--

The color settings after transforming it into a 'group' block now appear differently for both text and background

![image](https://user-images.githubusercontent.com/30507511/168259382-f110c02c-c7b8-49db-a707-4f2df7b1f997.png)

But something of note. It seems you don't need to transform it into a group in order to change the color settings, as it's already in the options for the 'Quote' block by default already.

--

The 'more text editing options' now show slightly different options: (it now has 'highlight', 'keyboard input', and 'text color' has been removed)

<img width="159" alt="image" src="https://user-images.githubusercontent.com/30507511/168259808-aa966831-0ac9-49ed-8deb-acff58a70303.png">

--

The 'More Options' now has slightly different options (additional 'Lock' section)

<img width="262" alt="image" src="https://user-images.githubusercontent.com/30507511/168260257-79495327-b94c-4a5b-a845-3eba11766e9a.png">

--

The 'Styles' now just show 'default' and 'plain'

<img width="281" alt="image" src="https://user-images.githubusercontent.com/30507511/168260484-95fd892f-606c-43b2-807e-f12d732af26c.png">

--

In the block settings, there is now also the option for 'colors' as well as 'typography'

![image](https://user-images.githubusercontent.com/30507511/168260712-bba6bd6c-423b-44bb-8b3f-57d8b348d5f2.png)
