### ISSUE TITLE
[HelpHub] Social Icons block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#288]
Article: https://wordpress.org/support/article/social-icons/

## Updating for 6.0
- [ ] Add the ability to show/hide labels. [38152](https://github.com/WordPress/gutenberg/pull/38152)

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Make sure videos are up to date
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

**Comment by cavalierlife** [comment]
I will check and add screenshots for this one.

**Comment by cavalierlife** [comment]
Updated 6.0 screenshots:



![Image](https://user-images.githubusercontent.com/28687464/189544313-25e7b246-4185-4856-b49d-4e933c390217.png)
![Image](https://user-images.githubusercontent.com/28687464/189544308-7170497c-d21a-4f56-87f3-d65e1a7c49db.png)
![Image](https://user-images.githubusercontent.com/28687464/189544314-fa181013-a899-4092-af87-9dcc5d1bab9f.jpeg)
![Image](https://user-images.githubusercontent.com/28687464/189544311-e4fc0a4d-7784-48f4-afd2-5c9e8623bfd9.jpeg)
![Image](https://user-images.githubusercontent.com/28687464/189544309-9bb5bf0f-82c6-48c8-a14d-a1b50a8e3380.jpeg)
![Image](https://user-images.githubusercontent.com/28687464/189544315-ed6bc95d-ba83-48a0-84d2-107a0f746423.jpeg)
![Image](https://user-images.githubusercontent.com/28687464/189544310-7898219a-0d64-4a14-9ef2-9308b48cf9b5.jpeg)
![Image](https://user-images.githubusercontent.com/28687464/189544312-a7e46be7-c63a-41d6-9c3b-6f387869faf0.jpeg)
![Image](https://user-images.githubusercontent.com/28687464/189544317-f4bb0ffb-1289-4ccf-a0a7-acaf17e6a952.jpeg)
![Image](https://user-images.githubusercontent.com/28687464/189544316-76e9f3e7-a82b-4594-ba31-a4d1ec3ed5a1.jpeg)

**Comment by cavalierlife** [comment]
@femkreations Please review the updated screenshots. Any not here are already up to date.

**Comment by femkreations** [comment]
Thanks @cavalierlife for the screenshots. They made it easier to update the page. Here is the page with the updates.

https://wordpress.org/support/article/social-icons/.

Also, I updated the content for 6.0 adding the following– Change items justification, block settings items, dimension control, added ALT tags for the images, reformatted the article, corrected spellings, and converted Reusable blocks to regular blocks.
