### ISSUE TITLE
[HelpHub] Spacer block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#289]
Article:  https://wordpress.org/support/article/spacer-block/

## Updating for 6.3
- [x] Adapt flex child controls for Spacer [49362](https://github.com/WordPress/gutenberg/pull/49362)
- [x] Add spacing presets to the spacer block [44002](https://github.com/WordPress/gutenberg/pull/44002)

## Updating for 6.1
- [x] Add spacing block supports [43366](https://github.com/WordPress/gutenberg/pull/43366)
- [x] Remove redundant block name from "settings" panels [40275](https://github.com/WordPress/gutenberg/pull/40275)

## Updating for 6.0
- [x] Add custom units for height and width. [36186](https://github.com/WordPress/gutenberg/pull/36186)
- [x] Note the resizable box and controls [39577](https://github.com/WordPress/gutenberg/pull/39577)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos are up to date
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

**Comment by wmjohnston06** [comment]
I am working on this issue during Contributor Day at WordCamp Europe 2022.

**Comment by wmjohnston06** [comment]
**_Suggested change 1: In the first paragraph of the article, update the text to read:_**

"If you want to have a space between two blocks, the spacer block is what you will use. 
A **vertical** spacer adds space between blocks in a column (as in a page or post).
A **horizontal** spacer adds space between blocks in a row (as in a [Navigation block](https://wordpress.org/support/article/navigation-block/)).

(Note:  Using a Navigation block requires a [block theme](https://wordpress.org/themes/tags/full-site-editing/) or a theme that has support for [template editing](https://wordpress.org/themes/tags/template-editing/).)



**_Suggested change 2:  In the paragraph under the heading "Spacer Settings", change the text_** 

_From:_  
"The Height setting adjusts the height of the space you want to add by typing the number."
_To:_
"The Height setting adjusts the height of the space.  The Width setting adjusts the width of the space.  You can adjust the settings by either:
- Typing the number in the "Spacer Settings" box, or
- Dragging the handle at the bottom of the spacer (for the vertical spacer) or at the side of the spacer (for the horizontal spacer).

**Comment by luminuu** [comment]
### Screenshots for 6.0

**More options**
<img width="371" alt="grafik" src="https://user-images.githubusercontent.com/7585600/171646685-19eb1080-7493-4d85-ba96-08884d4cd6c2.png">

**Comment by cavalierlife** [comment]
I'd like to work on this one.

**Comment by cavalierlife** [comment]
### Screenshots for 6.0
Add new spacer block with /

![Image](https://user-images.githubusercontent.com/28687464/189541348-49772276-96e3-4eac-9fde-4b08df482b83.jpeg)

**Comment by cavalierlife** [comment]
@femkreations These screenshots are ready to review.

**Comment by wmjohnston06** [comment]
Donna,

Please run with it.  I'm embarrassed that I never finished it, but I've 
had a string of other commitments since I got back from WCEU.

Thanks,

Mike

*Mike Johnston*
Founder | Author
MyManagementMentor.com
***@***.***
+1 812-350-4628

**Comment by cavalierlife** [comment]
No need to be embarrassed, @wmjohnston06 . And since I'm a new contributor, it's always possible I shouldn't have interrupted your process. I have no idea! Either way, we'll call this a team effort, right? :)

**Comment by femkreations** [comment]
Thanks @wmjohnston06 and @cavalierlife for adding in the content for the previous versions.

I am adding in the tasks for 6.1.

## Notes
1. We are not adding updates for the Block settings as we are revamping the block settings for all the block articles 
2. Pls make 6.1 updates first and then move into 6.0.
3. For 6.0, you can pick the screenshots added in the comments previously.

**Comment by chrisjangl** [comment]
I can help out here, @zzap.

**Comment by femkreations** [comment]
moving this into the 6.2 Project board

**Comment by jomarieminney** [comment]
I can make the above changes in WP and re-record the video if you want to assign this to me

**Comment by femkreations** [comment]
Added tasks for 6.3 and moved to 6.3 project board. @jomarieminney Pls let me know if you want to continue working on this.

**Comment by zzap** [comment]
Hey @gabrlknght, this issue is already assigned to @chrisjangl.<br>A maintainer can also add you to the list of assignees or swap you with the current assignee. Or you can take a look at other unassigned issues we have.<br>

**Comment by zzap** [comment]
![Spacer Block Settings Panel](https://github.com/WordPress/Documentation-Issue-Tracker/assets/1508963/8e5ea68f-ff8b-4ee3-b45c-8ad0f5f97b41)

**Comment by zzap** [comment]
I updated the article with updates for all versions. Thank you to everyone who contributed, you are heroes :heart:  

I just created a new `good first issue` if anyone wants to go over the screenshots and make sure they are up to date.

https://github.com/WordPress/Documentation-Issue-Tracker/issues/1241

Closing this one now.
