### ISSUE TITLE
[HelpHub] Tag Cloud block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#290]
Article:  https://wordpress.org/support/article/tag-cloud-block/

## Updating for 6.0
- [x] Add outline style. [37092](https://github.com/WordPress/gutenberg/pull/37092)
- [x] Transforms between Tag Cloud and Categories. [38566](https://github.com/WordPress/gutenberg/pull/38566)

### Updating for 5.9
- [x] Refer to the [tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues/158)

## General
- [x] Make sure all screenshots are relevant for the current version (6.0)
- [x] Make sure videos are up to date
- [x] Make sure the headings are in sentence case
- [x] Update the changelog at the end of the article

**Comment by evrpress** [comment]
Added screenshots to #158

**Comment by femkreations** [comment]
Updated the article for 6.0 with the screenshots and content and added ALT tags and a changelog.
