### ISSUE TITLE
[HelpHub]: Template Part block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#291]
Article:  https://wordpress.org/documentation/article/template-part-block/

## Update for 6.3
- [x] Sort template parts by type in navigation screen. [50841](https://github.com/WordPress/gutenberg/pull/50841)
- [x] Add corresponding area icon to template part menu items. [52102](https://github.com/WordPress/gutenberg/pull/52102)
- [x] Library: Rename template parts to library. [50769](https://github.com/WordPress/gutenberg/pull/50769)
- [x] Add chevrons to the templates and template parts in site editor [50076](https://github.com/WordPress/gutenberg/pull/50076)
- [x] Bring back revisions button for template parts [49163](https://github.com/WordPress/gutenberg/pull/49163)
- [x] Add "Added by" description to template part navigation sidebar [48732](https://github.com/WordPress/gutenberg/pull/48732)
- [x] Change "Browse all templates" to "Manage all templates" in template details popover [48496](https://github.com/WordPress/gutenberg/pull/48496)
- [x] Remove TemplateAreas from template details [48490](https://github.com/WordPress/gutenberg/pull/48490)
- [x] Append template type and name to the site editor page title [47855](https://github.com/WordPress/gutenberg/pull/47855)
- [x] Add a nested level when selecting templates or template parts [47777](https://github.com/WordPress/gutenberg/pull/47777)
- [x] Add corresponding area icon to template part menu items [50791](https://github.com/WordPress/gutenberg/pull/50791)
- [x] Update Template Parts icon to use the symbol [50410](https://github.com/WordPress/gutenberg/pull/50410)
- [x] Template revisions: require 2 revisions before showing the revisions UI [50762](https://github.com/WordPress/gutenberg/pull/50762)
- [x] Make sticky block action on template part block [49219](https://github.com/WordPress/gutenberg/pull/49219)
- [x] Add a "Make sticky" action to the Template Part block [49085](https://github.com/WordPress/gutenberg/pull/49085)
- [x]  Add Library for Template Parts & Patterns Management [51078](https://github.com/WordPress/gutenberg/pull/51078)
- [x] add footer to template part and ensure nested template areas display [51669](https://github.com/WordPress/gutenberg/pull/51669)

## Updating for 6.2
- [x] Colorize template parts and Reusable blocks [45473](https://github.com/WordPress/gutenberg/pull/45473)
- [x] Add an option to import widgets from the sidebars [45509](https://github.com/WordPress/gutenberg/pull/45509)
- [x] Avoid duplicate titles on creation [46996](https://github.com/WordPress/gutenberg/pull/46996)
- [x] Allow adding new templates and template parts directly from the sidebar [46458](https://github.com/WordPress/gutenberg/pull/46458)

## Updating for 6.1
- [x] Make template part and reusable block creation language consistent [43032](https://github.com/WordPress/gutenberg/pull/43032)
- [x] Add search to replacement modal [42459](https://github.com/WordPress/gutenberg/pull/42459)
- [x] Add block variations for individual template parts [42454](https://github.com/WordPress/gutenberg/pull/42454)
- [x] Swap block action places [42221](https://github.com/WordPress/gutenberg/pull/42221)
- [x] Only allow template part to be replaced if its a header or footer [40787](https://github.com/WordPress/gutenberg/pull/40787)
- [x] Bundle new collection of Header and Footer block patterns [43157](https://github.com/WordPress/gutenberg/pull/43157)
- [x] Allow changing properties in focus mode [43151](https://github.com/WordPress/gutenberg/pull/43151)

## Updating for 6.0
- [x] Show existing template parts and a list of block patterns at creation flow. [38814](https://github.com/WordPress/gutenberg/pull/38814)
- [x] Remove support for conversion to Reusable block. [36918](https://github.com/WordPress/gutenberg/pull/36918)
- [x] Remove color, spacing, and layout options. [36571](https://github.com/WordPress/gutenberg/pull/36571)
- [x] Remove the spotlight mode from template parts [40652](https://github.com/WordPress/gutenberg/pull/40652)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Pls make 6.2 updates first and then move to 6.1.
3. Some of the PRs have great videos that can be added to the article
4. For 6.1, you can pick the screenshots added in the comments previously, if they are relevant.

**Comment by femkreations** [comment]
Added tasks for 6.1

**Comment by tanazmasaba** [comment]
@femkreations Hi, I'd like to be assigned to this one if that's alright?

**Comment by jennimckinnon** [comment]
@tanazmasaba You're assigned! Thank you and have fun :)

**Comment by femkreations** [comment]
Moving this to 6.3

**Comment by shabnam611** [comment]
I would like to work on this one.

**Comment by femkreations** [comment]
Refer to this PR for details https://github.com/WordPress/gutenberg/issues/50392

**Comment by shabnam611** [comment]
Hi @femkreations 

For this ticket, I was unable to add all the changes while using 6.3-RC3. Here is the list of the updates I made for 6.3:

- [Sort template parts by type in navigation screen]( https://github.com/WordPress/gutenberg/pull/50841 ).

I have added screenshot that depicts the sorting under a new section that I created i.e **Creating new template parts from the template part list**

- [Add corresponding area icon to template part menu items](https://github.com/WordPress/gutenberg/pull/52102). 

I noticed the library has been replaced by Pattern so the screenshot from the section **Creating new template parts from the template part list** covers this as well. 

- [Library: Rename template parts to library](https://github.com/WordPress/gutenberg/pull/50769). 

I noticed this PR is dated as May 19th and the one [52102](https://github.com/WordPress/gutenberg/pull/52102) was on June 29th so I am assuming the one dated with June 29th is the latest one. Is that correct? 

- [Add chevrons to the templates and template parts in site editor](https://github.com/WordPress/gutenberg/pull/50076) and 
- [Change "Browse all templates" to "Manage all templates" in template details popover ](https://github.com/WordPress/gutenberg/pull/48496)

In the section **Creating new template parts from the template part list**, the screenshot shows chevron icons on the left of patterns and on the right of manage all template parts and manage all patterns. Since there is no description of template, I didn't add screenshot for template's chevron icon. 

In the same screenshot, the manage all template parts is shown. 

- [Add "Added by" description to template part navigation sidebar ](https://github.com/WordPress/gutenberg/pull/48732)

I created this section **Managing template parts and patterns**, and there I added a screenshot that shows the Added by for template parts. 

- [Append template type and name to the site editor page title ](https://github.com/WordPress/gutenberg/pull/47855)

I understand the change, but I was not sure how to incorporate it or if it is required to do so. 

- [Update Template Parts icon to use the symbol](https://github.com/WordPress/gutenberg/pull/50410) 

I updated the screenshots to show the latest Template parts icon

- [Add footer to template part and ensure nested template areas display](https://github.com/WordPress/gutenberg/pull/51669) 

I was able to locate this but I am not sure how to incorporate this, Shall I create a new topic for this? Will it go after advanced? 



**Couldn't find/couldn't work on**: 

- [Bring back revisions button for template parts](https://github.com/WordPress/gutenberg/pull/491) and [Template revisions: require 2 revisions before showing the revisions UI](https://github.com/WordPress/gutenberg/pull/50762) 

I couldn't find this revisions for template part

[Make sticky block action on template part block](https://github.com/WordPress/gutenberg/pull/49219) was reverted in [Add a "Make sticky" action to the Template Part block ](https://github.com/WordPress/gutenberg/pull/49085). So I didn't add any changes for this. 

- [Remove TemplateAreas from template details](https://github.com/WordPress/gutenberg/pull/48490) 
- [Add a nested level when selecting templates or template parts](https://github.com/WordPress/gutenberg/pull/47777) 
- [Add corresponding area icon to template part menu items](https://github.com/WordPress/gutenberg/pull/50791) 
- Add Library for Template Parts & Patterns Management https://github.com/WordPress/gutenberg/pull/51078

**Comment by atachibana** [comment]
@shabnam611 

Hi Mushrit, Thank you for the contribution and sorry for the late review.
All your suggestions and comments regarding 6.3 are appropriate.
Could you check 6.0, 6.1, and 6.2 as well? If the current version has changed in behavior or UI, you can ignore all of them. If you do not have the time, I will be happy to take over for you.

Here are a few comments in response to your question. Again, no action required of you.

> Library: Rename template parts to library.
> I noticed this PR is dated as May 19th and the one 52102 was on June 29th so I am assuming the one dated with June 29th is the latest one. Is that correct?

Yes, you can ignore this PR.

> Append template type and name to the site editor page title
> I understand the change, but I was not sure how to incorporate it or if it is required to do so.

You don't need do anything. As you said, this is not related to this content.

> Add footer to template part and ensure nested template areas display
> I was able to locate this but I am not sure how to incorporate this, Shall I create a new topic for this? Will it go after advanced?

Again, you don't do anything. This is user experience improvement.

> Bring back revisions button for template parts and Template revisions: require 2 revisions before showing the revisions UI
> I couldn't find this revisions for template part

As later PR says, you have to have 2 revisions at least.
But again, this is not essential to Template Parts. You can ignore these PRs.

Followings are uncommented PRs.

> Remove TemplateAreas from template details 48490
> Add a nested level when selecting templates or template parts 47777

This is user experience improvement. Let's ignore it.

> Add corresponding area icon to template part menu items 50791

This is covered by your first screenshot

> Add Library for Template Parts & Patterns Management 51078

Still we don't have Library. So we can ignore.

**Comment by atachibana** [comment]
OK, I would like to take over.

## Updating for 6.2
### N/A
UX improvement and not needed:
- Colorize template parts and Reusable blocks 45473
- Avoid duplicate titles on creation 46996

Already included:
- Allow adding new templates and template parts directly from the sidebar 46458

### Task
 Add an option to import widgets from the sidebars 45509

## Imporing widget area

If you've switched from a classic theme to a block theme and widgets created in the classic theme, you can import them from Import Widget Area dropdown in the Advanced Settings. Select the widget from dropdown and click Import.

![importing-widget-area_6 4](https://github.com/WordPress/Documentation-Issue-Tracker/assets/8876600/081c5cf0-e447-4029-b03f-da0f34e056f8)

**Comment by atachibana** [comment]
## Updating for 6.1
### N/A
UX improvement:
- Make template part and reusable block creation language consistent 43032
- Add search to replacement modal 42459
- Add block variations for individual template parts 42454
- Only allow template part to be replaced if its a header or footer 40787
- Allow changing properties in focus mode 43151

Already enhanced:
- Bundle new collection of Header and Footer block patterns 43157

### Task
Swap block action places 42221

## Template part focus mode
... an individual template part. To access this mode, Select the template part and click Edit from the toolbar.

https://github.com/WordPress/Documentation-Issue-Tracker/assets/8876600/7b172953-b7b0-4fda-b3a4-b94fe739b9db

## Replacing one template part with another

If the theme has more than one template part for the same area, you can use the Replace option after clicking on the three dot menu in the block toolbar to replace the current template part with another. If you don’t see this option, this is because the theme hasn’t provided multiple template parts for the same area.
![template-parts-replace-option-6 4](https://github.com/WordPress/Documentation-Issue-Tracker/assets/8876600/1d244bfb-2f41-4e37-8c6c-be4008c99cf2)

**Comment by atachibana** [comment]
## Updating for 6.0
### N/A
UX improvement:
- Remove support for conversion to Reusable block. 36918
- Remove color, spacing, and layout options. 36571
Remove the spotlight mode from template parts 40652

Already enhanced:
- Show existing template parts and a list of block patterns at creation flow. 38814

**Comment by atachibana** [comment]
I've enhanced all and close this PR.
