### ISSUE TITLE
[HelpHub] Post Featured Image block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#293]
Article:  https://wordpress.org/documentation/article/post-featured-image-block/

## Update for 6.3
- [x] Add aspect-ratio to post featured image block. [47854](https://github.com/WordPress/gutenberg/pull/47854)
- [x] Replace "Image size" with "Resolution" in image size controls [44190](https://github.com/WordPress/gutenberg/pull/44190)
- [x] Remove 16:10 from Post Featured Image [48969](https://github.com/WordPress/gutenberg/pull/48969)
- [x] Adjust Post Featured Image PanelBody label to "Settings" [49076](https://github.com/WordPress/gutenberg/pull/49076)
- [x]  [Inserter - Media tab]: Upload Openverse images when inserted [48501](https://github.com/WordPress/gutenberg/pull/48501)

## Update for 6.2
- [x] Enable image size for featured images in templates. [46848](https://github.com/WordPress/gutenberg/pull/46848)
- [x] Update placeholder style [44190](https://github.com/WordPress/gutenberg/pull/44190)

## Updating for 6.1
- [x] Enable gradient overlay. [43838](https://github.com/WordPress/gutenberg/pull/43838)
- [x] Polish placeholder radius and enable duotone. [43425](https://github.com/WordPress/gutenberg/pull/43425)
- [x] Add blurred background to work in nested cases. [43379](https://github.com/WordPress/gutenberg/pull/43379)
- [x] Placeholder: Refactor and simplify dashed placeholders. [43228](https://github.com/WordPress/gutenberg/pull/43228)
- [x] Add link target and rel attributes. [42853](https://github.com/WordPress/gutenberg/pull/42853)
- [x] Add border support applied to inner img. [42847](https://github.com/WordPress/gutenberg/pull/42847)

## Updating for 6.0
- [x] ~Makes cover block dynamic and adds featured image binding. [39658](https://github.com/WordPress/gutenberg/pull/39658)~
- [x] Add duotone to placeholders for site logo and featured image. [40085](https://github.com/WordPress/gutenberg/pull/40085)
- [x] Add size selector. [38044](https://github.com/WordPress/gutenberg/pull/38044)
- [x] Move width and height controls into the Dimensions panel. [36540](https://github.com/WordPress/gutenberg/pull/36540)
- [x] Update featured image placeholder graphic. [36712](https://github.com/WordPress/gutenberg/pull/36712)
- [x] Let Featured Image block inherit dimensions, look like a placeholder. [36517](https://github.com/WordPress/gutenberg/pull/36517)
- [x] Show all the controls when inside a Query Loop. [37945](https://github.com/WordPress/gutenberg/pull/37945)
- [x] Add an illustration option to the Placeholder component [41605](https://github.com/WordPress/gutenberg/pull/41605)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Pls make 6.2 updates first and then move to 6.1.
3. Some of the PRs have great videos that can be added to the article
4. For 6.1, you can pick the screenshots added in the comments previously, if they are relevant.

**Comment by agnieszkaszuba** [comment]
I'll pick this up

**Comment by agnieszkaszuba** [comment]
I have updated the following screenshots. As far as I could see, no other screenshots needed updating.

More options in the Post Featured Image block:
<img width="300" alt="featured-post-image-block-options-6 0" src="https://user-images.githubusercontent.com/32479012/190133467-b81044df-5b2c-4050-8efe-419d1b681f30.png">

Apply duotone filter in the Post Featured Image block
<img width="671" alt="featured-post-image-block-duotone-6 0" src="https://user-images.githubusercontent.com/32479012/190133508-042b239e-71f8-4a11-9824-e1225243f46b.png">

Dimension settings in the Post Featured Image block
<img width="280" alt="featured-post-image-block-dimensions-6 0" src="https://user-images.githubusercontent.com/32479012/190133557-7ccc6108-6b3c-4d8e-84b4-574a301ce374.png">

Reset all Dimension settings
<img width="240" alt="featured-post-image-reset-all-6 0" src="https://user-images.githubusercontent.com/32479012/190133586-eaa0a858-f5b3-447a-99ba-6542095f07fe.png">

**Comment by zzap** [comment]
Hi @agnieszkaszuba , are you still working on this issue?

**Comment by agnieszkaszuba** [comment]
no not currently :)

**Comment by femkreations** [comment]
Thanks @agnieszkaszuba for the work.

**Comment by femkreations** [comment]
Adding tasks for 6.1. Pls make 6.1 updates first and then move into 6.0.
Some of the PRs for 6.1 have great videos that can be added to the article (even for the Block settings section)
For 6.0, you can pick the screenshots added in the comments previously by @agnieszkaszuba. Thanks

**Comment by anandau** [comment]
Hi @femkreations 

I am interested in working on this issue. Please assign this to me.

**Comment by femkreations** [comment]
Hi @anandau I have moved this to the 6.3 project board and added tasks for 6.3. PLs let me know if you want to continue working on this. I can unassign it if not. Its perfectly ok. Thanks

**Comment by anandau** [comment]
I will get it done by next week.

**Comment by anandau** [comment]
The draft is ready for the review 
https://docs.google.com/document/d/1qSzDJYQNnZwz9Li9DCT8BBtHCK_3VfGzvZQ7jGbNBvw/edit?usp=sharing

**Comment by zzap** [comment]
Updated screenshots and videos, added style settings screenshot. Added updates from the document @anandau . Thank you so much for contributing.

TODO: I'll go through each feature item listed above to make sure we address them all in the article.

**Comment by zzap** [comment]
Gradient overlay 

![featured-image-gradient-overlay](https://github.com/WordPress/Documentation-Issue-Tracker/assets/1508963/c3cda069-6fd4-4a54-8b6f-390c707fc3d8)

**Comment by zzap** [comment]
Enable image size for featured images in templates. https://github.com/WordPress/gutenberg/pull/46848

![featured-image-inside-template](https://github.com/WordPress/Documentation-Issue-Tracker/assets/1508963/49bc3add-c38a-498f-86af-ce54a3d977cd)

**Comment by zzap** [comment]
> Add aspect-ratio to post featured image block. https://github.com/WordPress/gutenberg/pull/47854


https://github.com/WordPress/Documentation-Issue-Tracker/assets/1508963/cc6705cb-f65e-4a44-b6fc-2c64bdb3c0d5

**Comment by zzap** [comment]
This one is now completed. Thank you everyone who contributed :heart: :cookie:
