### ISSUE TITLE
[HelpHub] Group block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#296]
Article:  https://wordpress.org/documentation/article/group-block/

## Updating for 6.2
- [x] use a variation picker in the placeholder [43496](https://github.com/WordPress/gutenberg/pull/43496)
- [x] unwrap inner block when pressing Backspace at start. [45075](https://github.com/WordPress/gutenberg/pull/45075)
- [x] Layout child fixed size should not be fixed by default and should always have a value set [46139](https://github.com/WordPress/gutenberg/pull/46139)
- [x] Fix missing border regression [44696](https://github.com/WordPress/gutenberg/pull/44696)
- [x] Merge inner blocks if wrappers are equal [43181](https://github.com/WordPress/gutenberg/pull/43181)
- [x] Sticky Position: Hide controls if the block is non-root (has parents) [47334](https://github.com/WordPress/gutenberg/pull/47334)
- [x] Add a minHeight block support under dimensions [45300](https://github.com/WordPress/gutenberg/pull/45300)

## Updating for 6.1
- [ ] Add justification controls to constrained layout. [44065](https://github.com/WordPress/gutenberg/pull/44065)
- [ ] Fix click-first state. [43513](https://github.com/WordPress/gutenberg/pull/43513)
- [ ] update description to remove "layout". [43498](https://github.com/WordPress/gutenberg/pull/43498)
- [ ] Add missing typography supports. [43308](https://github.com/WordPress/gutenberg/pull/43308)
- [ ] Try "constrained" content width as new layout type. [42763](https://github.com/WordPress/gutenberg/pull/42763)
- [ ] add group unwrap. [42685](https://github.com/WordPress/gutenberg/pull/42685)
- [ ] Enable onEnter support for group block [40724](https://github.com/WordPress/gutenberg/pull/40724)
- [ ] Add a clickable Group setup state. [40664](https://github.com/WordPress/gutenberg/pull/40664)
- [ ] Merging blocks: allow x to be merged into wrapper blocks [42780](https://github.com/WordPress/gutenberg/pull/42780)

## Updating for 6.0
- [ ] New Group, Stack, Row block descriptions. [40176](https://github.com/WordPress/gutenberg/pull/40176)
- [ ] Add margin support. [37344](https://github.com/WordPress/gutenberg/pull/37344)
- [ ] Add Gap support. [37459](https://github.com/WordPress/gutenberg/pull/37459)
- [ ] Add the typography support. [37456](https://github.com/WordPress/gutenberg/pull/37456)
- [ ] Add transform to row variation. [36202](https://github.com/WordPress/gutenberg/pull/36202)
- [ ] Add the stack block variation to the group block. [39690](https://github.com/WordPress/gutenberg/pull/39690)
- [ ] Show group option in Group blocks. [39094](https://github.com/WordPress/gutenberg/pull/39094)
- [ ] BlockToolbar: Show Group button in toolbar when multiple blocks are selected. [39710](https://github.com/WordPress/gutenberg/pull/39710)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Pls make 6.2 updates first and then move to 6.1.
3. Some of the PRs have great videos that can be added to the article
4. For 6.1, you can pick the screenshots added in the comments previously, if they are relevant.

**Comment by femkreations** [comment]
Added 6.1 tasks

**Comment by alianschiavoncini** [comment]
The "None" option has been added to the alignment dropdown.
![group-block-alignment](https://user-images.githubusercontent.com/42210724/201333496-8e01a95f-2abe-4ae2-9174-21685352c70e.png)

The "More option" has been changed. 
Option labels renamed:
- Hide Block Settings in Hide more settings
- Copy in Copy Block
- Remove Block in Remove Group
- Add to Reusable blocks in Create Reusable block
- Remove Block in Remove Group

Option labels added:
- Lock

![group-block-more-options](https://user-images.githubusercontent.com/42210724/201335530-f2ee2682-a65a-45ce-b7f9-35e72a78d282.png)

The Dimensions option layout has been changed. This is a new screenshot.
![group-block-dimensions](https://user-images.githubusercontent.com/42210724/201336237-3fab8d09-9e3e-4af7-ae8a-806ba9895d3e.png)

**Comment by mrfoxtalbot** [comment]
@Leonardus-Nugraha, did you have the chance to make any progress with this?

**Comment by josevarghese** [comment]
Adding some details which I have noticed while testing the Beta

Once after adding the Group Block, we can select the layout we prefer for the block. The layouts are the following:
1. Group - It helps to gather blocks in a container
2. Row - Arrange blocks horizontally
3. Stack - Arrange blocks vertically

![select-layout-group-block](https://user-images.githubusercontent.com/34977009/228362290-0c99dada-38bb-485e-9265-dbe406687a57.png)
Screenshot showing the layout to be selected

![groups](https://user-images.githubusercontent.com/34977009/228363595-6abc8e15-8c27-422a-af70-46946a39ea16.png)
Screenshot showing how to change the layout in the Sidebar

**Comment by Leonardus-Nugraha** [comment]
@mrfoxtalbot I haven't started this, feel free if you want to take this over

**Comment by mrfoxtalbot** [comment]
This is ready, @femkreations. Can you please mark it as done?

**Comment by mrfoxtalbot** [comment]
I have moved this issue to the "needs review" column. Could you please take take a look @Leonardus-Nugraha? Thank you!

**Comment by Leonardus-Nugraha** [comment]
thanks @mrfoxtalbot! Reviewed the article and all good! Closing this issue.
