### ISSUE TITLE
[HelpHub] Navigation block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#297]
Article:  https://wordpress.org/documentation/article/navigation-block/

## Updating for 6.2
- [ ] Add layout child sizing to the Navigation block. [47584](https://github.com/WordPress/gutenberg/pull/47584)
- [ ] Allow multiple navigations with the same ref. [47453](https://github.com/WordPress/gutenberg/pull/47453)
- [ ] Remove the manage menus button from the selector. [47441](https://github.com/WordPress/gutenberg/pull/47441)
- [ ] Update icons for off-canvas navigation. [47337](https://github.com/WordPress/gutenberg/pull/47337)
- [ ] Remove the list view button from the navigation block. [47032](https://github.com/WordPress/gutenberg/pull/47032)
- [ ] Add more explicit labels to the Navigation Menu Selector. [47015](https://github.com/WordPress/gutenberg/pull/47015)
- [ ] Add a manage menus button to the menu selector dropdown. [47005](https://github.com/WordPress/gutenberg/pull/47005)
- [ ] Add an icon to the add submenu item option. [46884](https://github.com/WordPress/gutenberg/pull/46884)
- [ ] Replace block settings menu with a custom menu in off canvas editor. [46675](https://github.com/WordPress/gutenberg/pull/46675)
- [ ] Update copy of off canvas editor 'add submenu item' option. [46564](https://github.com/WordPress/gutenberg/pull/46564)
- [ ] Add page list to Link UI transforms in Nav block. [46426](https://github.com/WordPress/gutenberg/pull/46426)
- [ ] Adds page list as child of submenu. [46414](https://github.com/WordPress/gutenberg/pull/46414)
- [ ] Add a 'open list view' button. [46335](https://github.com/WordPress/gutenberg/pull/46335)
- [ ] update fallback nav creation to most recently created menu. [46286](https://github.com/WordPress/gutenberg/pull/46286)
- [ ] Move color controls to support panel. [46049](https://github.com/WordPress/gutenberg/pull/46049)
- [ ] Navigation list view: use smaller lock icon. [46578](https://github.com/WordPress/gutenberg/pull/46578)
- [ ] Enable easier drag and drop for navigation building. [45906](https://github.com/WordPress/gutenberg/pull/45906)
- [ ] Add link URL to the navigation submenu inspector controls. [45816](https://github.com/WordPress/gutenberg/pull/45816)
- [ ] Remove anchor support from the navigation block. [44721](https://github.com/WordPress/gutenberg/pull/44721)
- [ ] Remove ellipses as menu icon options for now. [44222](https://github.com/WordPress/gutenberg/pull/44222)
- [ ] Fallback to a classic menu if one is available. [44173](https://github.com/WordPress/gutenberg/pull/44173)
- [ ] Adds content locking to navigation block [44739](https://github.com/WordPress/gutenberg/pull/44739)
- [ ] Add label field to navigation link and navigation submenu [45964](https://github.com/WordPress/gutenberg/pull/45964)

### Updating for OffCanvas Editor feature
- [ ] Use offsite navigation editor on the navigation inspector sidebar [46440](https://github.com/WordPress/gutenberg/pull/46440)
- [ ] Alternative: add inserter to Nav block offcanvas experiment [45947](https://github.com/WordPress/gutenberg/pull/45947)
- [ ] Nav offcanvas editor: add simple back button to inspector controls [45852](https://github.com/WordPress/gutenberg/pull/45852)
- [ ] Add basic edit button UI to Nav block offcanvas editor [45815](https://github.com/WordPress/gutenberg/pull/45815)
- [ ] Add submenu menu item to list view [45794](https://github.com/WordPress/gutenberg/pull/45794)
- [ ] Reposition navigation selector [45555](https://github.com/WordPress/gutenberg/pull/45555)
- [ ] Adds a list view to the navigation block [45546](https://github.com/WordPress/gutenberg/pull/45546)
- [ ] Introduce experiment for inspector based navigation editing [45515](https://github.com/WordPress/gutenberg/pull/45515)
- [ ] Sidebar: Add list view tab for Navigation block et al [45483](https://github.com/WordPress/gutenberg/pull/45483)
- [ ] Alternative Nav Offcanvas show link UI for submenu creation [46857](https://github.com/WordPress/gutenberg/pull/46857)
- [ ] Bring back the heading and the menu selector in the ellipsis menu [46622](https://github.com/WordPress/gutenberg/pull/46622)
- [ ] Removes the header from the navigation list view in the experiment [46070](https://github.com/WordPress/gutenberg/pull/46070)
- [ ] Hide the create new menu button if the experiment is enabled [46019](https://github.com/WordPress/gutenberg/pull/46019)
- [ ] Display inserter popover in offcanvas UI [46013](https://github.com/WordPress/gutenberg/pull/46013)
- [ ] Navigation List view: scroll horizontally when table overflows [45966](https://github.com/WordPress/gutenberg/pull/45966)
- [ ] Reposition navigation selector [45555](https://github.com/WordPress/gutenberg/pull/45555)
- [ ] Update the update icon [46575](https://github.com/WordPress/gutenberg/pull/46575)
- [ ] Remove filters disabling tabs for link and submenu [47593](https://github.com/WordPress/gutenberg/pull/47593)

## Updating for 6.1
- [ ] Hide overlay preview settings when the overlay is off [44032](https://github.com/WordPress/gutenberg/pull/44032)
- [ ]  Try adding minimal animation to overlay [43851](https://github.com/WordPress/gutenberg/pull/43851)
- [ ]  Set the icon control to full width [43844](https://github.com/WordPress/gutenberg/pull/43844)
- [ ]  Add select icon for Navigation Block's menu button [43674](https://github.com/WordPress/gutenberg/pull/43674)
- [ ]   Create classic navigation menus as draft and dirty the site editor [43580](https://github.com/WordPress/gutenberg/pull/43580)
- [ ]  Try making it possible for themes to have the X overlay the = icon [43576](https://github.com/WordPress/gutenberg/pull/43576)
- [ ]  Add missing typography support [43542](https://github.com/WordPress/gutenberg/pull/43542)
- [ ]  Try to improve the appender in an empty block [43115](https://github.com/WordPress/gutenberg/pull/43115)
- [ ]  Add overlay close button to icon toggle control [43067](https://github.com/WordPress/gutenberg/pull/43067)
- [ ]  Improves the UX of menu management in the navigation block [42987](https://github.com/WordPress/gutenberg/pull/42987)
- [ ]  Use page list instead of placeholder as fallback [42735](https://github.com/WordPress/gutenberg/pull/42735)
- [ ] Navigation submenus: Allow Escape key to close the submenu and focus trigger [41774](https://github.com/WordPress/gutenberg/pull/41774)
- [ ]  Inherit font style and font weight [40671](https://github.com/WordPress/gutenberg/pull/40671)
- [ ]  Rename Navigation Menus to Navigation [40413](https://github.com/WordPress/gutenberg/pull/40413)
- [ ] Add icons for different types of suggestions in LinkControl [43970](https://github.com/WordPress/gutenberg/pull/43970)

## Updating for 6.0
- [ ] Enable Previews for Navigation Link Blocks. [36412](https://github.com/WordPress/gutenberg/pull/36412)
- [ ] Refactor and simplify setup state. [36375](https://github.com/WordPress/gutenberg/pull/36375)
- [ ] Only show submenu options and Show arrow button when relevant. [36826](https://github.com/WordPress/gutenberg/pull/36826)
- [ ] Try always generating navigation post title. [36760](https://github.com/WordPress/gutenberg/pull/36760)
- [ ] Use first non-empty Nav post as primary fallback for Nav block. [36740](https://github.com/WordPress/gutenberg/pull/36740)
- [ ] Implement suitable fallback for Nav block on front end of site when no menu selected. [36724](https://github.com/WordPress/gutenberg/pull/36724)
- [ ] Add/navigation blocks post processing after migration from menu items. [36950](https://github.com/WordPress/gutenberg/pull/36950)
- [ ] Enable even more compact setup state. [37089](https://github.com/WordPress/gutenberg/pull/37089)
- [ ] Add clearance for appender in submenus. [36720](https://github.com/WordPress/gutenberg/pull/36720)
- [ ] Allow using a text label instead of an icon on overlay menu toggle button. [36149](https://github.com/WordPress/gutenberg/pull/36149)
- [ ] Block gap support. [37543](https://github.com/WordPress/gutenberg/pull/37543)
- [ ] Show menus selection in placeholder only if available. [37980](https://github.com/WordPress/gutenberg/pull/37980)
- [ ] Try removing "Add all pages" from placeholder. [36775](https://github.com/WordPress/gutenberg/pull/36775)
- [ ] Try unifying submenu arrow positioning. [37003](https://github.com/WordPress/gutenberg/pull/37003)
- [ ] Submenu: Add revert button. [38203](https://github.com/WordPress/gutenberg/pull/38203)
- [ ] Improve loading and placeholder states. [38907](https://github.com/WordPress/gutenberg/pull/38907)
- [ ] Improve create new UI feedback in Nav block. [39219](https://github.com/WordPress/gutenberg/pull/39219)
- [ ] Improve feedback on Nav Menu deletion. [39677](https://github.com/WordPress/gutenberg/pull/39677)
- [ ] Enable navigation nesting to be filtered and manually set.  [38621](https://github.com/WordPress/gutenberg/pull/38621)

### Updating for 5.9
- [ ] Refer to the [tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues/221)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Pls make 6.2 updates first and then move to 6.1.
3. Some of the PRs have great videos that can be added to the article
4. For 6.1, you can pick the screenshots added in the comments previously, if they are relevant.

**Comment by lnaima** [comment]
I'll work on that

**Comment by lnaima** [comment]
Transform menu has a new option: "Home link"
![Navigation_block_Transform](https://user-images.githubusercontent.com/6752710/190151402-1157c553-e0b2-47eb-96dc-0bf4a912d067.png)

**Comment by lnaima** [comment]
Toolbar options have a new button
![Navigation_block_Toolbar](https://user-images.githubusercontent.com/6752710/190151821-aae1cf1d-816c-4bdd-ac2b-7ae0724d3cb6.png)

**Comment by lnaima** [comment]
In layout "All to wrap to multiple lines" is "**Allow** to wrap to multiple lines"

**Comment by mrfoxtalbot** [comment]
While opening https://github.com/WordPress/gutenberg/issues/44615 I noticed that the "Convert to links" workflow is does not to be listed in the Updating for 6.1 list above. 

I am still not 100% familiar with how we track these. Should we add it to the "to do" list to ensure we update that part of the article @femkreations? 

Thank you!

**Comment by femkreations** [comment]
Added 6.1 tasks

## Notes
1. We are not adding detailed updates for the Block settings as we are revamping the block settings for all the block articles 
2. Pls make 6.1 updates first and then move into 6.0.
3. Some of the PRs for 6.1 have great videos that can be added to the article (even for the Block settings section)
4. For 6.0, you can pick the screenshots added in the comments previously.

**Comment by mrfoxtalbot** [comment]
@femkreations, has anyone been assigned to work on this yet? @lnaima, would you like to work on this? If not, maybe I can work on it.

The Navigation Block is going to see a lot of changes in version 6.1 and it is an inherently complex block. I would like to make sure the docs are as detailed and as up-to-date as possible.

Thank you!

**Comment by lnaima** [comment]
Update for 6.1
The block behaviour is changed, here the screenshots fof block configuration:
![Nav_insert](https://user-images.githubusercontent.com/6752710/201328031-601c27ab-f8e9-4612-a2b8-787b3691b857.png)
![Nav_options](https://user-images.githubusercontent.com/6752710/201328054-0f51a846-ecd3-497b-bcae-087a3562de35.png)
![Nav_add](https://user-images.githubusercontent.com/6752710/201328087-0cb33a97-ede8-46f3-a435-5fcab06db93b.png)
![Nav_add-page](https://user-images.githubusercontent.com/6752710/201328096-066205fd-f4ab-4da5-8d97-8c86077c0786.png)

**Comment by lnaima** [comment]
"Add all pages" function seems to be gone

**Comment by lnaima** [comment]
In "Add additional menu items" now page link, post link, category and tag are all included into "custom link".
"Page list" and "Site title" seem to be gone.
![Nav_insert_other_blocks](https://user-images.githubusercontent.com/6752710/201331007-e274114c-0e19-4636-8d71-f7528ad84ade.png)

**Comment by lnaima** [comment]
In "Move blocks", "List view" seems to be gone.

**Comment by lnaima** [comment]
Transform to has changed a little
![Nav_trasform_to](https://user-images.githubusercontent.com/6752710/201331913-36276f04-ca79-438d-bd28-fd2f02449ec7.png)

**Comment by lnaima** [comment]
"Manage menus" is now in the right toolbar
![Nav_manage_menus](https://user-images.githubusercontent.com/6752710/201332305-a86ee35c-cb3f-4731-8f3e-92b23ac2a855.png)

**Comment by lnaima** [comment]
Block toolbar options
![Nav_toolbar](https://user-images.githubusercontent.com/6752710/201332546-6f69a2e9-476c-4582-b46d-91593d2023ab.png)

**Comment by lnaima** [comment]
In Toolbar options "Select menu" and "list view" are gone

**Comment by lnaima** [comment]
In block settings --> Layout now we have also "Orientation" and "Allow to wrap to multiple lines"
![Nav_settings_layout](https://user-images.githubusercontent.com/6752710/201333046-c877943d-32d4-436c-82bc-a4e0271bcb4f.png)

**Comment by lnaima** [comment]
In "Advanced settings", "HTML anchor" is gone
![Nav_settings_advanced](https://user-images.githubusercontent.com/6752710/201333562-bf212ed6-cc24-4c82-badb-d0f509fb7c92.png)

**Comment by lnaima** [comment]
A little video for "addictional menu items" to make clear how to add a tag or a category
[Nav_add_tag_category.webm](https://user-images.githubusercontent.com/6752710/201335538-5745e6cd-8d72-4aa4-94ac-0a36c14a0089.webm)

**Comment by mrfoxtalbot** [comment]
Thank you for reviewing all of the above, @lnaima. 
The Navigation Block has indeed experimented quite a few changes in 6.1!

I have put together a bunch of screenshots and I am ready to update the article but, since the issue was assigned to you, I wanted to check with you for to ensure you are not already editing it.

Is it ok if I go ahead and start making changes to the current article myself?

Thank you!

**Comment by femkreations** [comment]
Hi @mrfoxtalbot I am assigning this page to you. When you get a chance pls make the updates and I can review it. Thanks!

**Comment by femkreations** [comment]
@Leonardus-Nugraha I have updated the task list with PRs for OffCanvas editing features under a separate subheading.

**Comment by femkreations** [comment]
@Leonardus-Nugraha Pls [review this slack message](https://app.slack.com/client/T024MFP4J/C04JZ199XPG/thread/C04JZ199XPG-1678728808.778249) from Anne.

These has been a change and the Off Canvas  navigation in the Site Editor is NOT included in 6.2. The one in the Block settings IS INCLUDED in 6.2

**Comment by Leonardus-Nugraha** [comment]
Thanks for the notice @femkreations!

**Comment by mrfoxtalbot** [comment]
I am building on @Leonardus-Nugraha's [work](https://docs.google.com/document/d/1wOYCqj7CkJfsknax68U5oxVChKiAvY6EEFvRNUxmFRM/edit#) (thank you!) and editing the article myself right now.

**Comment by mrfoxtalbot** [comment]
This article is ready! 🚀

**Comment by Leonardus-Nugraha** [comment]
Thanks @mrfoxtalbot !
