### ISSUE TITLE
[HelpHub] Block-based Widgets Editor

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#299]
Article: https://wordpress.org/support/article/block-based-widgets-editor/

## Updating for 6.0
- [ ] Add preview pane to widget editor. [37012](https://github.com/WordPress/gutenberg/pull/37012)
- [ ] Add a note that this feature is available from 5.8 onwards and with a classic theme that has widgets.

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos are up to date
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

**Comment by samxmunoz** [comment]
@femkreations / @zzap / @colorful-tones - I don't see the option to access the Widget Editor - is the widget editor deprecated?

<img width="382" alt="Screen Shot 2022-09-28 at 3 02 39 PM" src="https://user-images.githubusercontent.com/43501707/192867004-7f3ebc2c-8f97-4b76-b814-91caf9e3b4bc.png">

**Comment by colorful-tones** [comment]
I have not followed the Widget transition closely and I'm likely out of the loop here to help. I feel like it is likely theme-dependent. Maybe try activating an older Twenty Twenty-something theme, e.g. Twenty Twenty-One.

This might also help shed some like (and was originally linked at the bottom of the existing doc resource): https://make.wordpress.org/core/2021/06/29/block-based-widgets-editor-in-wordpress-5-8/

**Comment by samxmunoz** [comment]
This screenshot is from a new InstaWP spin up of TT2 so I'm not sure - you're right maybe I'll activate TT1 in which case though - is this something we _want_ in these "later" docs.

**Comment by femkreations** [comment]
@colorful-tones @samxmunoz The block-based widget editor was introduced in 5.8 for folks who use the classic themes with widgets. With 5.8 WP install and a theme like 2020 you can see the block based widget editor.  This needs to be noted in the article. I am adding a note to the list of tasks.

**Comment by samxmunoz** [comment]
Perfect, thank you for adding that @femkreations!

**Comment by Yvonne-Palanca** [comment]
I'll pick this one up!

**Comment by Yvonne-Palanca** [comment]
I don't have the option to modify the article https://wordpress.org/support/article/block-based-widgets-editor/. So I shared a Google doc for the testing  I made using the WordPress 6.0 and Twenty twenty-one theme. 

https://docs.google.com/document/d/1ctWJd4kq_EeDCoMrNLnL4I4tQJf-0HLYhFp-ZuAbQfE/edit?usp=sharing

**Comment by femkreations** [comment]
Thank you @Yvonne-Palanca. I made a few tweaks to the article:
Added ALT tags for the images
Added internal links to other support articles.
Updated videos.
Also added a note on how you can find the widget editor in classic themes.

Thanks
