### ISSUE TITLE
[HelpHub] Reusable blocks

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#300]
Article:  https://wordpress.org/documentation/article/reusable-blocks/

## Updating for 6.3
- [x] Rename to 'Patterns' and add option to also add a non-synced Pattern. [51144](https://github.com/WordPress/gutenberg/pull/51144)

## Updating for 6.2
- [x] Colorize template parts and Reusable blocks. [45473](https://github.com/WordPress/gutenberg/pull/45473)
- [x] Move document information and outline to list view panel [44788](https://github.com/WordPress/gutenberg/pull/44788)
- [x] Don't show empty reusable tab if not allowed to insert reusable blocks  [46922](https://github.com/WordPress/gutenberg/pull/46922)
- [x] Replace text in Reusable tab with an icon [45851](https://github.com/WordPress/gutenberg/pull/45851)
- [x] Make Manage Reusable blocks match similar links [45689](https://github.com/WordPress/gutenberg/pull/45689)
- [x] Make Manage Reusable blocks match similar links [45641](https://github.com/WordPress/gutenberg/pull/45641)

## Updating for 6.1
- [x] Make template part and reusable block creation language consistent. [43032](https://github.com/WordPress/gutenberg/pull/43032)

## Updating for 6.0
- [x] Hide 'Convert to Blocks' when locked. [39939](https://github.com/WordPress/gutenberg/pull/39939)
- [x] Make the Cancel button tertiary.  [39872](https://github.com/WordPress/gutenberg/pull/39872)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. Please make the changes reflecting the update from Reusable blocks to Patterns
3. Some of the PRs have great videos that can be added to the article

**Comment by jaz-on** [comment]
@zzap I'll have a look at this one.

**Comment by jaz-on** [comment]
Ping @zzap 

**Quick notes:**
- https://wordpress.org/support/article/reusable-blocks/#edit-reusable-block : need review, not sure this is still working on the same way on 6.0 rc2
- https://wordpress.org/support/article/reusable-blocks/#remove-a-reusable-block : I didn't manage to reproduce this on 6.0 rc2

I generate new gifs for the article and saved it for being published on May 31th:
https://wordpress.org/support/wp-admin/post.php?post=13363440&action=edit

I am not sure what the 2 updates for 6.0 means. Is it new features that need to be added to the documentation or action to remove from actual screenshots?


> Article: https://wordpress.org/support/article/reusable-blocks/
> 
> ## Updating for 6.0
> * [ ]  Hide 'Convert to Blocks' when locked. [39939](https://github.com/WordPress/gutenberg/pull/39939)
> * [ ]  Make the Cancel button tertiary.  [39872](https://github.com/WordPress/gutenberg/pull/39872)
> 
> ## General
> * [x]  Make sure all screenshots are relevant for the current version (6.0)
> * [x]  Make sure videos are up to date
> * [x]  Make sure the headings are in sentence case
> * [x]  Update the changelog at the end of the article

**Comment by jaz-on** [comment]
Here are the gifs I used, I revert the changes I prepared on the documentation:

![convert a reusable block to regular block 20220513](https://user-images.githubusercontent.com/56646501/168280141-23fcae6e-29fe-42d2-96b4-0c9dd4700fbd.gif)
![Create a Reusable Block 20220513](https://user-images.githubusercontent.com/56646501/168280148-67584460-ed2c-41e8-bb5d-66f6c58923dc.gif)
![Demonstration of the Reusable Block 20220513](https://user-images.githubusercontent.com/56646501/168280150-2b73c762-c94b-4551-95fe-35c9e118079a.gif)
![how to delete a reusable block 20220513](https://user-images.githubusercontent.com/56646501/168280162-13e9e7d8-8718-4090-b372-74acf993edad.gif)
![how to pick a reusable block 20220513](https://user-images.githubusercontent.com/56646501/168280163-cc4fdd84-fdd0-4ee0-bd25-2fd77792cde7.gif)

**Comment by jaz-on** [comment]
FYI it's easy to replace the videos, just look at the files names. :)

**Comment by femkreations** [comment]
Thanks @jaz-on for adding in the content for this page.

**Comment by femkreations** [comment]
Adding tasks for 6.1

1. We are not adding updates for the Block settings as we are revamping the block settings for all the block articles. 
2. Pls make 6.1 updates first and then move into 6.0.
3. Some of the PRs for 6.1 have great videos that can be added to the article (even for the Block settings section)
4. For 6.0, you can pick the screenshots/videos added in the comments.

**Comment by mumtahinafaguni** [comment]
I want to contribute to write this doc 👋  @femkreations

**Comment by shabnam611** [comment]
I would like to work on this one.

**Comment by shabnam611** [comment]
[Reusable blocks for 6.1](https://docs.google.com/document/d/1IcVv2CbSSLFeonUjkOB23XGAc1V4EhDMNbgP7lmewq0/edit?usp=sharing)




I updated the screenshots to WordPress 6.1 for the issue

**Comment by shabnam611** [comment]
For the template part, shall I work here: https://github.com/WordPress/Documentation-Issue-Tracker/issues/291

**Comment by shabnam611** [comment]
Hi @femkreations 

It seems Alvaro Gómez already worked on this and added the 6.3 changes. Do I still need to update this one?
