### ISSUE TITLE
[HelpHub] More options

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#301]
Article:  https://wordpress.org/support/article/more-options/

## Updating for 6.1
- [x] Block Locking: Add the 'Apply to inner blocks' option. [41876](https://github.com/WordPress/gutenberg/pull/41876)
- [x]  Improve content locking experience. [43956](https://github.com/WordPress/gutenberg/pull/43956)
- [x] Make it easier to select "Edit visually" when in "Edit as HTML [41516](https://github.com/WordPress/gutenberg/pull/41516)

## Updating for 6.0
- [x] Reusable Blocks: Hide 'Convert to Blocks' when locked. [39939](https://github.com/WordPress/gutenberg/pull/39939)
- [x] Introduce block locking UI. [39183](https://github.com/WordPress/gutenberg/pull/39183)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by suascat** [comment]
Updating screenshots ...

**Comment by suascat** [comment]
More options:

![more-options](https://user-images.githubusercontent.com/9716719/168279594-5f64add2-8da1-4794-a1e3-4ff81c505d2a.png)

You will notice new menu item "Lock". (Lock Paragraph).
**Lock** menu item description is missing as per the new screenshot in the documentation.

Clicking this menu time will have this new pop-up:

Lock paragraph:

![lock-paragraph](https://user-images.githubusercontent.com/9716719/168280734-2caab2a2-a59b-4dbf-bc3d-1a546a5a465e.png)

**Comment by zzap** [comment]
Thank you :heart:

**Comment by femkreations** [comment]
Added tasks for 6.1

**Comment by femkreations** [comment]
Linking this one to  #526 which is worked on currently.

**Comment by femkreations** [comment]
Closing this as this has been completed in #526
