### ISSUE TITLE
[HelpHub] WordPress Editor

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#302]
Article:   https://wordpress.org/support/article/wordpress-editor/

## Updating for 6.1
- [x] Add estimated time to read to table of contents in editor [41611](https://github.com/WordPress/gutenberg/pull/41611)
- [x] Partial multi selection: limit if selection contains unmergeable block. [42934](https://github.com/WordPress/gutenberg/pull/42934)
- [x] Reduce active tab accent weight. [40998](https://github.com/WordPress/gutenberg/pull/40998)
- [ ] Add setting to display rich text toolbar inline [42399](https://github.com/WordPress/gutenberg/pull/42399)
- [ ] Writing flow: Esc should enter Nav mode consistently, avoid focus loss when clearing selection [42530](https://github.com/WordPress/gutenberg/pull/42530)
- [x] Rich text: add character shortcuts for wrapping selection [42469](https://github.com/WordPress/gutenberg/pull/42469)
- [x] Try to fix multi-selection with shift+click [40687](https://github.com/WordPress/gutenberg/pull/40687)

## Updating for 6.0
- [ ] Post Lock Modal: Update avatar size. [38040](https://github.com/WordPress/gutenberg/pull/38040)
- [ ] Post Lock: Adjust avatar design and update message. [37979](https://github.com/WordPress/gutenberg/pull/37979)
- [x] Enable tooltip for the main dashboard button. [38790](https://github.com/WordPress/gutenberg/pull/38790)
- [x] Multi-selection: Allow partial block selection. [38892](https://github.com/WordPress/gutenberg/pull/38892)
- [ ] Make appender fixed position to avoid jumps in the UI [36605](https://github.com/WordPress/gutenberg/pull/36605)
- [ ] Always show the block appender when its parent is selected [36656](https://github.com/WordPress/gutenberg/pull/36656)
- [x] Adjust order of theme blocks and reorder inserter items. [36719](https://github.com/WordPress/gutenberg/pull/36719)
- [x] Introduce block locking UI. [39183](https://github.com/WordPress/gutenberg/pull/39183)
- [ ] Add settings to enable/disable auto anchor generation. [38780](https://github.com/WordPress/gutenberg/pull/38780)
- [x] Block Transforms: Keep additional HTML classes during a block transform. [38964](https://github.com/WordPress/gutenberg/pull/38964)
- [ ] Add a link completer for inline links to posts. [29172](https://github.com/WordPress/gutenberg/pull/29172)
- [x] Quick Inserter: Prioritize showing patterns instead of blocks. [38709](https://github.com/WordPress/gutenberg/pull/38709)

**Explain the following features using video/screenshots:**
- [x] Select text across multiple blocks and edit it all at once.
- [x] Type two open brackets `[[` to quickly access the link menu.
- [x] Keep existing styles when you transform some blocks from one kind to another—from a Paragraph block to a Code block, for instance.

### Updating for 5.9
- [x] Refer to the [tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues/126)

## Updating for 5.7
- [x] #395

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos are up to date
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

**Comment by femkreations** [comment]
@zzap @bph I've updated [WordPress Block Editor](https://wordpress.org/support/article/wordpress-editor/) page. It is scheduled for publishing on May 23rd. Pls review and let me know.
I have moved the block related information to a new page https://wordpress.org/support/article/working-with-blocks/ and added in a lot of the tracker items on this page (all related to the blocks)

**Comment by abhansnuk** [comment]
@femkreations I added some items pre-release and just reviewing it from checking it against Learn WP and live runthroughs at WCEU/ contributor day. I have updated the reference to 2018 and updating some of the alt tags to give information about what the image shows for those who can not see it. Added alt tag to the featured image where it is used.

A couple of other changes to make it easier for users whose first language is not English or may wish to translate the document.

Changed the wording of link word 'here' for accessibility. 

Under view modes, is it worth adding screenshots for visual and code editor?

**Fullscreen mode**
'Fullscreen' - changed everything to 'Fullscreen' to match how it looks in the editor. We don't have a definition in the core glossary at the moment, so will check for adding it there too so we can use the same throughout. Learn WP uses 'full screen' so will check how it can be altered there for consistency.

'choise' changed to 'choice'

"Until the core developers find the best solution, you can use the [Persistent block editor settings plugin]" - presume this relates to a fix for Safari in the paragraph above. Think the wording needs revising in this instance.

Added excerpt. 


Femy is there anything else you need on this document? Thanks

**Comment by abhansnuk** [comment]
Under FAQs,
Q. Does the Block editor allow editing posts and pages in the front end of the site?
No. It’s a representation of what site visitors see on the front end of your site. However, the layout and visual experience in the editor are much closer to the way things look on the public-facing side of your site.

Can I suggest we rework this answer for clarity? Thanks Femy.

**Comment by femkreations** [comment]
## Notes
1. We are not adding updates for the Block settings as we are revamping the block settings for all the block articles 
2. Pls make 6.1 updates first and then move into 6.0.
3. Some of the PRs for 6.1 have great videos that can be added to the article (even for the Block settings section)
4. For 6.0, you can pick the screenshots added in the comments previously.

**Comment by femkreations** [comment]
Here is the page scheduled for Nov 1st. https://wordpress.org/support/wp-admin/post.php?post=16133030&action=edit

Updated screenshots to show the View button in the top toolbar, time to read

Content tweaked. FAQ removed. Added a section with videos on how to use the block editor. 

Added new videos to show tips to work with the Editor
