### ISSUE TITLE
[HelpHub] Page/Post Sidebar settings

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#303]
Article:  https://wordpress.org/support/article/settings-sidebar/

## Updating for 6.0
- [ ] Most Used Terms: Update show terms condition. [38513](https://github.com/WordPress/gutenberg/pull/38513)

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Make sure videos are up to date
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

**Comment by suascat** [comment]
I'm working on screenshots.

**Comment by suascat** [comment]
I found just 1 screenshot that needs to be updated.

![preferences](https://user-images.githubusercontent.com/9716719/168276841-8f6ad1a5-1954-443d-85d4-25858db68ec2.png)

**Comment by abigail0r** [comment]
All the headings are in sentence case 👍

**Comment by jenmearns** [comment]
No videos in existing article.

**Comment by femkreations** [comment]
Added tasks for 6.1

**Comment by femkreations** [comment]
Updated the page https://wordpress.org/support/wp-admin/post.php?post=16141282&action=edit
