### ISSUE TITLE
[HelpHub] List View

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#304]
Article:  https://wordpress.org/documentation/article/list-view/

## Updating for 6.2
- [ ] Update template part children background color [46708](https://github.com/WordPress/gutenberg/pull/46708)
- [ ] Update template part hover style in list view. [46707](https://github.com/WordPress/gutenberg/pull/46707)
- [ ] Disable branch expansion when block editing is locked [45541](https://github.com/WordPress/gutenberg/pull/45541)
- [ ] Colorize template parts and Reusable blocks [45473](https://github.com/WordPress/gutenberg/pull/45473)
- [ ] Move document information and outline to list view panel [44788](https://github.com/WordPress/gutenberg/pull/44788)
- [ ] Move wordcount to the top of the outline [46648](https://github.com/WordPress/gutenberg/pull/46648)

## Updating for 6.1
- [ ] useBlockDisplayInformation: Return anchor for block variations. [40458](https://github.com/WordPress/gutenberg/pull/40458)
- [ ] Fix list view drop indicator positioning. [42353](https://github.com/WordPress/gutenberg/pull/42353)
- [ ] Use heading content for button label text if available. [41855](https://github.com/WordPress/gutenberg/pull/41855)
- [ ] Add option in editor settings to show open list view as default. [40757](https://github.com/WordPress/gutenberg/pull/40757)
- [ ] Return anchor for block variations . [40458](https://github.com/WordPress/gutenberg/pull/40458)
- [ ] Show parent block as selected when there is content locking [43918](https://github.com/WordPress/gutenberg/pull/43918)

## Updating for 6.0
- [ ] Use anchor elements instead of buttons. [35655](https://github.com/WordPress/gutenberg/pull/35655)
- [ ] Add multi-select behaviour for blocks when shift key is selected. [38314](https://github.com/WordPress/gutenberg/pull/38314)
- [ ] Add multi-select support for shift + Home and End keys. [39272](https://github.com/WordPress/gutenberg/pull/39272)
- [ ] Display lock status. [40088](https://github.com/WordPress/gutenberg/pull/40088)

**Explain the following features using video/screenshots:**
New keyboard shortcuts enable you to select multiple blocks from the list view, modify them in bulk, and drag and drop them within the list. List View can be opened and closed easily; it comes collapsed by default and it automatically expands to the current selection whenever you select a block. Refer to [video at 9.15](https://www.youtube.com/watch?v=abaaVKl-beM
)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Notes
1. Pls make 6.2 updates first and then move to 6.1.
2. Some of the PRs have great videos that can be added to the article
3. For 6.1, you can pick the screenshots added in the comments previously, if they are relevant.

**Comment by abigail0r** [comment]
All the headings are in sentence case 👍

**Comment by femkreations** [comment]
Added tasks for 6.1

## Notes
1. Pls make 6.1 updates first and then move into 6.0.
2. Some of the PRs for 6.1 have great videos that can be added to the article (even for the Block settings section)

**Comment by mrfoxtalbot** [comment]
Hi @femkreations, I am seeing that this support article has not gotten much attention lately. If you want to assign it to me, I would love to revamp it for the 6.1 release.

**Comment by femkreations** [comment]
Thanks @mrfoxtalbot Its all yours!

**Comment by annezazu** [comment]
@mrfoxtalbot did you revamp this? We're hitting the 6.2 release and I'm going to take this on tomorrow if not :)

**Comment by mrfoxtalbot** [comment]
I just added a couple of screencasts to better illustrate multiple block selection and moving blocks around. This support is up to date, @annezazu, thank you for checking.

@femkreations, could you please mark this as solved? Thank you!

**Comment by annezazu** [comment]
Marking this as done based on the [comment here](https://wordpress.slack.com/archives/C02RP4WU5/p1679930666509889?thread_ts=1679769144.495649&cid=C02RP4WU5) from @bph

**Comment by mrfoxtalbot** [comment]
> updates are scheduled to align with the release as the changes in the doc now aren't reflected in 6.1 and need to be reviewed

Ouch, I have done this in the past but I forgot this time, @annezazu. It looks like the "schedule update" is missing for some reason. I saw @bph's [comment](https://wordpress.slack.com/archives/C02RP4WU5/p1679930666509889?thread_ts=1679769144.495649&cid=C02RP4WU5), I will open a Meta Trac issue in the next few days to investigate this.

Thank you for reviewing this and for marking it one as done!
