### ISSUE TITLE
[HelpHub] Site Editor

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#305]
Article:  https://wordpress.org/support/article/site-editor/

## Updating for 6.1
- [x] Update clear customizations copy for templates [41765](https://github.com/WordPress/gutenberg/pull/41765)
- [x] Add clear customizations to template card [41743](https://github.com/WordPress/gutenberg/pull/41743)
- [x]  Use the label 'Clear customizations' when changes are revertable [40935](https://github.com/WordPress/gutenberg/pull/40935 )
- [x] Update template details browse label [42350](https://github.com/WordPress/gutenberg/pull/42350)
- [x] Add a 'View Site' link in the site editor [42331](https://github.com/WordPress/gutenberg/pull/42331)
- [x] Allow clearing template name field while typing [42149](https://github.com/WordPress/gutenberg/pull/42149)
- [x] Only allow renaming user-created and non-default templates [40881](https://github.com/WordPress/gutenberg/pull/40881)
- [ ] Use default cursor for non-editable text blocks [40785](https://github.com/WordPress/gutenberg/pull/40785)

## Updating for 6.0
- [x] Add welcome guide. [36172](https://github.com/WordPress/gutenberg/pull/36172)
- [x] Update back button URL. [36313](https://github.com/WordPress/gutenberg/pull/36313)
- [x] Change edit links for templates and template parts. [36294](https://github.com/WordPress/gutenberg/pull/36294)
- [x] Update site editor title truncation. [36436](https://github.com/WordPress/gutenberg/pull/36436)
- [x] Make Reusable blocks available in the Site Editor. [36511](https://github.com/WordPress/gutenberg/pull/36511)
- [x] Remove the Styles link in Site Editor. [36637](https://github.com/WordPress/gutenberg/pull/36637)
- [x] Add icons to navigation sidebar items. [36893](https://github.com/WordPress/gutenberg/pull/36893)
- [x] Allow editing custom template title. [36933](https://github.com/WordPress/gutenberg/pull/36933)
- [x] Remove extra border radius from the canvas. [37022](https://github.com/WordPress/gutenberg/pull/37022)
- [x] Update navigation sidebar responsiveness. [36638](https://github.com/WordPress/gutenberg/pull/36638)
- [x] Update resize handle styling in template part focus mode. [36410](https://github.com/WordPress/gutenberg/pull/36410)
- [x] Theme export: Add theme.json to export file. [39048](https://github.com/WordPress/gutenberg/pull/39048)
- [x] Theme Export: Add index.php and style.css. [39173](https://github.com/WordPress/gutenberg/pull/39173)
- [x] Add: Copy all content to edit site. [37781](https://github.com/WordPress/gutenberg/pull/37781)
- [x] Add keyboard shortcut help modal. [37650](https://github.com/WordPress/gutenberg/pull/37650)
- [ ] Add client-side routing for Site Editor. [36488](https://github.com/WordPress/gutenberg/pull/36488)
- [x] Add: Code editor to edit site. [37765](https://github.com/WordPress/gutenberg/pull/37765)
- [x] Quick Inserter: Prioritize showing patterns instead of blocks. [38709](https://github.com/WordPress/gutenberg/pull/38709)
- [x] Remove Navigation Menus from the Appearance menu. [37212](https://github.com/WordPress/gutenberg/pull/37212)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos are up to date
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

**Comment by femkreations** [comment]
@zzap @bph I've updated [Site Editor](https://wordpress.org/support/wp-admin/post.php?post=15654988&action=edit) page. It is scheduled for publishing on May 23rd. Pls review and let me know.
-Screenshots/videos updated.
-Rewritten and added new content

**Comment by femkreations** [comment]
Here is the updated Site Editor with 6.1 changes. I have updated the videos and screenshots for 6.1. Some of the repetitive content for Templates and Template Editor has been removed and moved into those pages. 
Also some of the unchecked tasks here are to be included in Template Editor pages instead.

https://wordpress.org/support/wp-admin/post.php?post=16107857&action=edit

**Comment by femkreations** [comment]
Closing this issue. Here is the completed page https://wordpress.org/support/article/site-editor/
