### ISSUE TITLE
[HelpHub] Template Editor

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#306]
Article:  https://wordpress.org/support/article/template-editor/

## Updating for 6.0
- [ ] Update template home, front-page, and search template descriptions. [38132](https://github.com/WordPress/gutenberg/pull/38132)
- [ ] Change edit links for templates and template parts. [36294](https://github.com/WordPress/gutenberg/pull/36294)
- [ ] Update and align template descriptions.([36000](https://github.com/WordPress/gutenberg/pull/36000)
- [ ] Add icons to navigation sidebar items. [36893](https://github.com/WordPress/gutenberg/pull/36893)
- [ ] Template revert flow: Make label description source agnostic. [37004](https://github.com/WordPress/gutenberg/pull/37004)
- [ ] Add client-side routing for Site Editor. [36488](https://github.com/WordPress/gutenberg/pull/36488)
- [ ] Update copy on Snackbar that appears when a template is deleted. [37888](https://github.com/WordPress/gutenberg/pull/37888)
- [ ] Show theme, plugin, or author in Added By column with appropriate icon or avatar. [36763](https://github.com/WordPress/gutenberg/pull/36763)
- [ ] Add Template List View. [36379](https://github.com/WordPress/gutenberg/pull/36379)
- [ ] Add success and error snackbars. [36808](https://github.com/WordPress/gutenberg/pull/36808)
- [ ] Implement "Add New". [36592](https://github.com/WordPress/gutenberg/pull/36592)
- [ ] Use table layout. [36707](https://github.com/WordPress/gutenberg/pull/36707)
- [ ] Set the document title properly. [36805](https://github.com/WordPress/gutenberg/pull/36805)
- [ ] Add rename action. [36879](https://github.com/WordPress/gutenberg/pull/36879)
- [ ] Update delete template button. [36815](https://github.com/WordPress/gutenberg/pull/36815)

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Make sure videos are up to date
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

**Comment by femkreations** [comment]
@zzap @bph I've updated [Template Editor](https://wordpress.org/support/wp-admin/post.php?post=15668277&action=edit ) page. It is scheduled for publishing on May 24th. Pls review and let me know.
-Screenshots/videos updated.
-Rewritten and added new content

**Comment by bph** [comment]
@femkreations are you ready to close this issue?

**Comment by femkreations** [comment]
@bph yes!
