### ISSUE TITLE
[HelpHub] Keyboard shortcuts in Block Editor

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#307]
Article:  https://wordpress.org/support/article/block-editor-keyboard-shortcuts/

## Updating for 6.0
- [ ] Double escape unselects all blocks. [36945](https://github.com/WordPress/gutenberg/pull/36945)
- [ ] Add keyboard shortcut help modal. [37650](https://github.com/WordPress/gutenberg/pull/37650)

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Make sure videos are up to date
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

**Comment by abigail0r** [comment]
I'm working on this

**Comment by hannaw93** [comment]
I will pick up this issue :)

**Comment by hannaw93** [comment]
Done/added: 
Double escape unselects all blocks. 
Add keyboard shortcut help modal.

**Comment by femkreations** [comment]
Adding tasks for 6.1

**Comment by cgarofalo** [comment]
@femkreations I'd like to take this issue and update the screenshots and videos for this article. 🙏

**Comment by jennimckinnon** [comment]
@cgarofalo Assigned you as Femy is currently on leave and back in July. If you have any questions, feel free to ask in the docs channel on Slack or in a comment here. Happy contributing! 🎉

**Comment by cgarofalo** [comment]
Here are the new screenshots. There are no videos on this documentation page.

Visual Editor Screen

![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/d45039d2-af2f-40a7-9289-66b4046dda36)

Code Editor Screen

![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/e420a5d8-577d-4c85-afe4-89cfb96e748c)

Block List View

![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/8c397474-a244-4f4b-a8fa-406823dba74d)

Settings Sidebar

![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/ad1b0c2d-878e-4b4d-a31e-67a17e0f573f)

Navigate to the next part of the editor

![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/a4ef2d15-965f-4d02-96b9-5dfb2a1ef5a7)
![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/6a846bda-ad59-4790-b8a1-606fa1fc568b)

Nearest Toolbar

![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/44d93d7d-7fc4-4f5a-b894-7ba81c3a9178)

Saved

![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/1844b6a1-db90-462c-a72f-82b9c59c12f7)

Undo

![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/6da7cebc-e92e-49fd-8178-ce7a0059ea98)
![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/dc5b7c0e-03e3-440c-bda9-c0cab3e69560)

Select all

![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/fa72e42b-b961-477f-b465-386d8aca1684)
![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/d0cf71f8-9fb2-4907-8d96-cbcecd758149)

Duplicate block

![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/9b7cbeb7-86f8-4ac5-8369-3219489d4ea4)

Insert block

![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/5d726ccd-b7c9-4abc-8bc1-c97f99f59c07)
![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/f8221e2a-a2e4-48dc-9739-6486847f90f8)

Remove blocks

![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/e599f2a6-10d1-4c52-b7fd-27880a8df463)
![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/25d785e2-b532-4fc6-a33a-bef004731660)

Move up

![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/f10a654c-a1f2-47a3-b271-07ae3eefad9d)
![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/fe12e3e6-cc29-43c7-bd2c-17cfa0133f6a)

Change Block type

![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/d98aac38-2f8f-4fc5-821f-7999df5a0687)
![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/0bec6a0a-2704-4a3a-a636-199dd6853292)

Format link

![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/2f74ec92-6dda-439f-927a-0e8ffe2792ae)
![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/65b3912e-8e19-410c-829d-adf971186ff6)

**Comment by zzap** [comment]
Is this ready for review @cgarofalo ?

**Comment by jennimckinnon** [comment]
@zzap Now that @cgarofalo added the screenshots, this issue is ready to be worked on.

**Comment by cgarofalo** [comment]
@zzap Yup, ready for review.
