### ISSUE TITLE
[HelpHub] Adding a new block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#308]
Article:  https://wordpress.org/support/article/adding-a-new-block/

## Updating for 6.0
- [ ] Adjust order of theme blocks and reorder inserter items. [36719](https://github.com/WordPress/gutenberg/pull/36719)
- [ ] Accessibility improvements for Block Inserter. [37357](https://github.com/WordPress/gutenberg/pull/37357)
- [ ] Prioritize core blocks over core block variations when they have the same rank. [38616](https://github.com/WordPress/gutenberg/pull/38616)
- [ ] Quick Inserter: Prioritize showing patterns instead of blocks. [38709](https://github.com/WordPress/gutenberg/pull/38709)

### Updating for 5.9
- [ ] Refer to the [tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues/121)

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Make sure videos are up to date
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

**Comment by pls78** [comment]
I'm starting working on this!

**Comment by jaz-on** [comment]
Here are the new screenshots:

![full admin screen 20220513](https://user-images.githubusercontent.com/56646501/168280604-d1d4ce78-74ab-4bbf-bfbc-30289e274d2d.png)
![full screen the inserter 20220513](https://user-images.githubusercontent.com/56646501/168280606-8b322f40-b469-45b0-8ca1-b159437b4b40.png)
![insert before:after actual block 20220513](https://user-images.githubusercontent.com/56646501/168280608-68e7a4db-c4fc-40ff-a76d-cd19ab39674c.png)
![inserter icon 20220513](https://user-images.githubusercontent.com/56646501/168280614-889bbe9a-6640-4962-a81e-04b0d3d5f293.png)
![move up:down the actual block 20220513](https://user-images.githubusercontent.com/56646501/168280616-9516101f-87f8-48c7-afc4-22b304724689.png)
![search block from the inserter 20220513](https://user-images.githubusercontent.com/56646501/168280620-f316ddb1-cedf-4186-9f46-5616d4762654.png)
![slash inserter view 20220513](https://user-images.githubusercontent.com/56646501/168280621-8c394db0-6400-4e8d-91b1-7b0328f69ce5.png)
![the inserter 20220513](https://user-images.githubusercontent.com/56646501/168280623-47cfa634-f578-4602-9388-146007b04088.png)

Here are the new videos:
![add block from slash inserter 20220513](https://user-images.githubusercontent.com/56646501/168280659-0af6fe71-6e1e-4588-bb79-a8d30617c7b6.gif)
![add block from the inserter 20220513](https://user-images.githubusercontent.com/56646501/168280667-888ea696-89c0-4581-b2e3-f8b553be6f1f.gif)
![add block from the top toolbar 20220513](https://user-images.githubusercontent.com/56646501/168280675-38e20305-145b-4e38-b417-1cfa6028d142.gif)
![drag and drop current block 20220513](https://user-images.githubusercontent.com/56646501/168280680-4f62dc53-063a-4d70-a5fd-1a327393f022.gif)
![moving current block up or down 20220513](https://user-images.githubusercontent.com/56646501/168280683-b6cc0f74-15ae-4e0a-bb86-5fd9ff3cf09d.gif)
![screen-recorder-fri-may-13-2022-11-15-48](https://user-images.githubusercontent.com/56646501/168280687-b4ae826c-edea-41b2-8fbf-030b812d2509.gif)

**Comment by jaz-on** [comment]
Oh f... sorry @pls78 I forget to say I was working on it... :/

**Comment by zzap** [comment]
thank you so much :raised_hands:

**Comment by femkreations** [comment]
Thank you @pls78 and @jaz-on for helping out with this article and screenshots. I reviewed and updated the article.

Updated the page with all the missing details for 6.0  https://wordpress.org/support/article/adding-a-new-block/

**Comment by hannaw93** [comment]
I can pick up this issue :)
