### ISSUE TITLE
[HelpHub] List of blocks

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#309]
Article:  https://wordpress.org/support/article/blocks/

## Updating for 6.0
- [x] Update categories for theme blocks. [37723](https://github.com/WordPress/gutenberg/pull/37723)

### Updating for 5.9
- [ ] Refer to the [tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues/134)

## General
- [x] Make sure all screenshots are relevant for the current version (6.0)
- [x] Make sure videos are up to date
- [x] Make sure the headings are in sentence case
- [x] Update the changelog at the end of the article

**Comment by hdvos** [comment]
I am working on this

**Comment by hdvos** [comment]
All blocks seem to be organized differently. I will add the screenshots according to the new organization.

TEXT
<img width="296" alt="Screenshot 2022-05-13 at 11 45 38" src="https://user-images.githubusercontent.com/26040749/168257842-9cf17769-ad5d-496f-a3b8-6aab5c145ef7.png">

MEDIA
<img width="307" alt="Screenshot 2022-05-13 at 11 51 27" src="https://user-images.githubusercontent.com/26040749/168259087-7699b48b-ffb9-4e1e-93ee-e61ec2868716.png">

DESIGN
<img width="307" alt="Screenshot 2022-05-13 at 11 52 24" src="https://user-images.githubusercontent.com/26040749/168259229-81f30519-a676-47a2-b174-9664193f4c40.png">

WIDGETS
<img width="307" alt="Screenshot 2022-05-13 at 11 53 29" src="https://user-images.githubusercontent.com/26040749/168259418-193ffd73-3dc1-463e-b5b7-29f0596677e7.png">

THEME #1 (did not fit on my screen entirely)
<img width="307" alt="Screenshot 2022-05-13 at 11 54 25" src="https://user-images.githubusercontent.com/26040749/168259649-9c24810c-05fe-4ac6-afe8-36fb30d99fe8.png">
THEME #2
<img width="307" alt="Screenshot 2022-05-13 at 11 55 39" src="https://user-images.githubusercontent.com/26040749/168259820-9ce00952-25cb-408e-8d6f-e27c8287dc63.png">

EMBEDS #1 
<img width="307" alt="Screenshot 2022-05-13 at 11 56 39" src="https://user-images.githubusercontent.com/26040749/168259989-c06da58f-3f2d-4280-a79d-958d957063c0.png">
EMBEDS #2 
<img width="307" alt="Screenshot 2022-05-13 at 11 57 51" src="https://user-images.githubusercontent.com/26040749/168260303-428bebba-48b9-4553-944c-f4da032a19ef.png">

**Comment by zzap** [comment]
Thank you so much :heart:

**Comment by femkreations** [comment]
This has been updated.
