### ISSUE TITLE
[HelpHub] Preferences overview

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#310]
Article:  https://wordpress.org/support/article/preferences-overview/

## Updating for 6.1
- [x] Remove the Template panel option from the Preferences modal. [42030](https://github.com/WordPress/gutenberg/pull/42030)
- [x] Editor preferences: update order and copy. [40981](https://github.com/WordPress/gutenberg/pull/40981)
- [x] Update the modal design. [40781](https://github.com/WordPress/gutenberg/pull/40781)
- [x] Add option in editor settings to show open list view as default. [40757](https://github.com/WordPress/gutenberg/pull/40757)
- [ ] Fix list block check [41351](https://github.com/WordPress/gutenberg/pull/41351)
- [ ] Fix block switcher label to take into account block variations. [43309](https://github.com/WordPress/gutenberg/pull/43309)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos are up to date
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

**Comment by michaelbriantina** [comment]
I'll check on this!

**Comment by michaelbriantina** [comment]
The Preferences 'General' section now has slightly different options and headings.

It looks like the 'Appearance' section has been removed and merged together with the 'General' section as the 'display button labels' and 'use theme styles' options are now in the 'General' section.

<img width="755" alt="image" src="https://user-images.githubusercontent.com/30507511/168255432-8756944a-37f2-46b8-9ff5-520e3412e418.png">

The 'display button labels' screenshots are still applicable.

--

Adding screenshots to the 'Use theme styles' option

This is the effect when it is set to OFF

![image](https://user-images.githubusercontent.com/30507511/168256477-02aba65f-2d78-4a6c-b96b-2354a162d2bc.png)

This is the effect when it is set to ON

![image](https://user-images.githubusercontent.com/30507511/168256503-dca61890-4bee-4a0b-8c35-0ef3d24438ae.png)

**Comment by femkreations** [comment]
Added 6.1 tasks

**Comment by femkreations** [comment]
Completed this page https://wordpress.org/support/wp-admin/post.php?post=16133878&action=edit and set for Publish on Nov 1st.
Added screenshots and content update for 6.1
Added content for Site Editor Preferences with screenshots

**Comment by femkreations** [comment]
Completed for 6.1.
