### ISSUE TITLE
[HelpHub] Styles overview

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#313]
Article:  https://wordpress.org/support/article/styles-overview/

## Updating for 6.1
- [x] Allow setting Letter case and Decoration to 'None' and add Letter case to Global Styles. [44067](https://github.com/WordPress/gutenberg/pull/44067)
- [x] Block Spacing: using spacing controls for block gap values to support presets in the UI. [43466](https://github.com/WordPress/gutenberg/pull/43466)
- [x] Improve appearance of controls in the Global Styles Typography panel. [43304](https://github.com/WordPress/gutenberg/pull/43304)
- [x] Spacing presets: Add support for margins. [43246](https://github.com/WordPress/gutenberg/pull/43246)
- [x] Spacing presets: Implement disabling of custom space sizes. [43216](https://github.com/WordPress/gutenberg/pull/43216)
- [x] Enable alpha (opacity) in Global Styles color pickers. [43045](https://github.com/WordPress/gutenberg/pull/43045)
- [x] Add block spacing to root block support UI. [42797](https://github.com/WordPress/gutenberg/pull/42797)
- [x] Upsize typography panel components. [42718](https://github.com/WordPress/gutenberg/pull/42718)
- [ ] Fluid typography. [42688](https://github.com/WordPress/gutenberg/pull/42688)
- [x] BlockGap: Add axial gap option to global styles where available. [42490](https://github.com/WordPress/gutenberg/pull/42490)
- [x] Add layout content size controls to global styles [42309](https://github.com/WordPress/gutenberg/pull/42309)
- [x] Heading element UI controls. [42176](https://github.com/WordPress/gutenberg/pull/42176)
- [x] Heading block - add font family support [40970](https://github.com/WordPress/gutenberg/pull/40970)
- [x] Spacing presets: add editor UI support. [42173](https://github.com/WordPress/gutenberg/pull/42173)
- [x] Add support for heading elements. [41981](https://github.com/WordPress/gutenberg/pull/41981)
- [x] Add link element :hover interactivity control to global styles UI. [41976](https://github.com/WordPress/gutenberg/pull/41976)
- [x] Add UI for button elements [41659](https://github.com/WordPress/gutenberg/pull/41659)
- [x] Button Element: update button element selector. [41240](https://github.com/WordPress/gutenberg/pull/41240)
- [x] Add support for caption elements. [41140](https://github.com/WordPress/gutenberg/pull/41140)
- [x] Preset custom color duplicates. [40837](https://github.com/WordPress/gutenberg/pull/40837)
- [x] Global Styles Sidebar: tweak separator margin. [40526](https://github.com/WordPress/gutenberg/pull/40526)
- [x] Use new border control components in block support [37770](https://github.com/WordPress/gutenberg/pull/37770)
- [x] Button Element: Add support to Site Editor [41246](https://github.com/WordPress/gutenberg/pull/41246)
- [ ] Block supports: add fluid typography [39529](https://github.com/WordPress/gutenberg/pull/39529)

## Updating for 6.0
- [x] Add block icon next to blocks list. [36520](https://github.com/WordPress/gutenberg/pull/36520)
- [x]  Add elements support to the typography panel. [36718](https://github.com/WordPress/gutenberg/pull/36718)
- [x]  Add the gradient palette editor. [36820](https://github.com/WordPress/gutenberg/pull/36820)
- [x] Add transparency support to the colors panel. [36840](https://github.com/WordPress/gutenberg/pull/36840)
- [x]  Add read-only duotone palette. [36920](https://github.com/WordPress/gutenberg/pull/36920)
- [x]  Do not show default palette if theme opts-out. ([36639](https://github.com/WordPress/gutenberg/pull/36639))
- [x] Make user able to change all color palette origins. [36674](https://github.com/WordPress/gutenberg/pull/36674) [36817](https://github.com/WordPress/gutenberg/pull/36817)
- [x]  Add: Border indication to global styles colors. [36959](https://github.com/WordPress/gutenberg/pull/36959)
- [x]  Polish unset color indicator. [36994](https://github.com/WordPress/gutenberg/pull/36994)
- [x]  Add: Corners to custom color picker popover. [37015](https://github.com/WordPress/gutenberg/pull/37015)
- [x]  Add: Missing margin to the color picker clear button. [37016](https://github.com/WordPress/gutenberg/pull/37016)
- [x]  Global Styles: Call "palettes" and not "color palettes" on panel label. [36921](https://github.com/WordPress/gutenberg/pull/36921)
- [x]  Color Picker: Improve border, padding, and box shadow styles. [36963](https://github.com/WordPress/gutenberg/pull/36963)
- [x]  Color UI component: reorder palettes and update names. [36622](https://github.com/WordPress/gutenberg/pull/36622)
- [x]  Custom color picker popover position. [36965](https://github.com/WordPress/gutenberg/pull/36965)
- [x]  Make links plural in global styles. [36819](https://github.com/WordPress/gutenberg/pull/36819)
- [x]  Custom color palette: add default color name. [36940](https://github.com/WordPress/gutenberg/pull/36940)
- [x]  Add button text when no colors found. [36684](https://github.com/WordPress/gutenberg/pull/36684)
- [x]  Add labels to the global styles variations. [39322](https://github.com/WordPress/gutenberg/pull/39322)
- [x]  Global Styles Sidebar: Tweak preview box. [39978](https://github.com/WordPress/gutenberg/pull/39978)
- [x] Global Styles Sidebar: Wrap the preview box in the CardMedia component. [39980](https://github.com/WordPress/gutenberg/pull/39980)
- [x] Update "Other styles" to "Browse styles". [39752](https://github.com/WordPress/gutenberg/pull/39752)
- [x] Add the Welcome Guide option to the More Global Styles Actions dropdown. [37180](https://github.com/WordPress/gutenberg/pull/37180)
- [x]  Make the Blocks section more distinguishable. [37293](https://github.com/WordPress/gutenberg/pull/37293)
- [x] Move the Edit colors button to a standard menu item. [36842](https://github.com/WordPress/gutenberg/pull/36842)
- [x] Move Duotone palette to the bottom of global styles gradients. [37253](https://github.com/WordPress/gutenberg/pull/37253)
- [x] Allow switching global styles variations. [35619](https://github.com/WordPress/gutenberg/pull/35619)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos are up to date
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

**Comment by pls78** [comment]
I'm working on this :)

**Comment by pls78** [comment]
Here is the updated video: https://user-images.githubusercontent.com/68744851/168276796-50967efd-2574-45d1-96d9-f6b054540463.mp4

Screenshots follow, the number in the filenames (and the order in which they appear here) is related to the order of the screenshots in the doc.
<img width="291" alt="Screenshot 1" src="https://user-images.githubusercontent.com/68744851/168276821-b295e22d-d595-450b-82b5-e45c7138d254.png">

<img width="286" alt="Screenshot 2" src="https://user-images.githubusercontent.com/68744851/168276837-6efa7b90-b91e-4cdb-89ad-98e68990dc11.png">

**Comment by femkreations** [comment]
Added tasks to work for 6.1

**Comment by femkreations** [comment]
@pls78 are you still working on this page?

**Comment by pls78** [comment]
@femkreations Hi, no I'm not. Is there something needed by my side? 🙂

**Comment by femkreations** [comment]
Here is the draft of the Styles Overview page https://wordpress.org/support/wp-admin/post.php?post=16104506&action=edit covering all the trackers in [this one](https://github.com/WordPress/Documentation-Issue-Tracker/issues/313) for 6.1 and 6.0. 
I have not included Fluid Typography as I understand it is currently in theme.json only. @annezazu

**Comment by annezazu** [comment]
That's correct! Reviewed as per my messages in slack.
