### ISSUE TITLE
Migrate Site Architecture 1.5 (?) from Codex to DevHub

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#332]
## What is the new page you are requesting?

https://codex.wordpress.org/Site_Architecture_1.5

## How will this new page help you?

It should be in DevHub, most likely candidate for Common APIs handbook.

## Tasks

- [ ] Review and target outdated parts for removal
- [ ] Check all links on the page
- [ ] Links pointing to Codex pages should be replaced with equivalents from DevHub/HelpHub
- [ ] For pages that have no equivalents at DevHub/HelpHub, an issue like this one should be created.

**Comment by javiercasares** [comment]
Added into https://github.com/zzap/WordPress-Advanced-administration-handbook/pull/3

**Comment by javiercasares** [comment]
File: [resources/index.md](https://github.com/WordPress/Advanced-administration-handbook/blob/main/resources/index.md)

- Content is migrated.
- [#167](https://github.com/WordPress/Advanced-administration-handbook/issues/167) pending review
