### ISSUE TITLE
Migrate The Loop in Action from Codex to DevHub

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#333]
## What is the new page you are requesting?

https://codex.wordpress.org/The_Loop_in_Action

## How will this new page help you?

It should be in DevHub, most likely candidate for Common APIs handbook.

## Tasks

- [ ] Review and target outdated parts for removal
- [ ] Check all links on the page
- [ ] Links pointing to Codex pages should be replaced with equivalents from DevHub/HelpHub
- [ ] For pages that have no equivalents at DevHub/HelpHub, an issue like this one should be created.
