### ISSUE TITLE
[HelpHub] Appearance Menu

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#334]
Article:  https://wordpress.org/support/article/appearance-menus-screen/

## Updating for 6.0
- [ ] Add a Note:: Remove Navigation Menus from the Appearance menu. [37212](https://github.com/WordPress/gutenberg/pull/37212)

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Make sure videos are up to date
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

**Comment by leonidasmi** [comment]
I'm currently working on this :)

**Comment by leonidasmi** [comment]
1st image (not sure if the difference is big enough to warrant an update - The `Bulk Select` seems to be removed):
Old:
![image](https://user-images.githubusercontent.com/12400734/168248949-f19a1a73-2c02-4eab-84d1-faaff57dbd07.png)
New:
![image](https://user-images.githubusercontent.com/12400734/168252418-174b8668-e865-46a7-bf7e-290db16190ba.png)


2nd image ([Adding Items to a Menu](https://wordpress.org/support/article/appearance-menus-screen/#adding-items-to-a-menu)):
Remains the same

3rd image ([Deleting a Menu Item](https://wordpress.org/support/article/appearance-menus-screen/#deleting-a-menu-item)):
Remains the same

4th image ([Adding Your Menu to Your Site](https://wordpress.org/support/article/appearance-menus-screen/#adding-your-menu-to-your-site)):
Remains the same

5th image ([Rearranging, Configuring Menu Items](https://wordpress.org/support/article/appearance-menus-screen/#rearranging-configuring-menu-items)):
Remains the same

**Comment by zzap** [comment]
Yes, that is a big difference. Thank you so much @leonidasmi :heart:

**Comment by abigail0r** [comment]
Headings not in sentence case: 

- [Adding Your Menu to Your Site](https://wordpress.org/support/article/appearance-menus-screen/#adding-your-menu-to-your-site)

All other headings are in sentence case 👍

**Comment by femkreations** [comment]
@NewYorkerLaura Thank you!
