### ISSUE TITLE
[HelpHub] Update block styles for Tag Cloud block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#335]
Articles:
https://wordpress.org/support/article/tag-cloud-block/

## Updating for 6.0
- [ ] Block Styles: Show style preview when hovered or focused. [34522](https://github.com/WordPress/gutenberg/pull/34522)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by hdvos** [comment]
I am starting on the screenshots.

**Comment by hdvos** [comment]
# Image Block
<img width="673" alt="Screenshot 2022-05-13 at 13 16 47" src="https://user-images.githubusercontent.com/26040749/168272591-e021ee84-e2ba-4e9d-93b0-45f3e4e03cc9.png">
<img width="368" alt="Screenshot 2022-05-13 at 13 19 15" src="https://user-images.githubusercontent.com/26040749/168272923-8857f154-85ef-4841-8836-6800b128097c.png">

<img width="620" alt="Screenshot 2022-05-13 at 13 21 20" src="https://user-images.githubusercontent.com/26040749/168273194-9f25eccc-2315-415f-875f-ac7ea5eb9b86.png">

Adding an Image is identical, but will add it for the sake of completeness
<img width="622" alt="Screenshot 2022-05-13 at 13 23 54" src="https://user-images.githubusercontent.com/26040749/168273692-04509315-6436-4e35-8b8e-a9f2ee658c53.png">

<img width="947" alt="Screenshot 2022-05-13 at 13 28 41" src="https://user-images.githubusercontent.com/26040749/168274613-cbc839d4-bd1f-4fe6-8013-791df7759cdc.png">

[I don't know how to make the gifs.]
<img width="780" alt="Screenshot 2022-05-13 at 13 44 13" src="https://user-images.githubusercontent.com/26040749/168276566-d73f6d53-6d68-4e70-a22c-f811a503d84b.png">

[unable to do the video]
<img width="780" alt="Screenshot 2022-05-13 at 13 47 00" src="https://user-images.githubusercontent.com/26040749/168276934-1aa6b711-c674-462f-b98a-bf5e4c1d0a38.png">

[image editing video]
<img width="483" alt="Screenshot 2022-05-13 at 13 49 27" src="https://user-images.githubusercontent.com/26040749/168277278-efb98510-d93f-47ae-97ce-d813a97371ce.png">

<img width="781" alt="Screenshot 2022-05-13 at 13 51 23" src="https://user-images.githubusercontent.com/26040749/168277573-1c5ae302-9a60-44a2-b813-0c5c9eb3b1c3.png">

<img width="781" alt="Screenshot 2022-05-13 at 13 53 18" src="https://user-images.githubusercontent.com/26040749/168278151-71cc7268-ec20-4157-a5a8-28fc8371499e.png">

<img width="391" alt="Screenshot 2022-05-13 at 13 56 44" src="https://user-images.githubusercontent.com/26040749/168278282-08b90a69-b743-4553-9630-46b7bcb29137.png">

<img width="780" alt="Screenshot 2022-05-13 at 13 58 11" src="https://user-images.githubusercontent.com/26040749/168278599-e7c1fbdb-c23e-4596-ba7f-75870ef1aa08.png">

[did not do video on duotone filter]

Image for external image upload does not work in older documentation (https://wordpress.org/support/article/image-block/#external-image-upload ).

<img width="780" alt="Screenshot 2022-05-13 at 14 02 28" src="https://user-images.githubusercontent.com/26040749/168279199-ab8d592e-104c-412b-8617-de1e8301dbbc.png">

[did not do video of advanced options]

**Comment by hdvos** [comment]
# Quote Block

<img width="324" alt="Screenshot 2022-05-13 at 14 11 13" src="https://user-images.githubusercontent.com/26040749/168280449-e5f2e546-b8b1-4dce-b8ab-491935cdc2ea.png">

<img width="651" alt="Screenshot 2022-05-13 at 14 21 47" src="https://user-images.githubusercontent.com/26040749/168282071-4187d5aa-640a-4bec-b1bc-98ca3d3386e3.png">

<img width="649" alt="Screenshot 2022-05-13 at 14 22 43" src="https://user-images.githubusercontent.com/26040749/168282192-bfe13d9e-2c61-4637-ac8a-001f0a877b1f.png">

<img width="968" alt="Screenshot 2022-05-13 at 14 25 14" src="https://user-images.githubusercontent.com/26040749/168282581-08ccd822-3a95-4974-a91b-834353a2806a.png">
<img width="375" alt="Screenshot 2022-05-13 at 14 29 55" src="https://user-images.githubusercontent.com/26040749/168283705-6899691c-b3e7-4b17-abd0-722e1e5e4177.png">

<img width="601" alt="Screenshot 2022-05-13 at 14 36 14" src="https://user-images.githubusercontent.com/26040749/168284417-1f1e257a-67cc-4ed1-88f6-f3d5bfa536cf.png">

<img width="372" alt="Screenshot 2022-05-13 at 14 37 07" src="https://user-images.githubusercontent.com/26040749/168284534-becff41d-c7d0-4960-a785-96ad41c253fe.png">

<img width="274" alt="Screenshot 2022-05-13 at 14 37 52" src="https://user-images.githubusercontent.com/26040749/168284634-d73c71a2-5e41-4a70-b0be-a5e5d1f63227.png">

[I cannot find the text color option]

<img width="266" alt="Screenshot 2022-05-13 at 14 41 47" src="https://user-images.githubusercontent.com/26040749/168285291-e1992fcf-d0d7-436e-81ea-af159bb31e3a.png">

<img width="378" alt="Screenshot 2022-05-13 at 14 49 36" src="https://user-images.githubusercontent.com/26040749/168286914-de06ce1e-ff78-4e4b-bdf3-186abb178cde.png">

<img width="279" alt="Screenshot 2022-05-13 at 14 52 29" src="https://user-images.githubusercontent.com/26040749/168287176-7033f250-1277-40fb-a200-322f62194848.png">

<img width="286" alt="Screenshot 2022-05-13 at 14 53 21" src="https://user-images.githubusercontent.com/26040749/168287317-032ad2d2-4a29-4af7-9dea-6ba68b55cfb4.png">

**Comment by hdvos** [comment]
I did not get to:
https://wordpress.org/support/article/table-block/
https://wordpress.org/support/article/buttons-block/
https://wordpress.org/support/article/separator-block/
https://wordpress.org/support/article/tag-cloud-block/
https://wordpress.org/support/article/social-icons/
https://wordpress.org/support/article/wordpress-editor/

**Comment by zzap** [comment]
@hdvos thank you so much for your screenshots :heart:  They can be used in another issue.

This issue is about block styles. For example, image block has two styles: default and rounded.

![image-default-style](https://user-images.githubusercontent.com/1508963/172213306-54366599-e9bd-4425-8f10-12c6a4b8d6c4.png)

![image-rounded-style](https://user-images.githubusercontent.com/1508963/172213309-5618a205-71d0-4a77-9b64-f0ddcd523b34.png)

You can continue if you wish :raised_hands:

**Comment by femkreations** [comment]
The block styles need to be updated only for the tag cloud block.

**Comment by samxmunoz** [comment]
Taking this one :)

**Comment by samxmunoz** [comment]
**This is ready for review!! 🎉** @zzap and @femkreations 

I have updated screenshots for this, added alt text & added the block style previews.

**Comment by Leonardus-Nugraha** [comment]
Thanks @samxmunoz for the content update! I've reviewed them and all are great!
