### ISSUE TITLE
[HelpHub] Update border properties in the Border Settings panel 

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#336]
Articles:
https://wordpress.org/support/article/search-block/
https://wordpress.org/support/article/pullquote-block/
https://wordpress.org/support/article/group-block/
https://wordpress.org/support/article/code-block/
https://wordpress.org/support/article/table-block/
https://wordpress.org/support/article/buttons-block/
https://wordpress.org/support/article/image-block/

Make the screenshot update for the about listed articles (for block properties with border settings) for the tracker listed below.

## Updating for 6.0
- [ ] Border controls: display border properties in the ToolPanel. ([34061](https://github.com/WordPress/gutenberg/pull/34061)

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Make sure videos are up to date
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

**Comment by manuelaugustin** [comment]
I'll make a start on checking the screenshots for the articles mentioned in this issue

**Comment by manuelaugustin** [comment]
Below you can find updated screenshots, divided by article.

## Search block

### Block settings
![block settings](https://user-images.githubusercontent.com/27805437/168278605-3acb8c18-136c-4ebb-88af-2facd1d9cab7.jpeg)

### Button position
![button position](https://user-images.githubusercontent.com/27805437/168278608-c3bd6606-6c11-4eff-ad65-7b6f2a8b9649.jpeg)

### More options
![more options](https://user-images.githubusercontent.com/27805437/168278612-7235539e-7668-4674-b9d5-0c32fa9e673e.jpeg)

**Comment by abigail0r** [comment]
https://wordpress.org/support/article/search-block/
- "Change Button Position" subheading is not in sentence format
- "Alignment:" and "More Options:" subheadings contain unnecessary colons

https://wordpress.org/support/article/pullquote-block/
- "More Text Editing Options" is not in sentence format
- "Transform to:" "Moving handles:" "Change Alignment:" "Text Editing Options:" "More Options:" subheadings contain unnecessary colons

https://wordpress.org/support/article/buttons-block/
- "More Options:" subheading contains unnecessary colons

**Comment by zzap** [comment]
This issue is about border settings for blocks that has it. For example, this is setting for image block

![image-border-settings](https://user-images.githubusercontent.com/1508963/172214723-394bf4ea-7503-4014-8afb-1353d20f7c13.png)

**Comment by colorful-tones** [comment]
I'll be working through this on Friday. Self assigning for now.

**Comment by femkreations** [comment]
Closing this issue as we are moving the Border Properties to a separate new page and revamping all the block articles by linking to the new page. #480
