### ISSUE TITLE
[HelpHub] Search block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#337]
Article:  https://wordpress.org/support/article/search-block/

### Updating for 5.9
- [ ] Refer to the [tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues/160)

## General
- [ ] Make sure all screenshots are relevant for the current version (6.0)
- [ ] Make sure videos are up to date
- [ ] Make sure the headings are in sentence case
- [ ] Update the changelog at the end of the article

**Comment by michaelbriantina** [comment]
I'll check on this issue.

**Comment by michaelbriantina** [comment]
I noticed there are no screenshots or written sections for the 'use button with icon' 

![image](https://user-images.githubusercontent.com/30507511/168250288-97fdf62e-220f-41d2-93e1-663d7bf1a16e.png)

![image](https://user-images.githubusercontent.com/30507511/168250326-93cf75e3-30cb-4b90-9f1a-200bbfdd81da.png)

--

The 'more options' setting shows slightly different options now as well

![image](https://user-images.githubusercontent.com/30507511/168250993-6f4c9c6b-0310-428c-8d01-eedb56129fdb.png)

--

The search block setting also now has a 'color' option

![image](https://user-images.githubusercontent.com/30507511/168251645-986612ee-109e-433f-9b60-3175333d1923.png)

**Comment by abigail0r** [comment]
Headings not in sentence case:

- "Change Button Position"

All other headings are in sentence case 👍

**Comment by zzap** [comment]
Here's new 6.0 settings

![search-button-settings](https://user-images.githubusercontent.com/1508963/172215718-4d9efb6d-106a-4ac2-a967-39c9770df86c.png)

Headings fixed, thank you @abigail0r
