### ISSUE TITLE
[HelpHub] Block Patterns

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#338]
Articles:
https://wordpress.org/support/article/block-pattern/
https://wordpress.org/support/article/pages-add-new-screen/
https://wordpress.org/support/article/submit-your-block-pattern-to-the-directory/

Update the above articles for the tracker listed below.

## Updating for 6.0
- [ ] Add: Option to pick a pattern on page creation. [40034](https://github.com/WordPress/gutenberg/pull/40034)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by manuelaugustin** [comment]
I'll check this article

**Comment by manuelaugustin** [comment]
Here are updated screenshots for https://wordpress.org/support/article/block-pattern/#how-to-use-a-block-pattern. There were only some very minor changes in the interface as far as I can see.

![contextual patterns](https://user-images.githubusercontent.com/27805437/168261451-03749bcb-6d87-44c0-9f06-c78d052fff3f.jpeg)
![edit block](https://user-images.githubusercontent.com/27805437/168261455-6a46f1a8-3169-4bed-80cd-90b4d45eccd3.jpeg)

And here are updated screenshots for https://wordpress.org/support/article/pages-add-new-screen/. The current screenshot still used the classic editor. I've made a version with the block editor.
![Pages add new screen](https://user-images.githubusercontent.com/27805437/168261638-cdb1a316-fe41-447b-afec-e8376af7619d.jpeg)

**Comment by zzap** [comment]
Thank you so much @manuelaugustin :heart:

**Comment by abigail0r** [comment]
**Re: https://wordpress.org/support/article/block-pattern/#how-to-use-a-block-pattern** 

- The subheadings appear in the same size and weight as paragraph text.
- [How to Customize a Block Pattern](https://wordpress.org/support/article/block-pattern/#how-to-customize-a-block-pattern) is not in sentence case

**Re: https://wordpress.org/support/article/pages-add-new-screen/**

All subheadings are in sentence format 👍

**Comment by colorful-tones** [comment]
https://wordpress.org/support/article/block-pattern/#how-to-use-a-block-pattern

- [x] Make sure all screenshots are relevant to the latest version
- [x] Make sure videos are up to date
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

**Comment by colorful-tones** [comment]
https://wordpress.org/support/article/pages-add-new-screen/

I feel like the title for this doc should read: `Pages > Add New screen`. Perhaps I'm confused about the rules of sentence case.  I'm using this as my reference point: [Sentence Case Capitalization](https://apastyle.apa.org/style-grammar-guidelines/capitalization/sentence-case) @femkreations

**Comment by colorful-tones** [comment]
https://wordpress.org/support/article/submit-your-block-pattern-to-the-directory/

I made some grammatical and spelling updates, but I still need to work through the checklist.

**Comment by colorful-tones** [comment]
@femkreations I'm wondering if we could deprecate this doc: https://wordpress.org/support/article/pages-add-new-screen/

And merge any missing data (very little if any) into the better: https://wordpress.org/support/article/pages/
🤔

**Comment by femkreations** [comment]
@colorful-tones Yes that is a great idea.  Pls add all relevant info from [Pages Add New screen](https://wordpress.org/support/article/pages-add-new-screen/) to [Pages](https://wordpress.org/support/article/pages/)

And unpublish [Pages Add New screen](https://wordpress.org/support/article/pages-add-new-screen/)

@estelaris Can you pls make a note of this for redirecting the [Pages Add New screen](https://wordpress.org/support/article/pages-add-new-screen/) to  [Pages](https://wordpress.org/support/article/pages/)

**Comment by estelaris** [comment]
@colorful-tones and @femkreations before deprecating anything make sure they are not Classi Editor vs Block Editor info. 

If you see ticket #192 there are the following articles
- [ Pages ]( https://wordpress.org/support/article/pages/) > Create pages
- [ Pages Add New Screen](https://wordpress.org/support/article/pages-add-new-screen/) > Pages add new screen (Classic Editor)
- [ Pages Add New Screen](https://wordpress.org/support/?post_type=helphub_article&p=11032028) draft > Pages add new screen (Block Editor)

**Comment by femkreations** [comment]
Thanks @colorful-tones @manuelaugustin and @abigail0r I have reviewed https://wordpress.org/support/article/block-pattern/ and made minor edits to the heading levels and removed an external link in the Resources section.

**Comment by femkreations** [comment]
I am currently reviewing the Submit Block Pattern page

**Comment by femkreations** [comment]
Reviewed and reworked this page. https://wordpress.org/support/article/submit-your-block-pattern-to-the-directory/

**Comment by femkreations** [comment]
Added a link to the [Pages Add New screen](https://wordpress.org/support/article/pages-add-new-screen/) in [Pages](https://wordpress.org/support/article/pages/) to refer if the user is using a classic editor. Otherwise we have the info covered in the [Pages](https://wordpress.org/support/article/pages/)  for Block editor. Looks good. Thanks
