### ISSUE TITLE
[HelpHub] Media+Text Block 

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#340]
Article:  https://wordpress.org/support/article/media-text-block/

## Updating for 6.1
- [ ] Improve content locking on media & text block. [44036](https://github.com/WordPress/gutenberg/pull/44036)
- [ ] Add __experimentalRole attributes to media text block. [43957](https://github.com/WordPress/gutenberg/pull/43957)
- [ ] Display upload error notices using snackbars. [43890](https://github.com/WordPress/gutenberg/pull/43890)
- [ ]  Add spacing block supports. [43456](https://github.com/WordPress/gutenberg/pull/43456)
- [ ]  Add typography support. [43314](https://github.com/WordPress/gutenberg/pull/43314)
- [ ] Add transform between cover and media & text. [38458](https://github.com/WordPress/gutenberg/pull/38458)
- [ ] Remove redundant block name from "settings" panels [40275](https://github.com/WordPress/gutenberg/pull/40275)

## Updating for 6.0
- [ ] Media & Text: Display media while uploading. [39275](https://github.com/WordPress/gutenberg/pull/39275)

## Updating for 5.6
- [x] set image size - [24688](https://github.com/WordPress/gutenberg/issues/24688)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos are up to date
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

**Comment by michaelbriantina** [comment]
The 'transform to' option now has a few more options

<img width="321" alt="image" src="https://user-images.githubusercontent.com/30507511/168252955-f868282c-8f3a-4f77-ab91-33b26d11051c.png">

--

There's also now an option of 'none' aside from just 'wide width' and 'full width'

<img width="240" alt="image" src="https://user-images.githubusercontent.com/30507511/168253211-7717cddd-8357-4d8a-bddf-fadec19b2fd3.png">

--

The options have now omitted the 'vertically' text

<img width="147" alt="image" src="https://user-images.githubusercontent.com/30507511/168253359-4e097dcc-7c84-4f88-bc97-c5146a91fce4.png">

--

The more options setting has slightly different options now: (hide block settings vs. hide more settings, there's a new 'lock' option, and remove block vs. remove media & text)

![image](https://user-images.githubusercontent.com/30507511/168253666-365e8139-8372-404a-a38e-543bef446b32.png)

--

In the block settings, there's a new option for 'styles'

<img width="279" alt="image" src="https://user-images.githubusercontent.com/30507511/168254182-6690b870-ee78-4791-b106-74ca03c3714a.png">

The color settings are now also slightly different as there is an option for text and background now:

![image](https://user-images.githubusercontent.com/30507511/168254458-687d3997-5c78-4fb1-a60f-d29cbfb1d981.png)

![image](https://user-images.githubusercontent.com/30507511/168254491-3cc0a9a8-3316-48c5-9b4d-9b6b976f0009.png)

--

There's now also an 'HTML anchor' option in the Advanced tab

<img width="280" alt="image" src="https://user-images.githubusercontent.com/30507511/168254677-ec06e95a-c97e-4fca-9bd6-da98901051e9.png">

**Comment by NewYorkerLaura** [comment]
I am going to work on this today at the WCEU contributor day, verifying we are fully updated for 6.0

**Comment by abigail0r** [comment]
The title says "Media + Text" while the rest of the article refers to the block as "Media & Text"

**Comment by NewYorkerLaura** [comment]
@abigail0r I'm in process currently updating I'll make the Media & Text change

**Comment by NewYorkerLaura** [comment]
@femkreations 

As WCEU Contributor Day2022-06-02 

The following has been accomplished:
- All screenshots are relevant for the current version (6.0)
- The headings are in sentence case
- Updated the changelog at the end of the article to reflect updates to text and images

Outstanding
- The video still needs to be updated

**Comment by samxmunoz** [comment]
I'll handle the video for this one & updating the article - please assign to me @femkreations / @zzap

**Comment by femkreations** [comment]
Added tasks for 6.1

## Notes
1. We are not adding detailed updates for the Block settings as we are revamping the block settings for all the block articles 
2. Pls make 6.1 updates first and then move into 6.0.
3. Some of the PRs for 6.1 have great videos that can be added to the article (even for the Block settings section)
4. For 6.0, you can pick the screenshots added in the comments previously.

**Comment by femkreations** [comment]
@samxmunoz would you be able to update this page for 6.1?

**Comment by samxmunoz** [comment]
@femkreations / @zzap - this is **READY FOR REVIEW** for the 6.1 release (scheduled for Nov 1 @ 6:00 am UTC).

**Comment by femkreations** [comment]
Thanks @samxmunoz The info looks great. 
I updated the following info as well.
-Removed Color settings and added a link to the Color overview page
-Added Dimension and Typography settings and linked to their overview pages
-Updated a few more screenshots for 6.1.
-Added info about Insert link in the Block toolbar.
