### ISSUE TITLE
Unnecessary  articles to delete

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#373]
## Issue Description

Article contains a number of links to WP articles in order to find them. The new site map will make it easier to search for articles and this type of articles will be unnecessary.

## URL of the Page with the Issue

https://wordpress.org/support/article/wordpress-lessons/)

## Suggested Fix

Delete article

- [x] [WordPress lessons](https://wordpress.org/support/article/wordpress-lessons/) > delete
- [x] [Features](https://wordpress.org/support/article/wordpress-features/) > delete
- [x] [Requirements](https://wordpress.org/support/article/requirements/) > delete
- [ ]

**Comment by estelaris** [comment]
Articles have been deleted in the /documentation-test/ site

**Comment by estelaris** [comment]
WordPress lessons > was deleted without a redirect
Features > redirected to https://wordpress.org/about/features/
Requirements > redirected to https://wordpress.org/about/requirements/
