### ISSUE TITLE
Contributor Day Tasks

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#374]
When you don't know what to do at Contributor Day, check these:

- [ ] Code reference comments formatting (spacing etc)
- [ ] Updating screenshots to current version (mostly HelpHub)
- [ ] ALT tags for images (mostly HelpHub)
- [ ] All headings should be in sentence case

**Comment by bph** [comment]
Helpful links to share with people at Documentation tables at Contributor Days

- [Documentation Issues Tracker](https://github.com/WordPress/Documentation-Issue-Tracker/issues/340)
- [Documentation Style Guide](https://make.wordpress.org/docs/style-guide/)
-
