### ISSUE TITLE
[DevHub] Fixing escaping and internationalization mistakes in user contributed notes

### ISSUE THREAD

**Issue by lucprincen** [WordPress/Documentation-Issue-Tracker#375]
I'm creating and updating this issue and plan on collecting issues with user contributed notes in the code reference. 

**Contributing**
This issue will frequently be updated and I encourage you to add mistakes you find in the comments with the following format:

( checkbox ) - Brief issue description - link to comment 
( larger issue description if warranted ). 

**Progress**
Currently i've scrubbed function references pages 1 and 2 (of 111 😅). Feel free to start at page 3:
https://developer.wordpress.org/reference/functions/page/3/

**Missing escapes and sanitation:**
- [ ] add `\absint()` around **$item_id** of this comment to escape as late as possible - [reference: WP_Query](https://developer.wordpress.org/reference/classes/wp_query/#comment-3451)
- [ ] add `\esc_html()` around **$myvar** to escape as late as possible - [reference: add_action](https://developer.wordpress.org/reference/functions/add_action/#comment-3546)
- [ ] change `printf` statement to code example below this todo - [reference: add_action](https://developer.wordpress.org/reference/functions/add_action/#comment-3937)
`printf( esc_html__( 'Comment ID %s could not be found.', 'textdomain' ), \absint( $comment_id ) );`
- [ ] add `sanitize_text_field()` around **$_POST['wpdocs-meta-name']** in `update_post_meta` declaration - [reference: add_meta_box](https://developer.wordpress.org/reference/functions/add_meta_box/#comment-3677)
- [ ] declaration of `esc_attr()` at the bottom in the textarea should become `esc_textarea()` - [reference: add_meta_box](https://developer.wordpress.org/reference/functions/add_meta_box/#comment-5302)
- [ ] add `esc_html()` around **$wp_query->query_vars** mentions - [reference: add_rewrite_rule](https://developer.wordpress.org/reference/functions/add_rewrite_rule/#comment-4554)
- [ ] add `esc_attr()` to **button_attrs['url']** declaration - [reference: add_shortcode](https://developer.wordpress.org/reference/functions/add_shortcode/#comment-5631) 
- [ ] add `esc_html()` to **echo get_site_option()** declarations - [reference: add_site_option](https://developer.wordpress.org/reference/functions/add_site_option/#comment-1327)

**Strings requiring internationalization:**
- [ ] strings in this comment - [reference: add_action](https://developer.wordpress.org/reference/functions/add_action/#comment-353)
- [ ] string 'Hello World' - [reference: add_action](https://developer.wordpress.org/reference/functions/add_action/#comment-2658)
- [ ] string 'Hello' - [reference: add_action](https://developer.wordpress.org/reference/functions/add_action/#comment-3937)
- [ ] strings 'aye!' - [reference: add_feed](https://developer.wordpress.org/reference/functions/add_feed/#comment-2086)
- [ ] missing textdomain in strings 'Square medium' and 'Square large' - [reference: add_image_size](https://developer.wordpress.org/reference/functions/add_image_size/#comment-5074)
- [ ] strings 'My WP tool page' and 'My WP tool' - [reference: add_management_page](https://developer.wordpress.org/reference/functions/add_management_page/#comment-963)
- [ ] strings 'My page title', 'Title in the menu' and 'this is the content of the page - [reference: add_management_page](https://developer.wordpress.org/reference/functions/add_management_page/#comment-2983)
`maybe not though, because they seem to more describe the contents of those parameters?`
- [ ] all capitalized strings in this comment - [reference: add_menu_page](https://developer.wordpress.org/reference/functions/add_menu_page/#comment-4771)
- [ ] all capitalized strings in this comment - [reference: add_menu_page](https://developer.wordpress.org/reference/functions/add_menu_page/#comment-2169)
- [ ] string 'Unsubscribe email list' - [reference: add_menu_page](https://developer.wordpress.org/reference/functions/add_menu_page/#comment-1266)
- [ ] missing textdomain in last code string of this comment - [reference: add_menu_page](https://developer.wordpress.org/reference/functions/add_menu_page/#comment-5845)
- [ ] all capitalized strings in `add_menu_page` function call - [reference: add_menu_page](https://developer.wordpress.org/reference/functions/add_menu_page/#comment-1593)
- [ ] string 'Last modified' - [reference: add_meta_box](https://developer.wordpress.org/reference/functions/add_meta_box/#comment-342)
- [ ] string 'Social link' - [reference: add_meta_box](https://developer.wordpress.org/reference/functions/add_meta_box/#comment-3677)
- [ ] missing textdomain - [reference: add_meta_box](https://developer.wordpress.org/reference/functions/add_meta_box/#comment-3496)
- [ ] `esc_html()` declarations should become `esc_html__()` declarations - [reference: add_meta_box](https://developer.wordpress.org/reference/functions/add_meta_box/#comment-5469)
- [ ] capitalized strings in this comment - [reference: add_rewrite_rule](https://developer.wordpress.org/reference/functions/add_rewrite_rule/#comment-4554)
- [ ] string 'Custom subscriber' - [reference: add_role](https://developer.wordpress.org/reference/functions/add_role/#comment-3194), [additionally in this comment](https://developer.wordpress.org/reference/functions/add_role/#comment-942)
- [ ] string 'Superintendent' - [reference: add_role](https://developer.wordpress.org/reference/functions/add_role/#comment-3596)
- [ ] string 'My label' - [reference: add_screen_option](https://developer.wordpress.org/reference/functions/add_screen_option/#comment-3456)
- [ ] strings 'This is the setting title' and 'Content here' - [reference: add_settings_field](https://developer.wordpress.org/reference/functions/add_settings_field/#comment-2392), [additionally this comment](https://developer.wordpress.org/reference/functions/add_settings_field/#comment-2393)
- [ ] string 'My new checkbox' - [reference: add_settings_field](https://developer.wordpress.org/reference/functions/add_settings_field/#comment-3052)
- [ ] string 'WP Custom Setting Section' - [reference: add_settings_section](https://developer.wordpress.org/reference/functions/add_settings_section/#comment-2871)
- [ ] string 'Hello shortcode' - [reference: add_shortcode](https://developer.wordpress.org/reference/functions/add_shortcode/#comment-5379)
- [ ] all capitalized strings - [reference: add_submenu_page](https://developer.wordpress.org/reference/functions/add_submenu_page/#comment-446)
- [ ] strings 'Submenu Title' - [reference: add_submenu_page](https://developer.wordpress.org/reference/functions/add_submenu_page/#comment-446)
- [ ] strings 'My Custom Submenu Page' - [reference: add_submenu_page](https://developer.wordpress.org/reference/functions/add_submenu_page/#comment-445), [also this comment](https://developer.wordpress.org/reference/functions/add_submenu_page/#comment-2470)
- [ ] strings 'My custom page' - [reference: add_submenu_page](https://developer.wordpress.org/reference/functions/add_submenu_page/#comment-1980) 
- [ ] strings 'Product filter by ambient noise' - [reference: add_submenu_page](https://developer.wordpress.org/reference/functions/add_submenu_page/#comment-4324)

**Comment by lucprincen** [comment]
Request to add the tracking issue label to this one @zzap

**Comment by zzap** [comment]
This baby is all yours now :heart:
