### ISSUE TITLE
Move articles from Helphub to Devhub

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#388]
## Issue Description

Move articles to DevHub. Some will fit in the new Advance Administration that will be created under DevHub as [per meta ticket #6411](https://meta.trac.wordpress.org/ticket/6411), while others can be merged into existing articles or included in other sections.
**_Articles that need to be moved in full are in this list. For articles that need sections removed, see the project [Inventory of Technical Parts From End User Docs](https://github.com/orgs/WordPress/projects/26/views/1)_**

## URL of the Page with the Issue

See list below for links

## Why is this a problem?

Removing developer-focused and developer jargon from articles in HelpHub

## Suggested Fix

- [x] [Before Installing](https://wordpress.org/support/article/before-you-install/)
- [x] [Nginx](https://wordpress.org/support/article/nginx/)
- [x] [Creating Database for WordPress](https://wordpress.org/support/article/creating-database-for-wordpress/)
- [x] [Installing WordPress](https://wordpress.org/support/article/how-to-install-wordpress/)
- [x] [Installing WordPress at popular Hosting Companies](https://wordpress.org/support/article/installing-wordpress-at-popular-hosting-companies/)
- [x] [Running a Development Copy of WordPress](https://wordpress.org/support/article/running-a-development-copy-of-wordpress/)
- [x] [Installing WordPress on your own Computer](https://wordpress.org/support/article/installing-wordpress-on-your-own-computer/)
- [x] [Installing WordPress in Your Language](https://wordpress.org/support/article/installing-wordpress-in-your-language/)
- [x] [Common WordPress errors](https://wordpress.org/support/article/common-wordpress-errors/)
- [x] [Cookies](https://wordpress.org/support/article/cookies/)
- [x] [CSS](https://wordpress.org/support/article/css/)
- [x] [Loopbacks](https://wordpress.org/support/article/loopbacks/)
- [x] [Optimization caching](https://wordpress.org/support/article/optimization-caching/)

**Comment by lucprincen** [comment]
@zzap can we add the advanced administration label to this issue?

**Comment by lucprincen** [comment]
I'll do some work today and tomorrow to complete this list of todo's as we have an extensive google doc filled with pages that need to be ported over.

**Comment by lucprincen** [comment]
We also currently have two projects that try to deal with **advanced administration** content which we might chose to merge? Feels like the content in "Inventory of technical parts from end user docs" should eventually be in an issue for the Advanced administration handbook.

![Schermafbeelding 2022-08-15 om 10 21 36](https://user-images.githubusercontent.com/3257545/184601670-09795e61-1cef-48f8-8b6e-74810cf0fb24.png)

**Comment by zzap** [comment]
> We also currently have two projects that try to deal with **advanced administration** content which we might chose to merge? Feels like the content in "Inventory of technical parts from end user docs" should eventually be in an issue for the Advanced administration handbook.
> 
> ![Schermafbeelding 2022-08-15 om 10 21 36](https://user-images.githubusercontent.com/3257545/184601670-09795e61-1cef-48f8-8b6e-74810cf0fb24.png)

Actually no. Not everything from HelpHub will end up in Advanced administration. Some of it is strictly for developers and will, most likely, go to Common APIs.

**Comment by lucprincen** [comment]
More pages added to the suggested fix:

- [ ] [Administration over ssl](https://wordpress.org/support/article/administration-over-ssl/)
- [ ] [Backing up your database](https://wordpress.org/support/article/backing-up-your-database/)
- [ ] [Backing up your WordPress files](https://wordpress.org/support/article/backing-up-your-wordpress-files/)
- [ ] [Before you create a network](https://wordpress.org/support/article/before-you-create-a-network/) 
- [ ] [Brute Force Attacks](https://wordpress.org/support/article/brute-force-attacks/)
- [ ] [Optimization Caching](https://wordpress.org/support/article/optimization-caching/)
- [ ] [Changing File Permissions](https://wordpress.org/support/article/changing-file-permissions/)
- [ ] [Changing the site url](https://wordpress.org/support/article/changing-the-site-url/)
- [ ] [Configuring automatic background updates](https://wordpress.org/support/article/configuring-automatic-background-updates/)
- [ ] [Configuring wildcard subdomains](https://wordpress.org/support/article/configuring-wildcard-subdomains/)
- [ ] [Create a Network](https://wordpress.org/support/article/create-a-network/)
- [ ] [Debugging a WordPress Network](https://wordpress.org/support/article/debugging-a-wordpress-network/)
- [ ] [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/)
- [ ] [Editting files](https://wordpress.org/support/article/editing-files/)
- [ ] [Editting wp-config.php](https://wordpress.org/support/article/editing-wp-config-php/)
- [ ] [Emptying a database table](https://wordpress.org/support/article/emptying-a-database-table/)
- [ ] [Upgrading WordPress (extended instructions)](https://wordpress.org/support/article/upgrading-wordpress-extended-instructions/)
- [ ] [Finding server info](https://wordpress.org/support/article/finding-server-info/)
- [ ] [Giving WordPress its own directory](https://wordpress.org/support/article/giving-wordpress-its-own-directory/)
- [ ] [Hardening WordPress](https://wordpress.org/support/article/hardening-wordpress/)
- [ ] [Installing multiple blogs](https://wordpress.org/support/article/installing-multiple-blogs/)
- [ ] [Installing WordPress in your language](https://wordpress.org/support/article/installing-wordpress-in-your-language/)
- [ ] [Migrating multiple blogs into WordPress multisite](https://wordpress.org/support/article/migrating-multiple-blogs-into-wordpress-multisite/)
- [ ] [Moving WordPress](https://wordpress.org/support/article/moving-wordpress/)
- [ ] [Multilingual WordPress](https://wordpress.org/support/article/multilingual-wordpress/)
- [ ] [Multisite network administration](https://wordpress.org/support/article/multisite-network-administration/)
- [ ] [Must-use Plugins](https://wordpress.org/support/article/must-use-plugins/)
- [ ] [Network Admin](https://wordpress.org/support/article/network-admin/)
- [ ] [Network Admin sites screen](https://wordpress.org/support/article/network-admin-sites-screen/)
- [ ] [Network Admin updates screen](https://wordpress.org/support/article/network-admin-updates-screen/)
- [ ] [Optimization](https://wordpress.org/support/article/optimization/)
- [ ] [Restoring your database from backup](https://wordpress.org/support/article/restoring-your-database-from-backup/)
- [ ] [Test driving WordPress](https://wordpress.org/support/article/test-driving-wordpress/)
- [ ] [Two step authentication](https://wordpress.org/support/article/two-step-authentication/)
- [ ] [Update services](https://wordpress.org/support/article/update-services/)
- [ ] [Using cpanel](https://wordpress.org/support/article/using-cpanel/)
- [ ] [Using filezilla](https://wordpress.org/support/article/using-filezilla/)
- [ ] [FTP Clients](https://wordpress.org/support/article/ftp-clients/)
- [ ] [Phpmyadmin](https://wordpress.org/support/article/phpmyadmin/)
- [ ] [Using your browser to diagnose javascript errors](https://wordpress.org/support/article/using-your-browser-to-diagnose-javascript-errors/)
- [ ] [Why should I use https](https://wordpress.org/support/article/why-should-i-use-https/)
- [ ] [WordPress backups](https://wordpress.org/support/article/wordpress-backups/)
- [ ] [Cookies](https://wordpress.org/support/article/cookies/)
- [ ] [WordPress multisite domain mapping](https://wordpress.org/support/article/wordpress-multisite-domain-mapping/)

**Comment by femkreations** [comment]
@lucprincen @zzap The oEmbed information has been pulled out of the Embeds article: https://wordpress.org/support/article/embeds/ and moved to the google doc shared below. Pls add this to the Advanced Administration Handbook. Thanks

https://docs.google.com/document/d/1ni59ohlSHeCH_BwRtxUXzGY1LLWqFiaaGQFcCjh_2rQ/edit?usp=sharing

**Comment by javiercasares** [comment]
> @lucprincen @zzap The oEmbed information has been pulled out of the Embeds article: https://wordpress.org/support/article/embeds/ and moved to the google doc shared below. Pls add this to the Advanced Administration Handbook. Thanks
> 
> https://docs.google.com/document/d/1ni59ohlSHeCH_BwRtxUXzGY1LLWqFiaaGQFcCjh_2rQ/edit?usp=sharing

Added to the AAH Doc.

**Comment by femkreations** [comment]
@javiercasares Can you pls share a link so I can add it to the Embed block page for reference? Thanks

**Comment by javiercasares** [comment]
> @javiercasares Can you pls share a link so I can add it to the Embed block page for reference? Thanks

https://docs.google.com/document/d/1fVIw3DztzyVY18RDPCGk-kDYTO6gzHtx81o7aitGijo/

**Comment by javiercasares** [comment]
Added to https://github.com/zzap/WordPress-Advanced-administration-handbook/pull/3

**Comment by femkreations** [comment]
Adding one more page section to the list : https://wordpress.org/support/article/wordpress-feeds/#wordpress-built-in-feeds @javiercasares

**Comment by femkreations** [comment]
Adding #79 #73 #72 and #70 that has pages with sections that need to be moved into the Advanced Administration @javiercasares

**Comment by lucprincen** [comment]
I've managed to include the text you referenced in #79 and #73 in [this pull-request](https://github.com/zzap/WordPress-Advanced-administration-handbook/pull/68) @femkreations, but the content for #72, #58 and #70 has already been removed; is there a place where we can retrieve the old technical content? 

Additionally: I honestly have no idea where to 'put' the [build in feeds](https://wordpress.org/support/article/wordpress-feeds/#wordpress-built-in-feeds) article... it's not really related to advanced administration, or should we consider an "endpoints" category @javiercasares ? Where we can list feeds, maybe even default rest-api endpoints? Dunno, just an idea.

**Comment by femkreations** [comment]
@lucprincen You can find the deleted sections in this [google drive](https://drive.google.com/drive/u/1/folders/1e6ppOQ1SPF9dCoBMdCbOJC04-y4gfFWC)

**Comment by zzap** [comment]
- [Before Installing](https://wordpress.org/support/article/before-you-install/) is moved [here](https://github.com/zzap/WordPress-Advanced-administration-handbook/blob/main/before-install/index.md).

**Comment by javiercasares** [comment]
> Additionally: I honestly have no idea where to 'put' the [build in feeds](https://wordpress.org/support/article/wordpress-feeds/#wordpress-built-in-feeds) article... it's not really related to advanced administration, or should we consider an "endpoints" category @javiercasares ? Where we can list feeds, maybe even default rest-api endpoints? Dunno, just an idea.

I like very much having a REST-API / whatever usual endpoints... or just like some examples from the WordPress.org news site... having examples for the latest posts, authors or whatever :)

**Comment by zzap** [comment]
[Nginx](https://wordpress.org/support/article/nginx/) has a PR [here](https://github.com/zzap/WordPress-Advanced-administration-handbook/pull/79).

**Comment by zzap** [comment]
[Debugging a WordPress Network](https://wordpress.org/support/article/debugging-a-wordpress-network/) is moved [here](https://github.com/zzap/WordPress-Advanced-administration-handbook/blob/main/debug/debug-network.md)

**Comment by zzap** [comment]
[Finding server info](https://wordpress.org/support/article/finding-server-info/) PR is [here](https://github.com/zzap/WordPress-Advanced-administration-handbook/pull/82).

**Comment by estelaris** [comment]
Found another article for DevHub

- [ ] [FAQ Troubleshooting](https://wordpress.org/documentation/article/faq-troubleshooting-2/)

**Link will work after Jan 17**

**Comment by javiercasares** [comment]
The only page pending migration is [FAQ Troubleshooting](https://wordpress.org/documentation/article/faq-troubleshooting-2/), but there is a ticket here:

- [#171](https://github.com/WordPress/Advanced-administration-handbook/issues/171)

**Comment by estelaris** [comment]
We are reviewing articles to confirm the redirection from HH to Adv Admin handbook
