### ISSUE TITLE
Is this a duplicated article? Dimension Controls Overview

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#425]
## Issue Description

There is a draft called Dimension controls in the editor since it has no content only the headers, it is difficult to say it us duplicated but the headings are also seen in the Dimension Controls Overview article

## URL of the Page with the Issue

[Dimension controls in the editor](https://wordpress.org/support/?post_type=helphub_article&p=15125181) draft
[Dimension controls overview](https://wordpress.org/support/article/dimension-controls-overview/)

## Section of Page with the issue

The full article

## Why is this a problem?

duplicated content

## Suggested Fix

- [ ] review if article is duplicated
- [ ] update content if needed on live article
- [ ] delete draft, if needed.
