### ISSUE TITLE
[HelpHub] FAQ's review content

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#426]
## Issue Description

there are several FAQ pages that need content review and decide if we keep them, move them to DevHub or delete them.

## URL of the Page with the Issue

- [ ] [FAQ Working with WordPress](https://wordpress.org/support/article/faq-working-with-wordpress/)
- [ ] [FAQ installation](https://wordpress.org/support/article/faq-installation/)
- [ ] [FAQ troubleshooting](https://wordpress.org/support/article/faq-troubleshooting/)
- [ ] [FAQ troubleshooting 2](https://wordpress.org/support/?post_type=helphub_article&p=10776324) draft
- [ ] [FAQ my site was hacked](https://wordpress.org/support/article/faq-my-site-was-hacked/) 
- [ ] [I make changes and nothing happens](https://wordpress.org/support/article/i-make-changes-and-nothing-happens/)

## Section of Page with the issue

Full articles

## Why is this a problem?

Is the content helpful to end-users?

## Suggested Fix

Review content and remove any developer jargon or links

**Comment by zzap** [comment]
------------------------------------

## Needs updating:

---------------------------------------------------------

### How long is the release cycle of WordPress?

A major release of WordPress happens every 6 months or so. Suggest and vote on ideas for future releases at [the WordPress Extend Ideas site](https://wordpress.org/ideas/).

Also refer [WordPress Versions](https://codex.wordpress.org/WordPress%20Versions) for the chronologically listed versions of WordPress along with the Change Log information on new features and improvements in each version. There are the future releases and links to their respective milestones in the bug tracker.

------------------------------------------------------------------

### Why is there no Page Template option when writing or editing a Page?

If there is no Page Template option when writing or editing a [Page](https://wordpress.org/support/article/pages/) it may because there is no [template file](https://codex.wordpress.org/Stepping%20Into%20Templates) with the proper structure. For the [Page](https://wordpress.org/support/article/pages/) Template box to be available to assign to a Page there must be a least one template file in your theme that has a structure at the beginning of the template file that looks like this:

```PHP
<?php
/*
Template Name: My Custom Page
*/
?>
```

Create a new PHP file with any name under the theme directory and put above codes into the file. You will see the Page Template box appears that includes “My Custom Page” option in the Page Edit Screen. For more detail about Custom Page Template, refer [Page Templates](https://codex.wordpress.org/Page%20Templates).

**NOTE: The code part should be deleted, as well as everything after the first sentence.**

-----------------------------------------------

### How do I disable comments?

**Screenshot needs to be updated and remove everything after it.**

**Comment by estelaris** [comment]
There is still too much dev jargon on this article
