### ISSUE TITLE
[HelpHub] List block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#460]
Article:  https://wordpress.org/support/article/list-block/

## Updating for 6.1
- [ ]  Add spacing block supports. [43402](https://github.com/WordPress/gutenberg/pull/43402)
- [x]  Add missing typography block supports. [43311](https://github.com/WordPress/gutenberg/pull/43311)
- [ ]  Fix Shift+Arrow partial selection for lists & quote. [42885](https://github.com/WordPress/gutenberg/pull/42885)
- [ ]  Allow x to be merged into wrapper blocks. [42780](https://github.com/WordPress/gutenberg/pull/42780)
- [ ]  Remove quote transforms as removed by Quote v2. [42700](https://github.com/WordPress/gutenberg/pull/42700)
- [ ]  Add forward delete. [42564](https://github.com/WordPress/gutenberg/pull/42564)
- [ ]  Focus new list item added from sibling inserter. [41051](https://github.com/WordPress/gutenberg/pull/41051)
- [ ]  Indent multiple list items. [40991](https://github.com/WordPress/gutenberg/pull/40991)
- [x]  Outdent list item when pressing Backspace at the start. [40962](https://github.com/WordPress/gutenberg/pull/40962)
- [x]  Space to indent list item. [39949](https://github.com/WordPress/gutenberg/pull/39949)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos are up to date
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

**Comment by femkreations** [comment]
Article:  https://wordpress.org/support/article/list-block/

## Updating for 6.1
- [ ]  Add spacing block supports. [43402](https://github.com/WordPress/gutenberg/pull/43402)
- [ ]  Add missing typography block supports. [43311](https://github.com/WordPress/gutenberg/pull/43311)
- [ ]  Fix Shift+Arrow partial selection for lists & quote. [42885](https://github.com/WordPress/gutenberg/pull/42885)
- [ ]  Allow x to be merged into wrapper blocks. [42780](https://github.com/WordPress/gutenberg/pull/42780)
- [ ]  Remove quote transforms as removed by Quote v2. [42700](https://github.com/WordPress/gutenberg/pull/42700)
- [ ]  Add forward delete. [42564](https://github.com/WordPress/gutenberg/pull/42564)
- [ ]  Focus new list item added from sibling inserter. [41051](https://github.com/WordPress/gutenberg/pull/41051)
- [ ]  Indent multiple list items. [40991](https://github.com/WordPress/gutenberg/pull/40991)
- [ ]  Outdent list item when pressing Backspace at the start. [40962](https://github.com/WordPress/gutenberg/pull/40962)
- [ ]  Space to indent list item. [39949](https://github.com/WordPress/gutenberg/pull/39949)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by carolinan** [comment]
I have started working on this.

**Comment by carolinan** [comment]
I believe this update is ready for review (I do not have permission to check the boxes in the first issue).

**Comment by samxmunoz** [comment]
@carolinan - I will review. Thank you!

**Comment by samxmunoz** [comment]
Hi @carolinan - I've checked off the items that have been updated, we're still missing a few things here for the 6.1 updates. 

Let me know if you have any questions! There are some videos in the associated PRs that we can use.

**Comment by carolinan** [comment]
1. Spacing - I added a new but short sentence under the headline "Block settings".
3.  Multiselect -Not sure what to add here, I think this is a bug fix rather than new feature?
4+ 5. Wrapper blocks - The text was updated to
"You can transform the List Block into the Paragraph Block, Heading Block, Quote Block, Columns or Group. You can unwrap list items and replace the list with the individual blocks using the Unwrap option."
_Should it include that the transform to pullquote was removed?_
6. Delete -Not sure what to add here, -bug fix.
8. -Multiple indent. This was added but only as a caption for the video.

- [ ]  Focus new list item added from sibling inserter. https://github.com/WordPress/gutenberg/pull/41051
I'll need to think about this and where to put it some more...

**Comment by samxmunoz** [comment]
Handing off to @femkreations to finish review

**Comment by femkreations** [comment]
Looks good. Thanks @carolinan and @samxmunoz for working on these.
I made the following tweaks
-Updated sidebar screenshots
-Linked to Color, Dimension, and Typography overview pages and removed content from here
-Linked to More options page and removed content from here
- Updated the More rich text controls screenshot and content.
- Changes the heading level for Changelog so it shows properly in the TOC without the bullet.
