### ISSUE TITLE
[HelpHub] Gallery block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#463]
Article: https://wordpress.org/documentation/article/gallery-block/

## Update for 6.3
- [x] Allow dragging-and-dropping images from the inserter to image blocks. [49673](https://github.com/WordPress/gutenberg/pull/49673)
- [x] Replace "Image size" with "Resolution" in image size controls. [49112](https://github.com/WordPress/gutenberg/pull/49112)
- [x] Update Gallery block to use consistent 40px components. [49101](https://github.com/WordPress/gutenberg/pull/49101)
- [x] Add help text to Gallery Image Size control [49074](https://github.com/WordPress/gutenberg/pull/49074)
- [x]  [Inserter - Media tab]: Upload Openverse images when inserted [48501](https://github.com/WordPress/gutenberg/pull/48501)
- [x] add block controls on the inspector [49838](https://github.com/WordPress/gutenberg/pull/49838)

## Update for 6.2
- [x] Add toolbar button to add a caption. [47325](https://github.com/WordPress/gutenberg/pull/47325)

## Updating for 6.1
- [x] Add padding and margin support to the gallery block. [43965](https://github.com/WordPress/gutenberg/pull/43965)
- [ ] Display upload error notices using snackbars. [43946](https://github.com/WordPress/gutenberg/pull/43946)
- [x] Add background color block supports. [43294](https://github.com/WordPress/gutenberg/pull/43294)
- [x] Opt-in to axial (column/row) block spacing controls [41175](https://github.com/WordPress/gutenberg/pull/41175)
- [ ] Include image caption when converting a classic block gallery. [40872](https://github.com/WordPress/gutenberg/pull/40872) 
- [x] Remove redundant block name from "settings" panels [40275](https://github.com/WordPress/gutenberg/pull/40275)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article.

**Comment by alianschiavoncini** [comment]
The Add option has been removed in Toolbar.
New screenshot:
![gallery-toolbar](https://user-images.githubusercontent.com/42210724/201338783-a2579b9b-7e7f-49ac-bef5-fa87f51e4065.png)

The "Add images" paragraph can be removed.

**Comment by Thelmachido** [comment]
Hi @femkreations I believe I have gone throught the list of to-do can you please review?

**Comment by mrfoxtalbot** [comment]
I have moved this issue to the ["Needs Review" column](https://github.com/orgs/WordPress/projects/67/views/11). Please keep in mind to include this step in your process @Thelmachido. 
Thank you!

**Comment by mrfoxtalbot** [comment]
I have reviewed the article myself and adjusted a few things, @Thelmachido:

- Added several missing alt texts
- Replaced a screenshot the "Cog" icon with the "Sidebar" one and updated the wording.
- Converted "bold" paragraphs to H4s to give the article a more semantic structure and to provide a better table of contents. Unless there is some reasons I am unaware of  (@femkreations?) , I would strongly encourage everyone to use actual headings as much as possible.

I am going to mark this one as solved.

**Comment by anandau** [comment]
I am interested in working on this. Please assign me.

**Comment by anandau** [comment]
Hi @zzap 
I couldn't manage to look into this task and will be away from work for the next couple of weeks. You can unassign me from this task for now.

**Comment by zzap** [comment]
Done 👍

**Comment by julia0096** [comment]
I found couple of differences in the new version, screenshots below with explanations:

![Screenshot from 2023-09-14 17-07-54](https://github.com/WordPress/Documentation-Issue-Tracker/assets/136454492/d0d94e87-b3a1-4162-bd27-1f6a6e92a3fc)
Adding the Gallery block via + icon looks a bit different.

![Screenshot from 2023-09-14 17-16-56](https://github.com/WordPress/Documentation-Issue-Tracker/assets/136454492/75a6cec2-da98-48b2-aea8-641231c052b0)
Block Toolbar doesn't have Captions or Add -icons anymore. The Upload / Media Library -buttons have been added below the Toolbar (or at least they don't show in the previous screenshots anywhere).

![Screenshot from 2023-09-14 17-29-26](https://github.com/WordPress/Documentation-Issue-Tracker/assets/136454492/2ece34cb-c7b9-45ec-9384-09af9d87b406)
A screenshot of only the Upload / Media Library section in case it's addition need a separate section to the article.

![Screenshot from 2023-09-14 17-36-48](https://github.com/WordPress/Documentation-Issue-Tracker/assets/136454492/1f04402b-94f6-4665-b213-5a537dee52b3)
A screenshot of only the Toolbar.

![Screenshot from 2023-09-14 17-37-25](https://github.com/WordPress/Documentation-Issue-Tracker/assets/136454492/3d3f4e40-ef20-4ec6-93c8-b84bb2e4ecc9)
When you have uploaded some images, the Toolbar expands. Now the Captions icon is there again, with some completely new buttons, from left to right: Apply duotone filter (the black and white triangle), Align, Captions, Insert link, Crop, Replace.


![Screenshot from 2023-09-14 17-38-34](https://github.com/WordPress/Documentation-Issue-Tracker/assets/136454492/4b779301-8129-42ca-9fdb-44870246f200)
Transform to -menus items are in different order.

**Comment by attekosonen** [comment]
The styles tab formatting has changed and multiple block settings have been moved from settings tab under styles tab:

![Screenshot from 2023-09-14 17-51-54](https://github.com/WordPress/Documentation-Issue-Tracker/assets/108858177/424cef60-4fde-4e23-b5fd-2889749fceed)

**Comment by attekosonen** [comment]
Under "Border" section there seems to be a spelling error:

"The Galley block provides border settings options to add border color, width, and radius."

Should be:

"The Gallery block provides border settings options to add border color, width, and radius."

**Comment by julia0096** [comment]
![Screenshot from 2023-09-14 18-06-04](https://github.com/WordPress/Documentation-Issue-Tracker/assets/136454492/3af94f4a-95ff-4595-a2a2-2f0e97c2df62)
Block Settings: Preview -button has been changed to an icon.

![Screenshot from 2023-09-14 18-07-00](https://github.com/WordPress/Documentation-Issue-Tracker/assets/136454492/72202019-2794-43ef-8c39-81abd112936b)
Colums-settings have a "Image Size" option now.

![Screenshot from 2023-09-14 18-21-55](https://github.com/WordPress/Documentation-Issue-Tracker/assets/136454492/b3136f78-ad7a-4045-a6c0-d391a2009429)
Border settings have a separate color option now.

**Comment by zzap** [comment]
@docs-reviewers, this is ready for /review

**Comment by Leonardus-Nugraha** [comment]
Content updated for 6.3. Closing this issue and moving further updates and discussion for 6.4 updates on [this issue ](https://github.com/WordPress/Documentation-Issue-Tracker/issues/1220)
Thank you for all your contributions!
