### ISSUE TITLE
[HelpHub] Tracking: Updating WP.org Block Documentation

### ISSUE THREAD

**Issue by Thelmachido** [WordPress/Documentation-Issue-Tracker#492]
We will be documenting the new enhancements that have been introduced to blocks with the release of WP 6.1. In summary, the new block settings will consist of new typography, color, dimensions, more options, layout, and border settings. 

This tracking issue will reflect the work that needs to be done in: - 

1. Creating new articles to reflect the above settings
2. We already have an article that reflects the [Dimension settings](https://wordpress.org/support/article/dimension-controls-overview/) and [More Options](https://wordpress.org/support/article/more-options/), we might need to edit those. 
3. Put together a list of all the articles that have Typography, Color, Dimensions, Layout & Border sections in existing user-facing block documentation. 

- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/478
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/479 
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/477
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/476
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/480
- [x] (https://github.com/WordPress/Documentation-Issue-Tracker/issues/526)

### Articles to be updated 

- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/476
- [x] (https://github.com/WordPress/Documentation-Issue-Tracker/issues/526)

### Articles to be revamped 

Review the existing articles and replace the current content under Block settings with links to the newly created pages in Step 1. 

- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/483
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/484
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/485
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/486
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/487

**Comment by femkreations** [comment]
Also adding #480 Border Settings overview. Thanks

Adding this article for reference https://make.wordpress.org/core/2022/09/26/core-editor-improvement-catalyst-for-creativity/

**Comment by femkreations** [comment]
Adding #482 #483 #484 #485 #486 to track the progress of removing these sections from the existing block article pages.

**Comment by Thelmachido** [comment]
Hi @femkreations I have gone over the Theme, Widget, and Design blocks. I've also updated their tracking issues, once that is done maybe we can close this one

**Comment by femkreations** [comment]
Thanks for this update.
