### ISSUE TITLE
Theme handbook: Broken code snippets on "Theme Functions" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#530]
## Issue Description

Some code snippet on https://developer.wordpress.org/themes/basics/theme-functions/ are broken.

## Example of a broken code snippet

<img width="681" alt="Screenshot 2022-10-25 at 18 06 37" src="https://user-images.githubusercontent.com/3323310/197757420-d70732eb-f250-4cec-a644-0f61e82cbcd7.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/themes/basics/theme-functions/

## Section of Page with the issue

- [ ] [Theme Setup](https://developer.wordpress.org/themes/basics/theme-functions/#theme-setup)
- [ ] [Automatic Feed Links](https://developer.wordpress.org/themes/basics/theme-functions/#automatic-feed-links)
- [ ] [Navigation Menus](https://developer.wordpress.org/themes/basics/theme-functions/#navigation-menus)
- [ ] [Load Text Domain](https://developer.wordpress.org/themes/basics/theme-functions/#load-text-domain)
- [ ] [Post Thumbnails](https://developer.wordpress.org/themes/basics/theme-functions/#post-thumbnails)
- [ ] [Post Formats](https://developer.wordpress.org/themes/basics/theme-functions/#post-formats)
- [ ] [Initial Setup Example](https://developer.wordpress.org/themes/basics/theme-functions/#initial-setup-example)
- [ ] [Content Width](https://developer.wordpress.org/themes/basics/theme-functions/#content-width)
- [ ] [Your functions.php File](https://developer.wordpress.org/themes/basics/theme-functions/#your-functions-php-file)

## Why is this a problem?

I reported a similar issue in https://github.com/WordPress/wporg-developer/issues/146, and it turned out the the issue was caused do to formatting the code as `Preformatted` instead of as `Paragraph`.

## Suggested Fix

Changing the code snippet from `Preformatted` to `Paragraph` should solve the broken code snippet.

**Comment by nielslange** [comment]
Closing this issue as all code snippets have been corrected: https://developer.wordpress.org/themes/basics/theme-functions/
