### ISSUE TITLE
Theme handbook: Broken and incorrect formatted code snippets

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#531]
I went through the entire Theme handbook identifying code snippets that are broken or incorrect formatted. This issue aims to keep track of 'em all.

## Broken code snippets

A broken code snippet is a code snippet that is available, but is hard to see. Here's an example of such a code snippet:

<img width="681" alt="Screenshot 2022-10-25 at 18 13 05" src="https://user-images.githubusercontent.com/3323310/197758528-41314cd5-be5f-422b-bf1f-dd00e69e2d15.png">

### Affected pages

- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/529
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/530
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/532
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/533
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/534

### Potential cause and fix

I reported this issue in https://github.com/WordPress/wporg-developer/issues/146, and it turned out the the issue was caused do to formatting the code as `Preformatted` instead of as `Paragraph`. Changing the code snippet from `Preformatted` to `Paragraph` should solve the broken code snippet.

## Incorrect formatted code snippets

An incorrect formatted code snippet is a code snippet that currently has no format, is using a wrong indentation or has some other kind of formatting issue. Here's an example of such a code snippet that does not have formatting and wrong indention:

<img width="693" alt="Screenshot 2022-10-25 at 18 21 30" src="https://user-images.githubusercontent.com/3323310/197759987-668e0929-269e-4917-b0cd-6ee6e810b540.png">

### Affected pages

- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/535
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/536
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/537
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/538
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/539
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/540
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/541
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/542
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/543
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/544
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/545
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/546
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/547
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/548
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/549
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/550
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/551
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/552
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/553
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/554
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/555
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/556
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/557
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/558
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/559
- [x] https://github.com/WordPress/Documentation-Issue-Tracker/issues/560

### Potential cause and fix

These code snippets might have been created before the existence of the Code Syntax Block. Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

## Obsolete space

An obsolete space can either appear below the code snippet or within the code snippet. Here's an example of a code snippet that contains obsolete space:

<img width="682" alt="Screenshot 2022-10-25 at 18 27 35" src="https://user-images.githubusercontent.com/3323310/197761052-5a2a153d-bf63-45c8-84a5-7f8b659812b6.png">

### Affected pages:

- [x] https://developer.wordpress.org/themes/advanced-topics/theme-json/#global-styles-variations
- [x] https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#disabling-template-editor
- [x] https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/

### Potential cause and fix

It seems that obsolete spaces accidentally ended up within some code snippets or under the code snippets block. Simply removing them will resolve this issue.

**Comment by nielslange** [comment]
@zzap I'm closing this issue as all listed issues have been resolved. 😀
