### ISSUE TITLE
Theme handbook: Broken code snippets on "Video" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#533]
## Issue Description

Some code snippet on https://developer.wordpress.org/themes/functionality/media/video/ are broken.

## Example of a broken code snippet

<img width="680" alt="Screenshot 2022-10-25 at 19 40 33" src="https://user-images.githubusercontent.com/3323310/197775453-f516ef65-d7b8-443c-ba78-fd31a0e3744a.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/themes/functionality/media/video/

## Section of Page with the issue

- [x] [Video shortcode](https://developer.wordpress.org/themes/functionality/media/video/#video-shortcode)
- [x] [Loop and Autoplay](https://developer.wordpress.org/themes/functionality/media/video/#loop-and-autoplay)
- [x] [Poster](https://developer.wordpress.org/themes/functionality/media/video/#poster)
- [x] [Width](https://developer.wordpress.org/themes/functionality/media/video/#width)
- [x] [Styling](https://developer.wordpress.org/themes/functionality/media/video/#styling)

## Why is this a problem?

I reported a similar issue in https://github.com/WordPress/wporg-developer/issues/146, and it turned out the the issue was caused do to formatting the code as `Preformatted` instead of as `Paragraph`.

## Suggested Fix

Changing the code snippet from `Preformatted` to `Paragraph` should solve the broken code snippet.

**Comment by nielslange** [comment]
Closing this issue as all code snippets have been corrected: https://developer.wordpress.org/themes/functionality/media/video/
