### ISSUE TITLE
Theme handbook: Incorrect formatted code snippets on "Including CSS & JavaScript" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#538]
## Issue Description

Some code snippet on https://developer.wordpress.org/themes/basics/including-css-javascript/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="681" alt="Screenshot 2022-10-25 at 20 00 34" src="https://user-images.githubusercontent.com/3323310/197779664-06e303f4-b00b-4cfc-8209-95146d22020f.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/themes/basics/including-css-javascript/

## Section of Page with the issue

- [ ] [Stylesheets](https://developer.wordpress.org/themes/basics/including-css-javascript/#stylesheets)
- [ ] [Scripts](https://developer.wordpress.org/themes/basics/including-css-javascript/#scripts)
- [ ] [The Comment Reply Script](https://developer.wordpress.org/themes/basics/including-css-javascript/#the-comment-reply-script)
- [ ] [Combining Enqueue Functions](https://developer.wordpress.org/themes/basics/including-css-javascript/#combining-enqueue-functions)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

**Comment by nielslange** [comment]
Closing this issue as the code snippets have been formatted: https://developer.wordpress.org/themes/basics/including-css-javascript/
