### ISSUE TITLE
Theme handbook: Incorrect formatted code snippets on "Converting customizer settings to block patterns" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#539]
## Issue Description

Some code snippet on https://developer.wordpress.org/themes/block-themes/converting-customizer-settings-to-block-patterns/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="692" alt="Screenshot 2022-10-25 at 20 02 41" src="https://user-images.githubusercontent.com/3323310/197780129-0fc30dc7-5e54-45f0-ada6-6e0a080ef694.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/themes/block-themes/converting-customizer-settings-to-block-patterns/

## Section of Page with the issue

- [ ] [Step 2: Register the block pattern](https://developer.wordpress.org/themes/block-themes/converting-customizer-settings-to-block-patterns/#step-2-register-the-block-pattern)
- [ ] [Step 3: Add the customizer option values to the block pattern](https://developer.wordpress.org/themes/block-themes/converting-customizer-settings-to-block-patterns/#step-3-add-the-customizer-option-values-to-the-block-pattern)
- [ ] [Step 4: Display the block pattern](https://developer.wordpress.org/themes/block-themes/converting-customizer-settings-to-block-patterns/#step-4-display-the-block-pattern)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

**Comment by nielslange** [comment]
Closing this issue as the code snippets have been formatted: https://developer.wordpress.org/themes/block-themes/converting-customizer-settings-to-block-patterns/
