### ISSUE TITLE
Theme handbook: Incorrect formatted code snippets on "Post Template Files" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#540]
## Issue Description

Some code snippet on https://developer.wordpress.org/themes/template-files-section/post-template-files/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="686" alt="Screenshot 2022-10-25 at 20 06 32" src="https://user-images.githubusercontent.com/3323310/197780989-3d8b6ee4-c9fb-4dbc-a96c-e47d51a9bce3.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/themes/template-files-section/post-template-files/

## Section of Page with the issue

- [ ] [Single.php](https://developer.wordpress.org/themes/template-files-section/post-template-files/#single-php)
- [ ] [Archive.php](https://developer.wordpress.org/themes/template-files-section/post-template-files/#archive-php)
- [ ] [Search.php](https://developer.wordpress.org/themes/template-files-section/post-template-files/#search-php)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

**Comment by nielslange** [comment]
Closing this issue as the code snippets have been formatted: https://developer.wordpress.org/themes/template-files-section/post-template-files/
