### ISSUE TITLE
Theme handbook: Incorrect formatted code snippets on "Partial and Miscellaneous Template Files" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#542]
## Issue Description

Some code snippet on https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="691" alt="Screenshot 2022-10-25 at 20 12 58" src="https://user-images.githubusercontent.com/3323310/197782432-5be6a0a1-0354-43e7-888c-280dc55e0a1a.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/

## Section of Page with the issue

- [ ] [Header.php](https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/#header-php)
- [ ] [Footer.php](https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/#footer-php)
- [ ] [404.php](https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/#404-php)
- [ ] [Sidebar.php](https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/#sidebar-php)
- [ ] [Content-{$slug}.php](https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/#content-slug-php)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

**Comment by carolinan** [comment]
Fixed.

**Comment by nielslange** [comment]
Closing this issue as the formatting had been fixed: https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/
