### ISSUE TITLE
Theme handbook: Incorrect formatted code snippets on "Comment Template" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#543]
## Issue Description

Some code snippet on https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/comment-template/ are incorrect formatted.

## URL of the Page with the Issue

- https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/comment-template/

## Section of Page with the issue

- [x] [Simple comments loop](https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/comment-template/#simple-comments-loop)
- [x] [Another Comments.php Example](https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/comment-template/#another-comments-php-example)
- [x] [Template Header](https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/comment-template/#template-header)
- [x] [Comments Title](https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/comment-template/#comments-title)
- [x] [Comment Listing](https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/comment-template/#comment-listing)
- [x] [Comment Pagination](https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/comment-template/#comment-pagination)
- [x] [Comments are closed message.](https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/comment-template/#comments-are-closed-message)
- [x] [The End](https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/comment-template/#the-end)
- [x] [Comments Pagination](https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/comment-template/#comments-pagination)
- [x] [Alternative Comment Template](https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/comment-template/#alternative-comment-template)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

**Comment by nielslange** [comment]
Closing this as all formattings have been corrected: https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/comment-template/
