### ISSUE TITLE
Theme handbook: Incorrect formatted code snippets on "Taxonomy Templates" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#544]
## Issue Description

Some code snippet on https://developer.wordpress.org/themes/template-files-section/taxonomy-templates/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="687" alt="Screenshot 2022-10-25 at 20 18 23" src="https://user-images.githubusercontent.com/3323310/197783708-033cc9a9-d5f7-49c0-a1ce-7eb5a24a9118.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/themes/template-files-section/taxonomy-templates/

## Section of Page with the issue

- [x] [Static Text Above Posts](https://developer.wordpress.org/themes/template-files-section/taxonomy-templates/#static-text-above-posts)
- [x] [Different Text on Some Category Pages](https://developer.wordpress.org/themes/template-files-section/taxonomy-templates/#different-text-on-some-category-pages)
- [x] [Display Text only on First Page of Archive](https://developer.wordpress.org/themes/template-files-section/taxonomy-templates/#display-text-only-on-first-page-of-archive)
- [x] [Excerpts vs. Full Posts](https://developer.wordpress.org/themes/template-files-section/taxonomy-templates/#excerpts-vs-full-posts)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

**Comment by nielslange** [comment]
Closing this issue as all formattings have been corrected: https://developer.wordpress.org/themes/template-files-section/taxonomy-templates/
