### ISSUE TITLE
Theme handbook: Incorrect formatted code snippets on "Conditional Tags" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#545]
## Issue Description

Some code snippet on https://developer.wordpress.org/themes/basics/conditional-tags/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="691" alt="Screenshot 2022-10-25 at 20 23 01" src="https://user-images.githubusercontent.com/3323310/197784803-22e610c7-8c9c-4b1e-9f1b-14d39d930a08.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/themes/basics/conditional-tags/

## Section of Page with the issue

- [x] https://developer.wordpress.org/themes/basics/conditional-tags/
- [x] [A Single Post Page](https://developer.wordpress.org/themes/basics/conditional-tags/#a-single-post-page)
- [x] [A Sticky Post](https://developer.wordpress.org/themes/basics/conditional-tags/#a-sticky-post)
- [x] [A Post Type](https://developer.wordpress.org/themes/basics/conditional-tags/#a-post-type)
- [x] [A Post Type is Hierarchical](https://developer.wordpress.org/themes/basics/conditional-tags/#a-post-type-is-hierarchical)
- [x] [A Post Type Archive](https://developer.wordpress.org/themes/basics/conditional-tags/#a-post-type-archive)
- [x] [A “PAGE” Page](https://developer.wordpress.org/themes/basics/conditional-tags/#a-page-page)
- [x] [Testing for Paginated Pages](https://developer.wordpress.org/themes/basics/conditional-tags/#testing-for-paginated-pages)
- [x] [Testing for Sub-Pages](https://developer.wordpress.org/themes/basics/conditional-tags/#testing-for-sub-pages)
- [x] [Is a Page Template](https://developer.wordpress.org/themes/basics/conditional-tags/#is-a-page-template)
- [x] [A Category Page](https://developer.wordpress.org/themes/basics/conditional-tags/#a-category-page)
- [x] [A Tag Page](https://developer.wordpress.org/themes/basics/conditional-tags/#a-tag-page)
- [x] [A Taxonomy Page](https://developer.wordpress.org/themes/basics/conditional-tags/#a-taxonomy-page)
- [x] [An Author Page](https://developer.wordpress.org/themes/basics/conditional-tags/#an-author-page)
- [x] [A Single Page, Single Post or Attachment](https://developer.wordpress.org/themes/basics/conditional-tags/#a-single-page-single-post-or-attachment)
- [x] [Has An Excerpt](https://developer.wordpress.org/themes/basics/conditional-tags/#has-an-excerpt)
- [x] [Single Post](https://developer.wordpress.org/themes/basics/conditional-tags/#single-post)
- [x] [Check for Multiple Conditionals](https://developer.wordpress.org/themes/basics/conditional-tags/#check-for-multiple-conditionals)
- [x] [Date Based Differences](https://developer.wordpress.org/themes/basics/conditional-tags/#date-based-differences)
- [x] [Variable Sidebar Content](https://developer.wordpress.org/themes/basics/conditional-tags/#variable-sidebar-content)
- [x] [In the theme’s footer.php file](https://developer.wordpress.org/themes/basics/conditional-tags/#in-the-theme-s-footer-php-file)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

**Comment by nielslange** [comment]
Closing this issue as all formattings have been corrected: https://developer.wordpress.org/themes/basics/conditional-tags/
