### ISSUE TITLE
Theme handbook: Incorrect formatted code snippets on "Administration Menus" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#546]
## Issue Description

Some code snippet on https://developer.wordpress.org/themes/functionality/administration-menus/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="688" alt="Screenshot 2022-10-25 at 20 26 41" src="https://user-images.githubusercontent.com/3323310/197785643-4ae5df59-5536-4c6d-993b-18dc054bcc7f.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/themes/functionality/administration-menus/

## Section of Page with the issue

- [x] [Every Plot Needs a Hook](https://developer.wordpress.org/themes/functionality/administration-menus/#every-plot-needs-a-hook)
- [x] [Using Wrapper Functions](https://developer.wordpress.org/themes/functionality/administration-menus/#using-wrapper-functions)
- [x] [Example](https://developer.wordpress.org/themes/functionality/administration-menus/#example)
- [x] [Inserting the Pages](https://developer.wordpress.org/themes/functionality/administration-menus/#inserting-the-pages)
- [x] [Sample Menu Page](https://developer.wordpress.org/themes/functionality/administration-menus/#sample-menu-page)
- [x] [Page Hook Suffix](https://developer.wordpress.org/themes/functionality/administration-menus/#page-hook-suffix)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

**Comment by nielslange** [comment]
Closing this issue as the formattings have been corrected: https://developer.wordpress.org/themes/functionality/administration-menus/
