### ISSUE TITLE
Theme handbook: Incorrect formatted code snippets on "Custom Headers" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#547]
## Issue Description

Some code snippet on https://developer.wordpress.org/themes/functionality/custom-headers/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="688" alt="Screenshot 2022-10-25 at 21 02 48" src="https://user-images.githubusercontent.com/3323310/197794734-03f2aadb-815d-4837-aa7c-9ca3044c2add.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/themes/functionality/custom-headers/

## Section of Page with the issue

- [x] [Custom Header](https://developer.wordpress.org/themes/functionality/custom-headers/#custom-header)
- [x] [Add Custom Header Support to your Theme](https://developer.wordpress.org/themes/functionality/custom-headers/#add-custom-header-support-to-your-theme)
- [x] [Set a custom header image](https://developer.wordpress.org/themes/functionality/custom-headers/#set-a-custom-header-image)
- [x] [Use flexible headers](https://developer.wordpress.org/themes/functionality/custom-headers/#use-flexible-headers)
- [x] [Displaying Custom Header](https://developer.wordpress.org/themes/functionality/custom-headers/#displaying-custom-header)
- [x] [Backwards Compatibility](https://developer.wordpress.org/themes/functionality/custom-headers/#backwards-compatibility)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

**Comment by nielslange** [comment]
Closing this issue as the formattings have been corrected: https://developer.wordpress.org/themes/functionality/custom-headers/
