### ISSUE TITLE
Theme handbook: Incorrect formatted code snippets on "Post Formats" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#549]
## Issue Description

Some code snippet on https://developer.wordpress.org/themes/functionality/post-formats/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="694" alt="Screenshot 2022-10-25 at 21 06 37" src="https://user-images.githubusercontent.com/3323310/197795681-2d9114b4-dcd7-4070-b8d6-2979d63247d6.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/themes/functionality/post-formats/

## Section of Page with the issue

- [x] [Adding Theme Support](https://developer.wordpress.org/themes/functionality/post-formats/#adding-theme-support)
- [x] [Adding Post Type Support](https://developer.wordpress.org/themes/functionality/post-formats/#adding-post-type-support)
- [x] [Using Formats](https://developer.wordpress.org/themes/functionality/post-formats/#using-formats)
- [x] [Suggested Styling](https://developer.wordpress.org/themes/functionality/post-formats/#suggested-styling)
- [x] [Formats in a Child Theme](https://developer.wordpress.org/themes/functionality/post-formats/#formats-in-a-child-theme)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

**Comment by nielslange** [comment]
Closing this issue as the formattings have been corrected: https://developer.wordpress.org/themes/functionality/post-formats/
