### ISSUE TITLE
Theme handbook: Incorrect formatted code snippets on "Sticky Posts" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#550]
## Issue Description

Some code snippet on https://developer.wordpress.org/themes/functionality/sticky-posts/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="685" alt="Screenshot 2022-10-25 at 21 12 12" src="https://user-images.githubusercontent.com/3323310/197797108-debf61e8-73cf-4376-a57d-7e21462811aa.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/themes/functionality/sticky-posts/

## Section of Page with the issue

- [x] [Show Sticky Posts](https://developer.wordpress.org/themes/functionality/sticky-posts/#show-sticky-posts)
- [x] [Don’t Show Sticky Posts](https://developer.wordpress.org/themes/functionality/sticky-posts/#dont-show-sticky-posts)
- [x] [Style Sticky Posts](https://developer.wordpress.org/themes/functionality/sticky-posts/#style-sticky-posts)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

**Comment by nielslange** [comment]
Closing this issue as all formattings have been corrected: https://developer.wordpress.org/themes/functionality/sticky-posts/
