### ISSUE TITLE
Theme handbook: Incorrect formatted code snippets on "Sidebars" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#551]
## Issue Description

Some code snippet on https://developer.wordpress.org/themes/functionality/sidebars/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="679" alt="Screenshot 2022-10-25 at 21 15 03" src="https://user-images.githubusercontent.com/3323310/197797844-901ea516-7f62-4d23-9894-4ca29cdc7579.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/themes/functionality/sidebars/

## Section of Page with the issue

- [x] [Registering a Sidebar](https://developer.wordpress.org/themes/functionality/sidebars/#registering-a-sidebar)
- [x] [Examples](https://developer.wordpress.org/themes/functionality/sidebars/#examples)
- [x] [Example:](https://developer.wordpress.org/themes/functionality/sidebars/#example)
- [x] [Load your Sidebar](https://developer.wordpress.org/themes/functionality/sidebars/#load-your-sidebar)
- [x] [Display Default Sidebar Content](https://developer.wordpress.org/themes/functionality/sidebars/#display-default-sidebar-content)
- [x] [Display Default Widgets](https://developer.wordpress.org/themes/functionality/sidebars/#display-default-widgets)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

**Comment by nielslange** [comment]
Closing this issue as all formattings have been corrected: https://developer.wordpress.org/themes/functionality/sidebars/
