### ISSUE TITLE
Theme handbook: Incorrect formatted code snippets on "Widgets" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#552]
## Issue Description

Some code snippet on https://developer.wordpress.org/themes/functionality/widgets/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="693" alt="Screenshot 2022-10-25 at 21 17 49" src="https://user-images.githubusercontent.com/3323310/197798582-dee73727-4883-40dd-8737-33b0c3ac1b52.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/themes/functionality/widgets/

## Section of Page with the issue

- [ ] [Anatomy of a Widget](https://developer.wordpress.org/themes/functionality/widgets/#anatomy-of-a-widget)
- [ ] [Your Widget Class](https://developer.wordpress.org/themes/functionality/widgets/#your-widget-class)
- [ ] [Registering a Widget](https://developer.wordpress.org/themes/functionality/widgets/#registering-a-widget)
- [ ] [Sample Widget](https://developer.wordpress.org/themes/functionality/widgets/#sample-widget)
- [ ] [Example with a Namespace](https://developer.wordpress.org/themes/functionality/widgets/#example-with-a-namespace)
- [ ] [Special considerations](https://developer.wordpress.org/themes/functionality/widgets/#special-considerations)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

**Comment by nielslange** [comment]
Closing this issue as the formattings have been corrected: https://developer.wordpress.org/themes/functionality/widgets/
