### ISSUE TITLE
Theme handbook: Incorrect formatted code snippets on "Images" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#553]
## Issue Description

Some code snippet on https://developer.wordpress.org/themes/functionality/media/images/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="680" alt="Screenshot 2022-10-25 at 21 19 33" src="https://user-images.githubusercontent.com/3323310/197799021-5cdf2eb3-a365-4845-afea-805f420f450a.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/themes/functionality/media/images/

## Section of Page with the issue

- [x] [Getting img code](https://developer.wordpress.org/themes/functionality/media/images/#getting-img-code)
- [x] [Getting URL of image](https://developer.wordpress.org/themes/functionality/media/images/#getting-url-of-image)
- [x] [Alignments](https://developer.wordpress.org/themes/functionality/media/images/#alignments)
- [x] [Caption](https://developer.wordpress.org/themes/functionality/media/images/#caption)
- [x] [WebP support and default MIME type of sub size image output](https://developer.wordpress.org/themes/functionality/media/images/#webp-support-and-default-mime-type-of-sub-size-image-output)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

**Comment by nielslange** [comment]
Closing this issue as all formattings have been corrected: https://developer.wordpress.org/themes/functionality/media/images/
