### ISSUE TITLE
Theme handbook: Incorrect formatted code snippets on "Galleries" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#554]
## Issue Description

Some code snippet on https://developer.wordpress.org/themes/functionality/media/galleries/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="694" alt="Screenshot 2022-10-25 at 21 22 18" src="https://user-images.githubusercontent.com/3323310/197799681-4c99c24c-339f-4612-a249-0a23db9ba312.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/themes/functionality/media/galleries/

## Section of Page with the issue

- [x] [Gallery shortcode](https://developer.wordpress.org/themes/functionality/media/galleries/#gallery-shortcode)
- [x] [Usage](https://developer.wordpress.org/themes/functionality/media/galleries/#usage)
- [x] [Order](https://developer.wordpress.org/themes/functionality/media/galleries/#order)
- [x] [columns](https://developer.wordpress.org/themes/functionality/media/galleries/#columns)
- [x] [IDs](https://developer.wordpress.org/themes/functionality/media/galleries/#ids)
- [x] [Size](https://developer.wordpress.org/themes/functionality/media/galleries/#size)
- [x] [captiontag](https://developer.wordpress.org/themes/functionality/media/galleries/#captiontag)
- [x] [Link](https://developer.wordpress.org/themes/functionality/media/galleries/#link)
- [x] [Include](https://developer.wordpress.org/themes/functionality/media/galleries/#include)
- [x] [Exclude](https://developer.wordpress.org/themes/functionality/media/galleries/#exclude)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

**Comment by nielslange** [comment]
Closing this issue as all formattings have been corrected: https://developer.wordpress.org/themes/functionality/media/galleries/
