### ISSUE TITLE
Theme handbook: Incorrect formatted code snippets on "The Customizer JavaScript API" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#556]
## Issue Description

Some code snippet on https://developer.wordpress.org/themes/customize-api/the-customizer-javascript-api/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="683" alt="Screenshot 2022-10-25 at 21 26 53" src="https://user-images.githubusercontent.com/3323310/197800911-d2958aec-a61f-4115-a1a0-2de9ba9e4d61.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/themes/customize-api/the-customizer-javascript-api/

## Section of Page with the issue

- [x] [Preview JS and Controls JS](https://developer.wordpress.org/themes/customize-api/the-customizer-javascript-api/#preview-js-and-controls-js)
- [x] [Models for Controls, Sections, and Panels](https://developer.wordpress.org/themes/customize-api/the-customizer-javascript-api/#models-for-controls-sections-and-panels)
- [x] [Relating Controls, Sections, and Panels together](https://developer.wordpress.org/themes/customize-api/the-customizer-javascript-api/#relating-controls-sections-and-panels-together)
- [x] [Contextual Panels, Sections, and Controls](https://developer.wordpress.org/themes/customize-api/the-customizer-javascript-api/#contextual-panels-sections-and-controls)
- [x] [Focusing UI Objects](https://developer.wordpress.org/themes/customize-api/the-customizer-javascript-api/#focusing-ui-objects)
- [x] [Priorities](https://developer.wordpress.org/themes/customize-api/the-customizer-javascript-api/#priorities)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

**Comment by nielslange** [comment]
Closing this issue as the formattings have been corrected: https://developer.wordpress.org/themes/customize-api/the-customizer-javascript-api/
