### ISSUE TITLE
Theme handbook: Incorrect formatted code snippets on "Child Themes" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#558]
## Issue Description

Some code snippet on https://developer.wordpress.org/themes/advanced-topics/child-themes/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="681" alt="Screenshot 2022-10-25 at 21 32 19" src="https://user-images.githubusercontent.com/3323310/197802288-d3be60f9-16ee-4702-850f-3af7429ecfc5.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/themes/advanced-topics/child-themes/

## Section of Page with the issue

- [x] [2. Create a stylesheet: style.css](https://developer.wordpress.org/themes/advanced-topics/child-themes/#2-create-a-stylesheet-style-css)
- [x] [3. Enqueue stylesheet](https://developer.wordpress.org/themes/advanced-topics/child-themes/#3-enqueue-stylesheet)
- [x] [Using functions.php](https://developer.wordpress.org/themes/advanced-topics/child-themes/#using-functions-php)
- [x] [Referencing or Including Other Files](https://developer.wordpress.org/themes/advanced-topics/child-themes/#referencing-or-including-other-files)
- [x] [Enqueueing Styles and Scripts](https://developer.wordpress.org/themes/advanced-topics/child-themes/#enqueueing-styles-and-scripts)
- [x] [RTL Support](https://developer.wordpress.org/themes/advanced-topics/child-themes/#rtl-support)
- [x] [Example: textdomain](https://developer.wordpress.org/themes/advanced-topics/child-themes/#example-textdomain)
- [x] [Example: gettext functions](https://developer.wordpress.org/themes/advanced-topics/child-themes/#example-gettext-functions)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

**Comment by nielslange** [comment]
Closing this issue as the formattings have been corrected: https://developer.wordpress.org/themes/advanced-topics/child-themes/
