### ISSUE TITLE
Theme handbook: Incorrect formatted code snippets on "JavaScript Best Practices" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#559]
## Issue Description

Some code snippet on https://developer.wordpress.org/themes/advanced-topics/javascript-best-practices/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="679" alt="Screenshot 2022-10-25 at 21 34 52" src="https://user-images.githubusercontent.com/3323310/197802911-973ff89a-c6e9-482e-9449-edd7fbaecd7f.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/themes/advanced-topics/javascript-best-practices/

## Section of Page with the issue

- [x] [Using $](https://developer.wordpress.org/themes/advanced-topics/javascript-best-practices/#using)
- [x] [Selectors](https://developer.wordpress.org/themes/advanced-topics/javascript-best-practices/#selectors)
- [x] [Event Handling](https://developer.wordpress.org/themes/advanced-topics/javascript-best-practices/#event-handling)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

**Comment by nielslange** [comment]
Closing this issue as all formattings have been corrected: https://developer.wordpress.org/themes/advanced-topics/javascript-best-practices/
