### ISSUE TITLE
Theme handbook: Incorrect formatted code snippets on "Block patterns" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#560]
## Issue Description

Some code snippet on https://developer.wordpress.org/themes/advanced-topics/block-patterns/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="687" alt="Screenshot 2022-10-25 at 21 38 10" src="https://user-images.githubusercontent.com/3323310/197803790-332dc718-16b3-4ff2-96b9-d66b60db6416.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/themes/advanced-topics/block-patterns/

## Section of Page with the issue

- [x] [Using the patterns/ directory to register patterns](https://developer.wordpress.org/themes/advanced-topics/block-patterns/#using-the-patterns-directory-to-register-patterns)
- [x] [PHP registration of block patterns](https://developer.wordpress.org/themes/advanced-topics/block-patterns/#php-registration-of-block-patterns)
- [x] [Translations (i18n) in patterns](https://developer.wordpress.org/themes/advanced-topics/block-patterns/#translations-i18n-in-patterns)
- [x] [Linking assets (images) – use ](https://developer.wordpress.org/themes/advanced-topics/block-patterns/#linking-assets-images-use-get_theme_file_uri)[get_theme_file_uri()](https://developer.wordpress.org/reference/functions/get_theme_file_uri/)
- [x] [Including custom CSS classes in your patterns](https://developer.wordpress.org/themes/advanced-topics/block-patterns/#including-custom-css-classes-in-your-patterns)
- [x] [Conditionally load patterns when using register_block_pattern()](https://developer.wordpress.org/themes/advanced-topics/block-patterns/#conditionally-load-patterns-when-using-register_block_pattern)
- [x] [Conditionally loading patterns when using patterns/ directory](https://developer.wordpress.org/themes/advanced-topics/block-patterns/#conditionally-loading-patterns-when-using-patterns-directory)
- [x] [Registering a custom pattern category](https://developer.wordpress.org/themes/advanced-topics/block-patterns/#registering-a-custom-pattern-category)
- [x] [Unregister a block pattern category](https://developer.wordpress.org/themes/advanced-topics/block-patterns/#unregister-a-block-pattern-category)
- [x] [Removing or hiding block patterns](https://developer.wordpress.org/themes/advanced-topics/block-patterns/#removing-or-hiding-block-patterns)
- [x] [Including block patterns in block theme templates](https://developer.wordpress.org/themes/advanced-topics/block-patterns/#including-block-patterns-in-block-theme-templates)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.

**Comment by carolinan** [comment]
Fixed.

**Comment by nielslange** [comment]
Closing this issue as all formattings have been fixed: https://developer.wordpress.org/themes/advanced-topics/block-patterns/
