### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "Activation / Deactivation Hooks" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#567]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/plugin-basics/activation-deactivation-hooks/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="682" alt="Screenshot 2022-11-05 at 11 56 16" src="https://user-images.githubusercontent.com/3323310/200101893-7544c0fd-a3b1-463e-81fa-3456356a15e9.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/plugin-basics/activation-deactivation-hooks/

## Section of Page with the issue

- [ ] [Activation](https://developer.wordpress.org/plugins/plugin-basics/activation-deactivation-hooks/#activation)
- [ ] [Deactivation](https://developer.wordpress.org/plugins/plugin-basics/activation-deactivation-hooks/#deactivation)
- [ ] [Example](https://developer.wordpress.org/plugins/plugin-basics/activation-deactivation-hooks/#example)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.
