### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "Best Practices" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#569]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/plugin-basics/best-practices/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="688" alt="Screenshot 2022-11-05 at 12 00 35" src="https://user-images.githubusercontent.com/3323310/200102019-5f8a8179-f7d6-4f3a-86a3-389abb1f7050.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/plugin-basics/best-practices/

## Section of Page with the issue

- [ ] [Example](https://developer.wordpress.org/plugins/plugin-basics/best-practices/#example)
- [ ] [Example](https://developer.wordpress.org/plugins/plugin-basics/best-practices/#example-2)
- [ ] [Folder Structure](https://developer.wordpress.org/plugins/plugin-basics/best-practices/#folder-structure)
- [ ] [Conditional Loading](https://developer.wordpress.org/plugins/plugin-basics/best-practices/#conditional-loading)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.
