### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "Determining Plugin and Content Directories" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#570]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/plugin-basics/determining-plugin-and-content-directories/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="688" alt="Screenshot 2022-11-05 at 12 03 40" src="https://user-images.githubusercontent.com/3323310/200102107-3eef388b-bdd2-4ea2-bb69-ff570ba33482.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/plugin-basics/determining-plugin-and-content-directories/

## Section of Page with the issue

- [ ] [Common Usage](https://developer.wordpress.org/plugins/plugin-basics/determining-plugin-and-content-directories/#common-usage)
- [ ] [Plugins](https://developer.wordpress.org/plugins/plugin-basics/determining-plugin-and-content-directories/#plugins)
- [ ] [Themes](https://developer.wordpress.org/plugins/plugin-basics/determining-plugin-and-content-directories/#themes)
- [ ] [Site Home](https://developer.wordpress.org/plugins/plugin-basics/determining-plugin-and-content-directories/#site-home)
- [ ] [WordPress](https://developer.wordpress.org/plugins/plugin-basics/determining-plugin-and-content-directories/#wordpress)
- [ ] [Multisite](https://developer.wordpress.org/plugins/plugin-basics/determining-plugin-and-content-directories/#multisite)
- [ ] [Constants](https://developer.wordpress.org/plugins/plugin-basics/determining-plugin-and-content-directories/#constants)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.
