### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "Actions" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#576]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/hooks/actions/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="690" alt="Screenshot 2022-11-05 at 12 25 48" src="https://user-images.githubusercontent.com/3323310/200103540-8bfa990b-d187-4a96-9df5-3ddcd45b0f5f.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/hooks/actions/

## Section of Page with the issue

- [ ] [Assign (hook) your callback function](https://developer.wordpress.org/plugins/hooks/actions/#assign-hook-your-callback-function)
- [ ] [Priority](https://developer.wordpress.org/plugins/hooks/actions/#priority)
- [ ] [Number of Arguments](https://developer.wordpress.org/plugins/hooks/actions/#number-of-arguments)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.
