### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "Advanced Topics" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#579]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/hooks/advanced-topics/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="681" alt="Screenshot 2022-11-05 at 12 47 56" src="https://user-images.githubusercontent.com/3323310/200104602-7efaf86d-e189-4ab9-996e-3f69af40c088.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/hooks/advanced-topics/

## Section of Page with the issue

- [ ] [Example](https://developer.wordpress.org/plugins/hooks/advanced-topics/#example)
- [ ] [Determining the Current Hook](https://developer.wordpress.org/plugins/hooks/advanced-topics/#determining-the-current-hook)
- [ ] [Checking How Many Times a Hook Has Run](https://developer.wordpress.org/plugins/hooks/advanced-topics/#checking-how-many-times-a-hook-has-run)
- [ ] [Debugging with the “all” Hook](https://developer.wordpress.org/plugins/hooks/advanced-topics/#debugging-with-the-all-hook)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.
