### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "Top-Level Menus" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#583]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/administration-menus/top-level-menus/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="683" alt="Screenshot 2022-11-05 at 12 59 34" src="https://user-images.githubusercontent.com/3323310/200104969-5fcc2f61-ef5b-418d-bca3-1c5b7bcc935a.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/administration-menus/top-level-menus/

## Section of Page with the issue

- [ ] [Add a Top-Level Menu](https://developer.wordpress.org/plugins/administration-menus/top-level-menus/#add-a-top-level-menu)
- [ ] [Example](https://developer.wordpress.org/plugins/administration-menus/top-level-menus/#example)
- [ ] [Using a PHP File for HTML](https://developer.wordpress.org/plugins/administration-menus/top-level-menus/#using-a-php-file-for-html)
- [ ] [Remove a Top-Level Menu](https://developer.wordpress.org/plugins/administration-menus/top-level-menus/#remove-a-top-level-menu)
- [ ] [Example](https://developer.wordpress.org/plugins/administration-menus/top-level-menus/#example-2)
- [ ] [Form action attribute](https://developer.wordpress.org/plugins/administration-menus/top-level-menus/#form-action-attribute)
- [ ] [Processing the form](https://developer.wordpress.org/plugins/administration-menus/top-level-menus/#processing-the-form)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.
