### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "Sub-Menus" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#584]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/administration-menus/sub-menus/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="686" alt="Screenshot 2022-11-05 at 13 01 03" src="https://user-images.githubusercontent.com/3323310/200105014-e76e69a1-3d02-4e7c-ba0c-3c0c516bfe13.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/administration-menus/sub-menus/

## Section of Page with the issue

- [ ] [Add a Sub-Menu](https://developer.wordpress.org/plugins/administration-menus/sub-menus/#add-a-sub-menu)
- [ ] [Example](https://developer.wordpress.org/plugins/administration-menus/sub-menus/#example)
- [ ] [Submitting forms](https://developer.wordpress.org/plugins/administration-menus/sub-menus/#submitting-forms)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.
