### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "Enclosing Shortcodes" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#586]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/shortcodes/enclosing-shortcodes/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="688" alt="Screenshot 2022-11-05 at 13 31 00" src="https://user-images.githubusercontent.com/3323310/200106246-5a1bd6dc-c8aa-4601-b347-9bb80e744950.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/shortcodes/enclosing-shortcodes/

## Section of Page with the issue

- [ ] [Enclosing Content](https://developer.wordpress.org/plugins/shortcodes/enclosing-shortcodes/#enclosing-content)
- [ ] [Processing Enclosed Content](https://developer.wordpress.org/plugins/shortcodes/enclosing-shortcodes/#processing-enclosed-content)
- [ ] [Shortcode-ception](https://developer.wordpress.org/plugins/shortcodes/enclosing-shortcodes/#shortcode-ception)
- [ ] [Limitations](https://developer.wordpress.org/plugins/shortcodes/enclosing-shortcodes/#limitations)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.
