### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "Using Settings API" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#588]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/settings/using-settings-api/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="689" alt="Screenshot 2022-11-05 at 13 43 10" src="https://user-images.githubusercontent.com/3323310/200106604-5cfc78dd-e4d8-4ad4-89e9-471d2c2ed7fa.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/settings/using-settings-api/

## Section of Page with the issue

- [ ] [Add a Setting](https://developer.wordpress.org/plugins/settings/using-settings-api/#add-a-setting)
- [ ] [Add a Section](https://developer.wordpress.org/plugins/settings/using-settings-api/#add-a-section)
- [ ] [Add a Field](https://developer.wordpress.org/plugins/settings/using-settings-api/#add-a-field)
- [ ] [Example](https://developer.wordpress.org/plugins/settings/using-settings-api/#example)
- [ ] [Getting Settings](https://developer.wordpress.org/plugins/settings/using-settings-api/#getting-settings)
- [ ] [Example](https://developer.wordpress.org/plugins/settings/using-settings-api/#example-2)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.
