### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "Managing Post Metadata" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#591]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/metadata/managing-post-metadata/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="683" alt="Screenshot 2022-11-05 at 14 01 40" src="https://user-images.githubusercontent.com/3323310/200107219-716c662a-64e1-49ef-a5ea-2c5e4eb83f94.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/metadata/managing-post-metadata/

## Section of Page with the issue

- [ ] [Character Escaping](https://developer.wordpress.org/plugins/metadata/managing-post-metadata/#character-escaping)
- [ ] [Workaround](https://developer.wordpress.org/plugins/metadata/managing-post-metadata/#workaround)
- [ ] [Hidden Custom Fields](https://developer.wordpress.org/plugins/metadata/managing-post-metadata/#hidden-custom-fields)
- [ ] 

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.
