### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "Custom Meta Boxes" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#592]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/metadata/custom-meta-boxes/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="687" alt="Screenshot 2022-11-05 at 14 04 08" src="https://user-images.githubusercontent.com/3323310/200107283-e242bdb5-597a-491b-8f7d-8c73b5c7bd45.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/metadata/custom-meta-boxes/

## Section of Page with the issue

- [ ] [Adding Meta Boxes](https://developer.wordpress.org/plugins/metadata/custom-meta-boxes/#adding-meta-boxes)
- [ ] [Getting Values](https://developer.wordpress.org/plugins/metadata/custom-meta-boxes/#getting-values)
- [ ] [Saving Values](https://developer.wordpress.org/plugins/metadata/custom-meta-boxes/#saving-values)
- [ ] [OOP](https://developer.wordpress.org/plugins/metadata/custom-meta-boxes/#oop)
- [ ] [Define a Trigger](https://developer.wordpress.org/plugins/metadata/custom-meta-boxes/#define-a-trigger)
- [ ] [Client Side Code](https://developer.wordpress.org/plugins/metadata/custom-meta-boxes/#client-side-code)
- [ ] [Enqueue Client Side Code](https://developer.wordpress.org/plugins/metadata/custom-meta-boxes/#enqueue-client-side-code)
- [ ] [Server Side Code](https://developer.wordpress.org/plugins/metadata/custom-meta-boxes/#server-side-code)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.
