### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "Term Splitting (WP 4.2)" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#596]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/taxonomies/split-terms-wp-4-2/ use incorrect indents.

## Example of an code snippet with incorrect indents

<img width="682" alt="Screenshot 2022-11-05 at 14 31 05" src="https://user-images.githubusercontent.com/3323310/200108380-58bca98b-c592-44ed-b206-f3812845eac5.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/taxonomies/split-terms-wp-4-2/

## Section of Page with the issue

- [ ] [Term ID stored in an option](https://developer.wordpress.org/plugins/taxonomies/split-terms-wp-4-2/#term-id-stored-in-an-option)
- [ ] [Term ID stored in post meta](https://developer.wordpress.org/plugins/taxonomies/split-terms-wp-4-2/#term-id-stored-in-post-meta)
- [ ] [The wp_get_split_term function](https://developer.wordpress.org/plugins/taxonomies/split-terms-wp-4-2/#the-wp_get_split_term-function)

## Why is this a problem?

While this is not really a problem, it makes the code snippet harder to read.

## Suggested Fix

Indent the code snippet correctly.
