### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "Working with Users" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#597]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/users/working-with-users/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="680" alt="Screenshot 2022-11-05 at 14 33 07" src="https://user-images.githubusercontent.com/3323310/200108466-f9daed63-acaf-4e85-a61c-dbf988edfd17.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/users/working-with-users/

## Section of Page with the issue

- [ ] [Example Create](https://developer.wordpress.org/plugins/users/working-with-users/#example-create)
- [ ] [Insert User](https://developer.wordpress.org/plugins/users/working-with-users/#insert-user)
- [ ] [Example Insert](https://developer.wordpress.org/plugins/users/working-with-users/#example-insert)
- [ ] [Example Update](https://developer.wordpress.org/plugins/users/working-with-users/#example-update)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.
