### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "Working with User Metadata" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#598]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/users/working-with-user-metadata/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="682" alt="Screenshot 2022-11-05 at 14 35 34" src="https://user-images.githubusercontent.com/3323310/200108549-238daa1d-81bb-4b11-ab5e-647a32f1ae85.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/users/working-with-user-metadata/

## Section of Page with the issue

- [ ] [Example Form Field](https://developer.wordpress.org/plugins/users/working-with-user-metadata/#example-form-field)
- [ ] [Add](https://developer.wordpress.org/plugins/users/working-with-user-metadata/#add)
- [ ] [Update](https://developer.wordpress.org/plugins/users/working-with-user-metadata/#update)
- [ ] [Delete](https://developer.wordpress.org/plugins/users/working-with-user-metadata/#delete)
- [ ] [Get](https://developer.wordpress.org/plugins/users/working-with-user-metadata/#get)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.
