### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "Roles and Capabilities" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#599]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/users/roles-and-capabilities/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="689" alt="Screenshot 2022-11-05 at 14 39 05" src="https://user-images.githubusercontent.com/3323310/200109159-3d696ef7-caae-43ba-beac-a6f93471b7dd.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/users/roles-and-capabilities/

## Section of Page with the issue

- [ ] [Adding Roles](https://developer.wordpress.org/plugins/users/roles-and-capabilities/#adding-roles)
- [ ] [Removing Roles](https://developer.wordpress.org/plugins/users/roles-and-capabilities/#removing-roles)
- [ ] [Adding Capabilities](https://developer.wordpress.org/plugins/users/roles-and-capabilities/#adding-capabilities)
- [ ] [Get Role](https://developer.wordpress.org/plugins/users/roles-and-capabilities/#get-role)
- [ ] [User Can](https://developer.wordpress.org/plugins/users/roles-and-capabilities/#user-can)
- [ ] [Current User Can](https://developer.wordpress.org/plugins/users/roles-and-capabilities/#current-user-can)
- [ ] [Example](https://developer.wordpress.org/plugins/users/roles-and-capabilities/#example)
- [ ] [Multisite](https://developer.wordpress.org/plugins/users/roles-and-capabilities/#multisite)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.
