### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "HTTP API" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#600]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/http-api/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="684" alt="Screenshot 2022-11-05 at 14 41 36" src="https://user-images.githubusercontent.com/3323310/200109261-3ed8bfa4-616b-476b-b80a-8050c32247f8.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/http-api/

## Section of Page with the issue

- [ ] [GETting data from an API](https://developer.wordpress.org/plugins/http-api/#getting-data-from-an-api)
- [ ] [GET the body you always wanted](https://developer.wordpress.org/plugins/http-api/#get-the-body-you-always-wanted)
- [ ] [GET the response code](https://developer.wordpress.org/plugins/http-api/#get-the-response-code)
- [ ] [GET a specific header](https://developer.wordpress.org/plugins/http-api/#get-a-specific-header)
- [ ] [GET using basic authentication](https://developer.wordpress.org/plugins/http-api/#get-using-basic-authentication)
- [ ] [POSTing data to an API](https://developer.wordpress.org/plugins/http-api/#posting-data-to-an-api)
- [ ] [HEADing off bandwidth usage](https://developer.wordpress.org/plugins/http-api/#heading-off-bandwidth-usage)
- [ ] [Make any sort of request](https://developer.wordpress.org/plugins/http-api/#make-any-sort-of-request)
- [ ] [Cache an object ( Set a transient )](https://developer.wordpress.org/plugins/http-api/#cache-an-object-set-a-transient)
- [ ] [Get a cached object ( Get a transient )](https://developer.wordpress.org/plugins/http-api/#get-a-cached-object-get-a-transient)
- [ ] [Delete a cached object (Delete a transient)](https://developer.wordpress.org/plugins/http-api/#delete-a-cached-object-delete-a-transient)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.
