### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "AJAX" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#602]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/javascript/ajax/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="684" alt="Screenshot 2022-11-05 at 14 46 37" src="https://user-images.githubusercontent.com/3323310/200109440-fcd030e8-5293-4fd5-8112-d785e215dffd.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/javascript/ajax/

## Section of Page with the issue

- [ ] [Using AJAX with jQuery](https://developer.wordpress.org/plugins/javascript/ajax/#using-ajax-with-jquery)
- [ ] [URL](https://developer.wordpress.org/plugins/javascript/ajax/#url)
- [ ] [Data](https://developer.wordpress.org/plugins/javascript/ajax/#data)
- [ ] [Nonce](https://developer.wordpress.org/plugins/javascript/ajax/#nonce)
- [ ] [Action](https://developer.wordpress.org/plugins/javascript/ajax/#action)
- [ ] [Callback](https://developer.wordpress.org/plugins/javascript/ajax/#callback)
- [ ] [Client Side Summary](https://developer.wordpress.org/plugins/javascript/ajax/#client-side-summary)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.
