### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "Server Side PHP and Enqueuing" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#603]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/javascript/enqueuing/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="688" alt="Screenshot 2022-11-05 at 14 48 50" src="https://user-images.githubusercontent.com/3323310/200109511-ec6027c1-8cba-47ac-8fb6-9e41d4967ad9.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/javascript/enqueuing/

## Section of Page with the issue

- [ ] [Enqueue](https://developer.wordpress.org/plugins/javascript/enqueuing/#enqueue)
- [ ] [Nonce](https://developer.wordpress.org/plugins/javascript/enqueuing/#nonce)
- [ ] [Localize](https://developer.wordpress.org/plugins/javascript/enqueuing/#localize)
- [ ] [AJAX Action](https://developer.wordpress.org/plugins/javascript/enqueuing/#ajax-action)
- [ ] [Data](https://developer.wordpress.org/plugins/javascript/enqueuing/#data)
- [ ] [Other](https://developer.wordpress.org/plugins/javascript/enqueuing/#other)
- [ ] [AJAX Handler Summary](https://developer.wordpress.org/plugins/javascript/enqueuing/#ajax-handler-summary)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.
