### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "Heartbeat API" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#604]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/javascript/heartbeat-api/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="689" alt="Screenshot 2022-11-05 at 14 50 26" src="https://user-images.githubusercontent.com/3323310/200109579-94ffbf6f-6ae1-47d4-b642-820fb5fe4126.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/javascript/heartbeat-api/

## Section of Page with the issue

- [ ] [Sending Data to the Server](https://developer.wordpress.org/plugins/javascript/heartbeat-api/#sending-data-to-the-server)
- [ ] [Receiving and Responding on the Server](https://developer.wordpress.org/plugins/javascript/heartbeat-api/#receiving-and-responding-on-the-server)
- [ ] [Processing the Response](https://developer.wordpress.org/plugins/javascript/heartbeat-api/#processing-the-response)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.
