### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "Scheduling WP Cron Events" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#607]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/cron/scheduling-wp-cron-events/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="685" alt="Screenshot 2022-11-05 at 14 55 35" src="https://user-images.githubusercontent.com/3323310/200109847-6683e4b6-8bf0-4061-a661-dae15a1e5110.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/cron/scheduling-wp-cron-events/

## Section of Page with the issue

- [ ] [Adding the Hook](https://developer.wordpress.org/plugins/cron/scheduling-wp-cron-events/#adding-the-hook)
- [ ] [Scheduling the Task](https://developer.wordpress.org/plugins/cron/scheduling-wp-cron-events/#scheduling-the-task)
- [ ] [Unscheduling tasks](https://developer.wordpress.org/plugins/cron/scheduling-wp-cron-events/#unscheduling-tasks)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.
