### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "Hooking WP-Cron [...]" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#608]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/cron/hooking-wp-cron-into-the-system-task-scheduler/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="679" alt="Screenshot 2022-11-05 at 14 57 38" src="https://user-images.githubusercontent.com/3323310/200109922-9cca9f26-9dac-43a6-b3e3-bae1cc9b782f.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/cron/hooking-wp-cron-into-the-system-task-scheduler/

## Section of Page with the issue

- [ ] [Hooking WP-Cron Into the System Task Scheduler](https://developer.wordpress.org/plugins/cron/hooking-wp-cron-into-the-system-task-scheduler/)
- [ ] [Windows](https://developer.wordpress.org/plugins/cron/hooking-wp-cron-into-the-system-task-scheduler/#windows)
- [ ] [MacOS and Linux](https://developer.wordpress.org/plugins/cron/hooking-wp-cron-into-the-system-task-scheduler/#macos-and-linux)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.
