### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "How to Internationalize Your Plugin" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#610]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="696" alt="Screenshot 2022-11-05 at 15 02 20" src="https://user-images.githubusercontent.com/3323310/200110121-e327baa6-91a9-44ef-b4cf-beacac9b1b42.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/

## Section of Page with the issue

- [x] [Text Domains](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#text-domains)
- [x] [Domain Path](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#domain-path)
- [x] [Basic strings](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#basic-strings)
- [x] [Variables](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#variables)
- [x] [Basic Pluralization](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#basic-pluralization)
- [x] [Pluralization done later](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#pluralization-done-later)
- [x] [Disambiguation by context](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#disambiguation-by-context)
- [x] [Descriptions](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#descriptions)
- [x] [Best Practices for writing strings](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#best-practices-for-writing-strings)
- [x] [Add Text Domain to strings](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#add-text-domain-to-strings)
- [x] [Loading Text Domain](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#loading-text-domain)
- [x] [Plugins on WordPress.org](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#plugins-on-wordpress-org)
- [ ] 

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.
