### ISSUE TITLE
Plugin handbook: Incorrect formatted code snippets on "Internationalization Security" page

### ISSUE THREAD

**Issue by nielslange** [WordPress/Documentation-Issue-Tracker#611]
## Issue Description

Some code snippet on https://developer.wordpress.org/plugins/internationalization/security/ are incorrect formatted.

## Example of an incorrect formatted code snippet

<img width="690" alt="Screenshot 2022-11-05 at 15 04 12" src="https://user-images.githubusercontent.com/3323310/200110181-b46a3cf7-2345-4c83-913c-b89899d5dee8.png">

## URL of the Page with the Issue

- https://developer.wordpress.org/plugins/internationalization/security/

## Section of Page with the issue

- [ ] [Minimum Fields](https://developer.wordpress.org/plugins/plugin-basics/header-requirements/#minimum-fields)
- [ ] [Header Fields](https://developer.wordpress.org/plugins/plugin-basics/header-requirements/#header-fields)
- [ ] [Compile Your Own .mo Binaries](https://developer.wordpress.org/plugins/internationalization/security/#compile-your-own-mo-binaries)

## Why is this a problem?

These code snippets might have been created before the existence of the Code Syntax Block.

## Suggested Fix

Using the same Code Syntax Block, as used for working code snippets such as https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/#adding-block-template-parts-in-classic-themes, should solve this problem.
