### ISSUE TITLE
WordCamp Asia 2023 - Contributor Day

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#650]

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by atachibana** [comment]
No one has been assigned to the following Block Help Page. These are relatively easy to work on, and also the writer can refer to other Block Help pages.

- [ ] [Category Block #461](https://github.com/WordPress/Documentation-Issue-Tracker/issues/461)
- [ ] [Post Date Block #282](https://github.com/WordPress/Documentation-Issue-Tracker/issues/282)
- [ ] [Comment Pagination Block #491](https://github.com/WordPress/Documentation-Issue-Tracker/issues/491)
- [ ] [Site Logo Block #504](https://github.com/WordPress/Documentation-Issue-Tracker/issues/504)
- [ ] [Next Post Block #238](https://github.com/WordPress/Documentation-Issue-Tracker/issues/238)
- [ ] [Previous Post Block #240](https://github.com/WordPress/Documentation-Issue-Tracker/issues/240)
- [ ] [Image Block #278](https://github.com/WordPress/Documentation-Issue-Tracker/issues/278)

**Comment by nouman17610** [comment]
I want to work on these 2 tasks. Please guide me or assign me the work.

https://github.com/WordPress/Documentation-Issue-Tracker/issues/443
https://github.com/WordPress/Documentation-Issue-Tracker/issues/458

**Comment by zzap** [comment]
@nouman17610 are you going to attend WordCamp Asia Contributor Day?

**Comment by nouman17610** [comment]
@zzap Yes, I would attend and contribute virtually.

**Comment by zzap** [comment]
@nouman17610 please comment on those issues so I can assign you to them

**Comment by nouman17610** [comment]
Okay sure, I am doing it right now.

**Comment by femkreations** [comment]
@nouman17610 I've assigned these tasks to you. Thank you

**Comment by nouman17610** [comment]
@zzap @femkreations 
I have completed issue 643 and mentioned the suggested content in the comment.
https://github.com/WordPress/Documentation-Issue-Tracker/issues/643#issuecomment-1424859435

Can I get editing access for the remaining two tasks
https://github.com/WordPress/Documentation-Issue-Tracker/issues/443
https://github.com/WordPress/Documentation-Issue-Tracker/issues/458

It would be convenient to edit the documentation to complete the tasks. 
Thank you.

**Comment by rumejan** [comment]
I'd like to work on [#278](https://github.com/WordPress/Documentation-Issue-Tracker/issues/278)

**Comment by Leonardus-Nugraha** [comment]
@rumejan can you leave a comment on the issue #278? then I can assign you there

**Comment by liewcf** [comment]
Hello from WordCamp Asia Contributor Day
My WP.org username is @lcf

**Comment by knockerscalvin** [comment]
WCAsia Contributor Day 
Wp.org username @aghorizon214
