### ISSUE TITLE
[HelpHub] WordPress Editor

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#678]
Article: https://wordpress.org/documentation/article/wordpress-editor/

## Update for 6.3
- [x] Add <ViewLink> component  [50260](https://github.com/WordPress/gutenberg/pull/50260)
- [x] Display device icon on "preview" and "view" buttons  [50218](https://github.com/WordPress/gutenberg/pull/50218)
- [x] Distraction Free Mode: Don't show the metaboxes  [48947](https://github.com/WordPress/gutenberg/pull/48947)
- [x] Improve "switch to draft" placement [50217](https://github.com/WordPress/gutenberg/pull/50217)
- [x] Add the command center to the post editor [50128](https://github.com/WordPress/gutenberg/pull/50128)
- [x] Updates the behavior of the top toolbar fixed setting [49634](https://github.com/WordPress/gutenberg/pull/49634)
- [x] Update the document title in the template mode of the post editor [50864](https://github.com/WordPress/gutenberg/pull/50864)
- [x] Apply busy status to the publish button in progress and unify button width [48444](https://github.com/WordPress/gutenberg/pull/48444)
- [x]  [Inserter - Media tab]: Upload Openverse images when inserted [48501](https://github.com/WordPress/gutenberg/pull/48501)
- [x] Show a pointer/hint in the settings tab informing the user about the styles tab [47670](https://github.com/WordPress/gutenberg/pull/47670)

## Update for 6.2
- [x] Introduce distraction free mode [41740](https://github.com/WordPress/gutenberg/pull/41740)
- [x] Edit Post: Improve distraction-free mode notices  [45348](https://github.com/WordPress/gutenberg/pull/45348)
- [x] Move document information and outline to list view panel [44788](https://github.com/WordPress/gutenberg/pull/44788)
- [x] Block Inspector: Make Settings tab the default . [47592](https://github.com/WordPress/gutenberg/pull/47592)
- [x] Block Inspector: Avoid advanced panel only settings tab . [47474](https://github.com/WordPress/gutenberg/pull/47474)
- [x] Stabilize the block inspector tabs experiment . [47045](https://github.com/WordPress/gutenberg/pull/47045)
- [x] Add text only mode for block inspector tabs . [46968](https://github.com/WordPress/gutenberg/pull/46968)
- [x] Remove Block Inspector Button . [46709](https://github.com/WordPress/gutenberg/pull/46709)
- [x] Rename appearance tab to styles . [46027](https://github.com/WordPress/gutenberg/pull/46027)
- [x] Only render sidebar tabs possessing items to display . [45991](https://github.com/WordPress/gutenberg/pull/45991)
- [x] Add list view tab for Navigation block et al . [45483](https://github.com/WordPress/gutenberg/pull/45483)
- [x] Split block tools into menu, settings, and appearance tabs . [45005](https://github.com/WordPress/gutenberg/pull/45005)
- [x] Don't show empty reusable tab if not allowed to insert reusable blocks [46922](https://github.com/WordPress/gutenberg/pull/46922)
- [x] Openverse integration [46251](https://github.com/WordPress/gutenberg/pull/46251)
- [x] Replace text in Reusable tab with an icon [45851](https://github.com/WordPress/gutenberg/pull/45851)
- [x] Restore the empty paragraph inserter [45542](https://github.com/WordPress/gutenberg/pull/45542)
- [x] Add media tab [44918](https://github.com/WordPress/gutenberg/pull/44918)
- [x] Rename view to Preview [45074](https://github.com/WordPress/gutenberg/pull/45074)
- [x] Move wordcount to the top of the outline  [46648](https://github.com/WordPress/gutenberg/pull/46648)
- [x] Stabilize the block inspector tabs experiment  [47045](https://github.com/WordPress/gutenberg/pull/47045)
- [x] Block Inspector: Make Settings tab the default [47592](https://github.com/WordPress/gutenberg/pull/47592)

Refer to this [blog post](https://make.wordpress.org/core/2023/03/07/introduction-of-block-inspector-tabs/) for more details on the block inspector

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by annezazu** [comment]
Added in mention of distraction free mode and updated the "more options" screenshot to include it, along with the new settings icon [as part of this effort](https://github.com/WordPress/Documentation-Issue-Tracker/issues/793#issuecomment-1510572022).

**Comment by femkreations** [comment]
Adding 6.3 tasks and moving to the 6.3 board

**Comment by shabnam611** [comment]
I can work on this.

**Comment by Leonardus-Nugraha** [comment]
I'm returning this to the "To do" group, as some updates still need to be done, and some screenshots are outdated. For example, this article still doesn't cover the split block tools to "settings" and "styles"

**Comment by atachibana** [comment]
I triage existing issues before actual writing.

n/a - UI improvement in the template mode
- Update the document title in the template mode of the post editor 50864

n/a - UI improvement when the first trial
- Show a pointer/hint in the settings tab informing the user about the styles tab 47670

n/a - UI improvement for the distraction-free mode
- Edit Post: Improve distraction-free mode notices 45348

n/a - UI improvement for the Block Inspector (Screenshots should be updated)
- Block Inspector: Make Settings tab the default . 47592
- Block Inspector: Avoid advanced panel only settings tab . 47474
- Stabilize the block inspector tabs experiment . 47045
- Add text only mode for block inspector tabs . 46968
- Rename appearance tab to styles . 46027
- Only render sidebar tabs possessing items to display . 45991
- Add list view tab for Navigation block et al . 45483
- Split block tools into menu, settings, and appearance tabs . 45005

n/a - UI improvement for the Block Inserter
- Don't show empty reusable tab if not allowed to insert reusable blocks 46922
- Replace text in Reusable tab with an icon 45851
- Restore the empty paragraph inserter 45542

n/a - UI improvement for the menu
- Remove Block Inspector Button . 46709

**Should be fixed**
- Add the command center to the post editor 50128

Also, the content is very confusing due to multiple editors' revisions. I will fix them.

**Comment by atachibana** [comment]
## The block editor’s workspace
 ...

![Image](https://github.com/user-attachments/assets/23d4325e-dfb9-4054-a6e9-7cf36bf269b4)
Fig. WordPress Block Editor

### The top toolbar

Before you publish your post or page, you will see the following options in the top toolbar.
![Image](https://github.com/user-attachments/assets/8c4c4554-749f-4f9e-b443-6c48192bf0e8)
Fig. Top toolbar before publishing

After the publishing, you will see the following options.
![Image](https://github.com/user-attachments/assets/ca42794d-0e72-4016-a944-183735db5674)
Fig. Top toolbar after publishing

1. View Posts / View Pages: Shows the W icon ... (as is)
2. Toggle block inserter: Shows or Hides block inserter that allows users to add block, patterns or media to your post or page.
3. Tools: Switch ... (as is)
4. Undo and Redo: (as is)
5. Document Overview: It includes List View and Outline.
   List View shows a list of ... (as is)
   Outline shows the post/page details ... (as is)
6. Command Palette: The Command Palette helps you streamline your workflow in the WordPress editor by providing a centralized location to work on various aspects of your site’s design. Click this field, or press Cmd+k on Mac or Ctrl+k on Windows. For more details about Command Palete, refer "Editor Command Palette" https://wordpress.org/documentation/article/site-editor-command-palette/
7. Save draft: Save a ... (as is)
8. View: Views how your post/pages looks (as is)
For more details, refer this page https://wordpress.org/documentation/article/how-to-use-the-preview-function/
9. Zoom out: The Zoom out mode allows users to zoom out to edit and create at the pattern level over granular block editing.
10. Settings: Show or hide the post/page sidebar settings and the block settings.
11. Publish: Make your ... (as is)
12. Options: Open up more options.
13. View Post / View Page: After you publish your post or page, you will see this new option. Opens a new tab where you can see how your post/page looks on the frontend.

### More options
If you click the three dots icon in the top toolbar, additional options are displayed. Here, you can customize your editing experience using various options.

#### View
- Top toolbar: Display or hide ... (as is)
- Distraction free: When enabled, this option ...(as is)
- Spotlight mode: With spotlight mode, all block out ...(as is)
- Fullscreen mode: When enabled, this mode hides the Administration screens user interface.

#### Editor
(as is)

#### Tools
Here, you can learn keyboard shortcuts, copy all content on the post/page, view additional support articles, manage patterns or visit the WordPress block editor welcome guide.

#### Preferences
(as is)

**Comment by atachibana** [comment]
Done 🎉 
https://wordpress.org/documentation/article/wordpress-block-editor/
