### ISSUE TITLE
[HelpHub] List Block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#683]
Article: https://wordpress.org/documentation/article/list-block/

## Updating for 6.3
- [x] Add numbering type selection [51186](https://github.com/WordPress/gutenberg/pull/51186)

## Updating for 6.2
- [x] unwrap inner block when pressing Backspace at start. [45075](https://github.com/WordPress/gutenberg/pull/45075)
- [x] Merge inner blocks if wrappers are equal [43181](https://github.com/WordPress/gutenberg/pull/43181)
- [x] List Item: Adopt typography supports [43312](https://github.com/WordPress/gutenberg/pull/43312)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by ratneshsonar** [comment]
Hi, @femkreations 

Could you please assign this task to me.

**Comment by femkreations** [comment]
Moving this to 6.3 and adding tasks for 6.3. @ratneshsonar Pls let me know if you have any updates or would like to continue working on this one.

**Comment by ratneshsonar** [comment]
Hi, @femkreations I would like to continue to work on this one for WP 6.3.

**Comment by zzap** [comment]
Hello, @ratneshsonar . Any updates on this issue?

**Comment by atachibana** [comment]
## Triage

NA: UI improvements:
- unwrap inner block when pressing Backspace at start. 45075
- Merge inner blocks if wrappers are equal 43181

Already modified:
- List Item: Adopt typography supports 43312

Need to enhance:
- Add numbering type selection 51186 ... Need to modfiy

<hr />

## Block settings
Every block has specific options in the editor sidebar in addition to the options found in the block toolbar. If you do not see the sidebar, click the settings icon next to the Publish or Save button.

![Image](https://github.com/user-attachments/assets/b19f8c88-1f06-4675-979a-0b2fd255f860)


ALT: settings icon

### Unordered list settings
If you choose an unordered list, you can select the symbol style at the beginning of every list item from Styles.

![Image](https://github.com/user-attachments/assets/49346fcf-dd0e-408f-8f8f-91e6106bba27)


This is the example when Checkmark is selected.

![Image](https://github.com/user-attachments/assets/971626fc-46bf-45fd-9fe4-832f2e23abe6)

### Ordered list settings

![Image](https://github.com/user-attachments/assets/f5d52864-1cdc-4fbc-92c0-b190130c0a13)

**List Style**

If you choose an ordered list, you can select the list style from the List Style dropdown.

![Image](https://github.com/user-attachments/assets/15583371-c802-4d63-acc4-f326e30c1584)

This is the example when Uppercase Roman numerals is selected.

![Image](https://github.com/user-attachments/assets/e340ca5a-a9d7-469f-b070-fc043f2a415f)

**Start Value**
You can select the number your list starts at. This is useful if you want your list to start at a number other than 1.

**Reverse order**
You can also reverse the numbers of the list to start at the highest number first.
