### ISSUE TITLE
[HelpHub] Media & Text block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#705]
Article:  https://wordpress.org/documentation/article/media-text-block/

## Update for 6.3
- [ ] Update media and video icons [49523](https://github.com/WordPress/gutenberg/pull/49523)
- [ ] Update alternative text labels and help text. [49416](https://github.com/WordPress/gutenberg/pull/49416)
- [ ] Replace "Image size" with "Resolution" in image size controls. [49112](https://github.com/WordPress/gutenberg/pull/49112)
- [ ] Changes image size description, as it causes confusion. [48478](https://github.com/WordPress/gutenberg/pull/48478)
- [ ] Switch default alignment to none. [48404](https://github.com/WordPress/gutenberg/pull/48404)
- [ ]  [Inserter - Media tab]: Upload Openverse images when inserted [48501](https://github.com/WordPress/gutenberg/pull/48501)
- [ ] add block controls on the inspector [49838](https://github.com/WordPress/gutenberg/pull/49838)

## Update for 6.2
- [x] FocalPointPicker: add new opt-in prop. [45958](https://github.com/WordPress/gutenberg/pull/45958)
- [ ] create undo history when media width is changed [46084](https://github.com/WordPress/gutenberg/pull/46084)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by NewYorkerLaura** [comment]
@femkreations I can take this on for 6.3

**Comment by andreawetzel** [comment]
Closing via https://github.com/WordPress/Documentation-Issue-Tracker/issues/2156
