### ISSUE TITLE
[HelpHub] Color Settings overview

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#707]
Article:  https://wordpress.org/documentation/article/colors-settings-overview/

## Update for 6.3
- [x] Improve color name readability. [50450](https://github.com/WordPress/gutenberg/pull/50450)

## Update for 6.2
- [ ] Remove clearable from link ColorPanel item. [46507](https://github.com/WordPress/gutenberg/pull/46507)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by mujuonly** [comment]
I will take this

**Comment by mujuonly** [comment]
<img width="520" alt="image" src="https://user-images.githubusercontent.com/459367/230034945-945cbdf4-f047-4320-8407-7a03cde9164a.png">

I can see the  **clearable** from link ColorPanel item in WP 6.2. The title is confusing. Could you please clarify.?

**Comment by janmckell** [comment]
I'm working on this - @janmckell

**Comment by janmckell** [comment]
For the heading, [Text and background colors](https://wordpress.org/documentation/article/colors-settings-overview/#text-and-background-colors), the video needed to be updated to replace the video showing the color name and value now below the color picker area.



https://github.com/WordPress/Documentation-Issue-Tracker/assets/84089207/6e9e4849-d1df-4138-80fc-8b3b7aacb8e2



![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/84089207/16f50a79-4a94-464b-94b3-42f6bbf814d1)



There is an additional video in this section where you can see an example of a color combination that is not accessibility friendly, and the editor shows a warning.

For the heading, [Link colors](https://wordpress.org/documentation/article/colors-settings-overview/#link-colors), the video needed to be updated to replace the video showing the color name and value now below the color picker area, but showing this on the 'Link' color settings.



![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/84089207/7ff18f1b-f128-4dcb-b845-88ce4af6e253)

**Comment by georgehieron** [comment]
![Screenshot 2023-09-14 at 17 11 43](https://github.com/WordPress/Documentation-Issue-Tracker/assets/31737701/df77d623-f8c0-40fa-8369-16aafea4e64e)

Updated screenshot showing position of gradient type selector for background colour

**Comment by georgehieron** [comment]
https://github.com/WordPress/Documentation-Issue-Tracker/assets/31737701/eb628eb0-f4d0-43cf-ae4c-e908904bde2a

Updated video showing setting text colour and background colour and highlighting the help message alerting of weak colour contrast

**Comment by georgehieron** [comment]
https://github.com/WordPress/Documentation-Issue-Tracker/assets/31737701/a56c2f54-76ab-45df-a846-5456fab85cba

Updated video showing how to set link text colour and hover colour

**Comment by atachibana** [comment]
I will enhance HelpHub page by above updates and some modifications as followings:
<hr />

- Delete 2nd paragraph, because it is too old description.

## How to access color settings

Colors can be set on a site basis or on a block basis. Setting color on a site basis will affect the color of the entire site.
### How to access color settings for your site

1. From your Administration Screens, Select Appearance > Editor
2. Select Styles
3. Select Colors

### How to access color settings for a single block

1. Select the block you want to modify the color
2. Open the Block Settings sidebar of a block by clicking the Settings icon that is to the right of the Publish or Save buttons.
3. Find the Color section.
4. or, In some blocks (e.g. Group block), the Color section is located in the Styles tab represented by a black and white circle.

![Image](https://github.com/user-attachments/assets/69b5d9be-b30c-4854-82f6-c3a07798268c)
ALT: Color settings of Paragraph block

![Image](https://github.com/user-attachments/assets/89c9c84a-acfe-4274-ab37-cd582df96e0c)
ALT: Color settings of Group block

### Viewing all settings
 
In the Color section,  click on the three-dot menu (also known as an ellipsis) to explore all the color settings that are not visible by default. Note that not every block supports all the color settings.

![Image](https://github.com/user-attachments/assets/b639049c-1de7-4c3f-be3d-ae8d8eb29ed4)
ALT: All color settings

### Resetting all settings

If you make customizations to these settings and want to revert back to the original settings quickly, you can do so by selecting the three-dot menu icon and clicking Reset all (see above figure). This resets the settings and removes all of your changes.

### Text and background colors
(Replace two videos by georgehieron’s one)

### Link colors
(Replace video by georgehieron’s one)

 ### Gradient background colors
(Replace video by georgehieron’s one)

Graident type
(Replace image by georgehieron’s one)
