### ISSUE TITLE
[HelpHub] Site Health screen

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#726]
## Issue Description

Originally reported by @marklchaves (@mlchaves on WordPress.org).

Original comment on HelpHub:

> 1) I might have missed it, but I don’t see anywhere you tell readers where to find the Site Health Page. See this glossary entry I just wrote as an example https://docs.wppopupmaker.com/article/484-popup-maker-glossary-of-terms#system-info
> 
> 2) This doc is also titled Site Health Screen, but you also say Site Health page. I think you should be consistent or say upfront you use those terms interchangeably.
> 
> 3) In the “2. Info:” paragraph, you have 2 spaces after some periods. That’s outdated and inconsistent with the rest of the doc.
> 
> 4) In the “2. Info:” paragraph second sentence, the word “sites” should be singular (“site”).
> 
> Thanks!

## URL of the Page with the Issue
https://wordpress.org/documentation/article/site-health-screen/

## Section of Page with the issue
Beginning and the second paragraph.

## Why is this a problem?
It's unclear where the screen is. Also, other small errors.

## Suggested Fix
- [ ] Add instructions on where to find the screen.
- [ ] Fix inconsistencies between page and screen throughout the article. Keep screen.
- [ ] Delete extra spaces after periods in the Info paragraph.
- [ ] Fix plural in the Info paragraph.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.
