### ISSUE TITLE
Add distraction free writing article

### ISSUE THREAD

**Issue by annezazu** [WordPress/Documentation-Issue-Tracker#793]
## Issue Description

WordPress 6.2 introduces distraction free mode and the current distraction free writing experience is missing this important new feature.

## URL of the Page with the Issue

https://make.wordpress.org/support/user-manual/editors/distraction-free-writing/

## Suggested Fix

Update the doc with distraction free mode references.

Props to @pablohoneyhoney for finding this and noting it.

Unless someone beats me to it, I'll aim to get this updated next week and will report back if I don't.

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by annezazu** [comment]
We also need to likely create a new doc in the official support repo too: https://wordpress.org/search/distraction+free/

Right now though, it seems this pops up pretty highly when searching for distraction free writing. I'll try to tackle both or have it be something we can cross reference.

**Comment by ndiego** [comment]
I want to note that this root URL has multiple out-of-date docs. I wonder if the "user manual" was an old docs resource that was deprecated. Here are a few examples:

- https://make.wordpress.org/support/user-manual/editors/
- https://make.wordpress.org/support/user-manual/editors/visual-editor/
- https://make.wordpress.org/support/user-manual/editors/distraction-free-writing/

There does not appear to be a direct way to access this "user manual" without a direct URL. Perhaps a solution would be to de-index the pages and/or remove them entirely. I know removing pages is generally not advised, though.

**Comment by annezazu** [comment]
Great point. I'm not sure either. Curious to hear from others and am happy to update this only to have it deprecated later :). Worst case, it can all be used for a Support Article.

**Comment by annezazu** [comment]
Noting a discussion with @Clorith in Make Slack: https://wordpress.slack.com/archives/C02RQC6RW/p1681491802504319 TLDR: likely can be deprecated and redirected. I'll aim for a new doc we can redirect to at least :)

**Comment by annezazu** [comment]
Because there are quite a few tasks here, here's what I'm planning to do. I welcome help! 
- [ ] Publish support article for distraction free mode, taking inspiration from the [format of the List View article](https://wordpress.org/documentation/article/list-view/).
- [ ] Update https://wordpress.org/documentation/article/wordpress-block-editor/ to include a mention to distraction free mode and link to new article as mentioned here: https://github.com/WordPress/Documentation-Issue-Tracker/issues/678
- [ ] Update https://wordpress.org/documentation/article/working-with-blocks/ to include a mention to distraction free mode and link to new article as mentioned here: https://github.com/WordPress/Documentation-Issue-Tracker/issues/464
- [ ] When all of that is done, redirect https://make.wordpress.org/support/user-manual/editors/distraction-free-writing/ to the new distraction free article. 

Note: using the phrasing ["Distraction Free mode" pulled from the 6.2 release announcement for consistency](https://wordpress.org/news/2023/03/dolphy/).

**Comment by annezazu** [comment]
@Clorith mind redirecting https://make.wordpress.org/support/user-manual/editors/distraction-free-writing/ to https://wordpress.org/documentation/article/distraction-free-mode/ and checking off the above when done? I'll note this in slack as well in case this doesn't notify you <3

**Comment by mrfoxtalbot** [comment]
I think that the current article is still relevant considering that the Classic Editor plugin has 5M+ active installs. I have gone ahead and added a notice to the original article explaining it is about the classic editor and linking to the new one.

> This support article is about the classic editor. If you are using the [new block editor](https://wordpress.org/support/forum-user-guide/block-editor/), you can learn about the Distraction Free writing mode [here](https://wordpress.org/documentation/article/distraction-free-mode/#how-distraction-free-mode-works).

What do you think @Clorith, @annezazu?

**Comment by annezazu** [comment]
I don't have enough historical knowledge of this section of the Make Support site to give an informed opinion. From what was shared in slack, it seems like these pages were precursors to the support site. As an alternative, what if we redirected but still shared links to using the classic editor in the new doc? I'd rather we have folks land in the official support docs from a search engine than a dead end.
