### ISSUE TITLE
Theme Handbook Overhaul (Tracking Ticket)

### ISSUE THREAD

**Issue by justintadlock** [WordPress/Documentation-Issue-Tracker#816]
In April, there was a proposal to overhaul the [WordPress Theme Handbook](https://developer.wordpress.org/themes) with a new structure and learning pathways for theme creators. April 28 was the deadline for feedback on the proposal. After two meetings and an open discussion, we have an outline that we can begin working from.

To reference the progress on this project, visit the following docs and posts:

- [Handbook Outline](https://docs.google.com/document/d/1w1P7j8nX2AsibExh70pX7Y-248XTTdWj7YNkMgMGOyw/edit#heading=h.q33211bhwuly) (Google Doc)
- [Theme Handbook Overhaul Proposal](https://make.wordpress.org/themes/2023/04/04/theme-handbook-overhaul-proposal/)
- [Themes Team Meeting Notes](https://make.wordpress.org/themes/2023/04/12/themes-team-meeting-notes-april-11-2023/) (April 11, 2023)

## Tracking Issues

This is an overall tracking ticket for the project. The following list should be updated to link to specific tickets as they are created. The list may also be amended as this project progresses. Note that some pages already exist and merely need to be moved or potentially updated.

- [ ] **Welcome to the Theme Handbook**
- [ ] **Chapter 1: Getting Started**
	- [ ] Chapter Landing Page
	- [ ] What is a theme?
	- [ ] Who is this handbook for?
	- [ ] Reading this handbook
	- [ ] Tools and setup
	- [ ] Quick-start guide
- [ ] **Chapter 2: Core Concepts**
	- [ ] Chapter Landing Page
	- [ ] Theme structure
	- [ ] Main stylesheet (style.css)
	- [ ] Templates
	- [ ] Custom functionality
	- [ ] Including assets
	- [ ] Global settings and styles (theme.json)
	- [ ] Tools and resources
- [ ] **Chapter 3: Global Settings and Styles**
	- [ ] Chapter Landing Page
	- [ ] Introduction to theme.json
	- [ ] Settings
		- [ ] Typography
		- [ ] Spacing
		- ...
	- [ ] Styles
	- [ ] Registering template parts
	- [ ] Style variations
	- [ ] Reference table
- [ ] **Chapter 4: Templates**
	- [ ] Chapter Landing Page
	- [ ] Introduction to templates
	- [ ] Templates
	- [ ] Template parts
- [ ] **Chapter 5: Features**
	- [ ] Chapter Landing Page
	- [ ] Block patterns
	- [ ] Block style variations
	- [ ] Block stylesheets
	- [ ] Block variations
	- [ ] Starter content
- [ ] **Chapter 6: Classic Themes**
	- [ ] Chapter Landing Page
	- [ ] Your first theme
	- [ ] Linking to theme files and directories
	- [ ] Templates
	- [ ] The Loop
	- [ ] Template tags
	- [ ] Conditional tags
	- [ ] Theme functionality
	- [ ] Theme options / the Customizer
	- [ ] Plugin API hooks
- [ ] **Chapter 7: Advanced Topics**
	- [ ] Chapter Landing Page
	- [ ] Internationalization
	- [ ] Child themes
	- [ ] Privacy
	- [ ] Testing
	- [ ] Debugging
	- [ ] Front-end validation
	- [ ] Security
	- [ ] Publishing themes
- [ ] **Chapter 8: Accessibility**
	- [ ] Chapter Landing Page
	- [ ] Principles of accessibility
	- [ ] Block themes
	- [ ] Resources
- [ ] **Chapter 9: Guides**
	- [ ] Chapter Landing Page
	- [ ] Migrating a classic theme to blocks
	- [ ] UI best practices
	- [ ] JavaScript best practices
- [ ] **Contributing**

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by justintadlock** [comment]
There was a new page recently published on Theme Security: https://developer.wordpress.org/themes/theme-security/theme-security-issues/

This would fit into the upcoming Security page from this outline, but I think some of that needs to be added as part of the split/move to the Make Themes handbook (particularly, things that are specific to the DotOrg directory).

**Comment by justintadlock** [comment]
@javiercasares - I'd love to have a dedicated GitHub repo for managing this. It would save a lot of headaches with moving content around. It's something @richtabor and I recently discussed that would help contributors keep things updated.

I'm personally fine helping to move the content over to Markdown in a repo, and we can certainly start drafting upcoming docs in Markdown.

CC: @kafleg, @carolinan - Thoughts?

**Comment by javiercasares** [comment]
We've been working on this with @zzap for some projects (The Advanced Administration, a year ago, the Plugins with the plugins team a couple of months ago -working on finishing the transition-), so, it's a good opportunity to plan it.

There are 2 good things behind this:
- autosync with the developer site (everything in the "main" will be synced automatically every 15 minutes
- start working on the internationalization project, so we can have all the documentation in a lot of languages.

**Comment by justintadlock** [comment]
@javiercasares - You mentioned a pending ticket. Can you share that link? That'd probably be the best place to discuss anything we need to do on our end. And I can update the instructions in this ticket for drafting new docs when this moves forward.

For existing Google Docs, there's not many that would need to be moved to Markdown. It's just the open tickets above (under the Classic Themes and Advanced Topics sections). All of the other closed tickets have now been moved to develop.wordpress.org/themes.

**Comment by javiercasares** [comment]
- [DevHub Plugins Team (developer.wordpress.org/plugins) Handbook sync](https://meta.trac.wordpress.org/ticket/7361)
- [Plugins Team (make.wordpress.org/plugins) Handbook sync](https://meta.trac.wordpress.org/ticket/7358)

**Comment by t-hamano** [comment]
It would be great if the theme handbook pages were managed in a GitHub repository.

The Japanese community has published [Japanese versions of some handbooks](https://ja.wordpress.org/team/handbook/), but the flow varies greatly depending on whether the original repository is managed on GitHub or not.

- If it is managed on GitHub (such as the plugin handbook): Fork the repository, comment out the original text, and add the Japanese translation below it ([example](https://github.com/jawordpressorg/developer-plugins-handbook/blob/c5d5f9360a21cf65a3bdb4159a9002411b69d95b/index.md#L7-L11)). This makes it easier to detect differences when merging updates made upstream.
- If it is not managed on GitHub: Use a tool called [wp-handbook-converter](https://github.com/mirucon/wp-handbook-converter) to parse the handbook pages and convert them to markdown. This mostly works, but manual adjustments may be required.

**Comment by justintadlock** [comment]
@t-hamano I'd love that too. Here's the relevant ticket: https://meta.trac.wordpress.org/ticket/7520

**Comment by t-hamano** [comment]
Thank you. Unfortunately, that is certainly true 😅
