### ISSUE TITLE
Issues Triage May 30, 2023

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#844]
Issues we discussed and assigned.

### Ready to publish
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/240 - @Leonardus-Nugraha 

### Todo
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/498 - @sagargurnani
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/291 - @femkreations 
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/289 - @jomarieminney
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/278 - @aurooba 
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/462 - @jomarieminney
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/307 
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/300 - @shabnam611
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/293
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/282

### Ready to publish
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/271 - @Leonardus-Nugraha

### Ready to publish 
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/715 - @jomarieminney

## General
- [ ] https://github.com/WordPress/Documentation-Issue-Tracker/issues/427 - @shabnam611

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.
