### ISSUE TITLE
[HelpHub]: Site Editor

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#933]
Article: https://wordpress.org/documentation/article/site-editor/

### General
- [ ] Change "Home" template name to "Blog home". [52048](https://github.com/WordPress/gutenberg/pull/52048)
- [ ] Site editor: only show view site link in view mode. [51279](https://github.com/WordPress/gutenberg/pull/51279)
- [ ] Update the bottom sticky section in the site editor details panel. [51274](https://github.com/WordPress/gutenberg/pull/51274)
- [ ] Disable block supports derived design tools when Blocking Editing Mode is not default. [50912](https://github.com/WordPress/gutenberg/pull/50912)
- [ ] Tweak edit site resizable frame handle. [50878](https://github.com/WordPress/gutenberg/pull/50878)
- [ ] Directly save if only changing current context. [50567](https://github.com/WordPress/gutenberg/pull/50567)
- [ ] Add view site link to site editor nav. [50420](https://github.com/WordPress/gutenberg/pull/50420)
- [ ] Update the document title in the site editor to open the command tool. [50369](https://github.com/WordPress/gutenberg/pull/50369)
- [ ] Add a command center to the site editor. [49330](https://github.com/WordPress/gutenberg/pull/49330) 
- [ ] Add support for hiding breadcrumbs in the Site Editor [49518](https://github.com/WordPress/gutenberg/pull/49518)
- [ ] Hide navigation screen in site editor [49043](https://github.com/WordPress/gutenberg/pull/49043)
- [ ] Add descriptions to all panels in the Site Editor's dark side [48739](https://github.com/WordPress/gutenberg/pull/48739)
- [ ] Adds a global save button to the site editor. [47142](https://github.com/WordPress/gutenberg/pull/47142))
- [ ] update the edit button. [48584](https://github.com/WordPress/gutenberg/pull/48584)
- [ ] Add back link to Design heading in site editor navigation to return to Dashboard. [47950](https://github.com/WordPress/gutenberg/pull/47950)
- [ ] Append template type and name to the site editor page title [47855](https://github.com/WordPress/gutenberg/pull/47855)
- [ ] Update the Save Button label when you're previewing a theme [51361](https://github.com/WordPress/gutenberg/pull/51361)
- [ ] Add Library for Template Parts & Patterns Management [51078](https://github.com/WordPress/gutenberg/pull/51078)

### Patterns
- [ ] Rename Library to Patterns. [52102](https://github.com/WordPress/gutenberg/pull/52102)

### Pages
- [ ] Add the pages menu to the site editor [50463](https://github.com/WordPress/gutenberg/pull/50463)
- [ ] Refer [this PR for Content Editing in the Site Editor](https://github.com/WordPress/gutenberg/pull/44461)

### Templates
- [ ] Add template actions in site editor navigation sidebar. [51054](https://github.com/WordPress/gutenberg/pull/51054)
- [ ] Update the add template menu. [50595](https://github.com/WordPress/gutenberg/pull/50595)
- [ ] Add a nested level when selecting templates or template parts [47777](https://github.com/WordPress/gutenberg/pull/47777)
- [ ] Append template type and name to the site editor page title [47855](https://github.com/WordPress/gutenberg/pull/47855)

### Template Parts
- [ ] Sort template parts by type in navigation screen. [50841](https://github.com/WordPress/gutenberg/pull/50841)
- [ ] Add corresponding area icon to template part menu items. [52102](https://github.com/WordPress/gutenberg/pull/52102)
- [ ] Library: Rename template parts to library. [50769](https://github.com/WordPress/gutenberg/pull/50769)
- [ ] Add a nested level when selecting templates or template parts [47777](https://github.com/WordPress/gutenberg/pull/47777)

### Styles
- [ ] Always show the Styles navigation item. [50573](https://github.com/WordPress/gutenberg/pull/50573)
- [ ] Add link to global styles revisions [51149](https://github.com/WordPress/gutenberg/pull/51149)
- [ ] Add Style Book [50566](https://github.com/WordPress/gutenberg/pull/50566)
- [ ] Styles section to the browse mode sidebar [49014](https://github.com/WordPress/gutenberg/pull/49014)
- [ ] Refer to this PR for [details](https://github.com/WordPress/gutenberg/issues/50429)

### Navigation
- [ ] Navigation in Browse Mode [Refer to this PR](https://github.com/WordPress/gutenberg/issues/50396)

### Command Palette
- [ ] Add a button to open it from the site editor view mode [50425](https://github.com/WordPress/gutenberg/issues/50425)
- [ ] Refer to this [PR for more details](https://github.com/WordPress/gutenberg/issues/48457)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Notes
1. Give an overview of the side bar in the Site Editor for Navigation, Styles, Pages, Templates, and Patterns. Navigation, Pages and Patterns will get a new page covering the details. Issues for the new pages will be linked to this issue.
2. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
3. Some of the PRs have great videos that can be added to the article.

**Comment by femkreations** [comment]
Refer to #936 and #937 for Pages and Patterns detailed pages

**Comment by femkreations** [comment]
Refer to #941 for Navigation detailed page

**Comment by femkreations** [comment]
Refer to #947 for Command center details

**Comment by mrfoxtalbot** [comment]
I'm happy to work on this one too, @femkreations.

**Comment by femkreations** [comment]
Thanks much! I've assigned it to you

**Comment by mrfoxtalbot** [comment]
Ready to go review @femkreations! 

https://wordpress.org/documentation/wp-admin/post.php?post=16357939&action=edit

**Comment by mrfoxtalbot** [comment]
@femkreations, this was ready in August but we might need to review since 6.5 might have introduced some changes. Can you confirm, please? Thank you!
