### ISSUE TITLE
[HelpHub]: Template Editor

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#934]
Article:  https://wordpress.org/documentation/article/template-editor/

## Update for 6.3
- [x] Update the add template menu. [50595](https://github.com/WordPress/gutenberg/pull/50595)
- [x] Sort by the rendered title instead of the slug [50353](https://github.com/WordPress/gutenberg/pull/50353)
- [x] Template editing: improve revert notices [50302](https://github.com/WordPress/gutenberg/pull/50302)
- [x] Add chevrons to the templates and template parts in site editor [50076](https://github.com/WordPress/gutenberg/pull/50076)
- [x] Increase pattern modal dimensions when creating a new template [49722](https://github.com/WordPress/gutenberg/pull/49722)
- [x] Update template descriptions with more detail [48934](https://github.com/WordPress/gutenberg/pull/48934)
- [x] go direct to edit from manage all templates list [48764](https://github.com/WordPress/gutenberg/pull/48764)
- [x] Move "Add Template"'s descriptions to tooltips [48710](https://github.com/WordPress/gutenberg/pull/48710)
- [x] Change "Browse all templates" to "Manage all templates" in template details popover [48496](https://github.com/WordPress/gutenberg/pull/48496)
- [x] Remove TemplateAreas from template details [48490](https://github.com/WordPress/gutenberg/pull/48490)
- [x] Append template type and name to the site editor page title [47855](https://github.com/WordPress/gutenberg/pull/47855)
- [x] Add a nested level when selecting templates or template parts [47777](https://github.com/WordPress/gutenberg/pull/47777)
- [x] Add home to list of new templates [47389](https://github.com/WordPress/gutenberg/pull/47389)
- [x] Add: Patterns to the template start modal [47322](https://github.com/WordPress/gutenberg/pull/47322)
- [x] Modal to choose a start pattern on new templates [46248](https://github.com/WordPress/gutenberg/pull/46248)
- [x]  Template revisions: require 2 revisions before showing the revisions UI [50762](https://github.com/WordPress/gutenberg/pull/50762)
- [x] Prevent the saving button from showing when renaming templates [48399](https://github.com/WordPress/gutenberg/pull/48399)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article.

**Comment by femkreations** [comment]
Refer to this PR for more details https://github.com/WordPress/gutenberg/issues/49597

**Comment by mrfoxtalbot** [comment]
This is a very important article but I am not going to be able to work on it myself.

Sorry for the multiple ping, @Leonardus-Nugraha, @femkreations, @atachibana, @jordesign, do you think could find some time to work on this one?

Thank you!

**Comment by jordesign** [comment]
I've started work on this - beginning with:

> Update the add template menu. https://github.com/WordPress/gutenberg/pull/50595

But also realising that probably the screenshots need to updated consistently throughout the doc

**Comment by jordesign** [comment]
Just noting this is updated all the way through to 'Deleting a Template'. I'll continue on the rest in a few hours.

**Comment by jordesign** [comment]
OK - all updates in place @femkreations  and this is ready for review.
https://wordpress.org/documentation/wp-admin/post.php?post=16358552&action=edit

**Comment by atachibana** [comment]
@jordesign 
Thanks for the great job! I read with great satisfaction the latest documents and images :-) 

Please add a caption to the video in the
- From the templates list in the Template Editor

Reviewer Notes:
The only substantial PR to be reflected in the article is below, which has already been reflected.
- Add home to the list of new templates #47389

All other PRs are related to the UI.

**Comment by jordesign** [comment]
Thanks @atachibana  - that edit is now made (caption added).

**Comment by atachibana** [comment]
@jordesign 
I confirmed the fix.

Thanks one last time.
The article has been modernized in one fell swoop. 🎉
