### ISSUE TITLE
[HelpHub]: List View

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#944]
Article:  https://wordpress.org/documentation/article/list-view/

## Update for 6.3
- [ ]  Append when dragging into collapsed blocks [50936](https://github.com/WordPress/gutenberg/pull/50936)
- [ ] Allow dragging outside the immediate area by passing down a dropZoneElement [50726](https://github.com/WordPress/gutenberg/pull/50726)
- [ ] Allow deleting blocks using keyboard [50422](https://github.com/WordPress/gutenberg/pull/50422)
- [ ] Allow dragging to all levels of the block hierarchy [49742](https://github.com/WordPress/gutenberg/pull/49742)
- [ ] Allow the component to show a custom "more" menu. [48097](https://github.com/WordPress/gutenberg/pull/48097)
- [ ]  [Inserter - Media tab]: Upload Openverse images when inserted [48501](https://github.com/WordPress/gutenberg/pull/48501)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article.

**Comment by NewYorkerLaura** [comment]
@femkreations I can take this on for 6.3

**Comment by CalolanC** [comment]
Hello @Leonardus-Nugraha I hope you are doing well.
This article has already all the items updated to the 6.4 version in other issues:
Convert all reusable blocks to a ‘regular block’: https://github.com/WordPress/Documentation-Issue-Tracker/issues/1221
Check ALT attributes: https://github.com/WordPress/Documentation-Issue-Tracker/issues/1321
Check headings: https://github.com/WordPress/Documentation-Issue-Tracker/issues/1322
Update screenshots: https://github.com/WordPress/Documentation-Issue-Tracker/issues/1323
Update videos: https://github.com/WordPress/Documentation-Issue-Tracker/issues/1324

I think there's no need to add the updates for the 6.3 version. Please let me know if I'm right so this issue can be closed.
/review

**Comment by andreawetzel** [comment]
Closing as part of #2504
