### ISSUE TITLE
[HelpHub]: Cover Block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#945]
Article: https://wordpress.org/documentation/article/cover-block/

## Update for 6.3
- [x] Simplify cover block description. [50355](https://github.com/WordPress/gutenberg/pull/50355)
- [x] Update alternative text labels and help text. [49416](https://github.com/WordPress/gutenberg/pull/49416)
- [x] Add border support using ResizableBox via BlockPopover. [41153](https://github.com/WordPress/gutenberg/pull/41153)
- [x] Add text color block support. [41572](https://github.com/WordPress/gutenberg/pull/41572)
- [ ]  [Inserter - Media tab]: Upload Openverse images when inserted [48501](https://github.com/WordPress/gutenberg/pull/48501)
- [x] add block controls on the inspector [49838](https://github.com/WordPress/gutenberg/pull/49838)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article.

**Comment by yogskr** [comment]
Hi @Leonardus-Nugraha I'd like to work on this issue. Thanks!

**Comment by femkreations** [comment]
@yogskr All yours! Thank you

**Comment by mrfoxtalbot** [comment]
I was reviewing the "[More Options](https://github.com/WordPress/Documentation-Issue-Tracker/issues/713)" issue and landed on this on, I have fixed the headings problem:

- Corrected the heading structure.
- Removed custom sizes and CSS classes that were messing up the appearance of the article.

@Leonardus-Nugraha, let me know if you need help with this one. 

Thank you!

**Comment by emmasophieyoung** [comment]
https://docs.google.com/document/d/1cJa1VXEI7x3SejJnTXYKWu57PiEAP9PTetO5RnVz6Fo/edit#heading=h.bktommumuw9p @Leonardus-Nugraha this review is done too - needs 2nd

**Comment by Leonardus-Nugraha** [comment]
Draft reviewed and article updated!
