### ISSUE TITLE
[HelpHub]: Code block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#946]
Article:  https://wordpress.org/documentation/article/code-block/

## Update for 6.3
- [x] Add wide align support to code block. [50710](https://github.com/WordPress/gutenberg/pull/50710)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article.

**Comment by cgarofalo** [comment]
@femkreations 
Here are the new screenshots for 6.3. Not all of them needed to be updated.

There was an update to the toolbar:
<img width="380" alt="code_block_toolbar" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/45bc26bb-f192-4fdd-a870-d3834c91c7f8">
<img width="380" alt="code_block_toolbar_moving_handles" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/782eee25-933c-4f66-95b7-439ae8022e28">
<img width="380" alt="code_block_toolbar_bold" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/bc7a3a73-e87e-4d47-9f00-a9c4f54e4ab4">
<img width="380" alt="code_block_toolbar_italic" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/19afa18c-d1ae-4c36-b90d-c2ec9164c160">
<img width="380" alt="code_block_toolbar_link" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/aebd9d57-752b-4005-a9dc-106458882661">
The link dialogue has changed:
<img width="369" alt="code_block_url" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/4e010ec8-cacb-4124-bae6-6738333c4844">
The word "Preview" has been replaced with an icon:
<img width="300" alt="code_block_settings" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/42e1e688-fec7-4b45-a0ab-af8b3a220e24">
Transform to has a new toolbar:
<img width="381" alt="code_block_convert" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/d7ce127c-9cc4-4396-8a9e-fa443fce8ddf">
A new width option has been added:
<img width="380" alt="code_block_width" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/eb87fcf9-5009-4552-a3bf-49eff5f27233">

**Comment by cgarofalo** [comment]
More edits:

- "For details, refer to this support article: [Color settings overview](https://wordpress.org/support/article/colors-settings-overview/)" needs to be in a light blue box, to remain consistent with the rest of the article:
<img width="698" alt="Screen Shot 2023-08-01 at 11 27 55 AM" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/380c4008-b6b4-44d3-9838-ebbf8bd8bc7d">

- Add Change Alignment Documentation:

## Change alignment
The _change alignment_ tool lets you align the _Code block_ within the content. You can choose one of the following alignment options:

**None:** Leaves the block alignment as is.

**Wide width:** Increase the block's width beyond the content size.

**Comment by cgarofalo** [comment]
@femkreations @zzap May I be assigned to this issue? Thanks :)

**Comment by cgarofalo** [comment]
New video

https://github.com/WordPress/Documentation-Issue-Tracker/assets/28444463/6fa51096-f087-49c8-841d-231d24914eca

**Comment by cgarofalo** [comment]
@femkreations Ready for review.
