### ISSUE TITLE
[HelpHub]: Site Editor > Command Palette

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#947]
## New page for 6.3
- [x] Create a new article for the Command Center details inside the Site Editor sidebar
- [x] Make sure the URL slug under Permalink is: site-editor-command-palette

## Update for 6.3
- [x] Add contextual commands [50543](https://github.com/WordPress/gutenberg/issues/50543)
- [x] Command center: Update the experiment label  [50467](https://github.com/WordPress/gutenberg/issues/50467)
- [x] Refer to this [PR for more details](https://github.com/WordPress/gutenberg/issues/48457)
- [x] Add global styles related commands [51637](https://github.com/WordPress/gutenberg/issues/51637)
- [x] Update the design of the command center [49681](https://github.com/WordPress/gutenberg/pull/49681)
- [x] Do not show dynamic add new post, add new page commands [50221](https://github.com/WordPress/gutenberg/pull/50221)
- [ ] Allow adding posts and pages with custom titles from the command menu [49893](https://github.com/WordPress/gutenberg/pull/49893)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article.

**Comment by stevenlinx** [comment]
FYI, or to whom it may concern, the name has been officially changed to "Command Palette".
https://wptavern.com/wordpress-6-3-will-introduce-a-command-palette
https://github.com/WordPress/gutenberg/issues/50925#issuecomment-1610044400

**Comment by mrfoxtalbot** [comment]
@femkreations, I am happy to take this one. Thank you!

**Comment by femkreations** [comment]
It is now yours! @mrfoxtalbot

**Comment by mrfoxtalbot** [comment]
This article is ready for revision @femkreations. Thank you! 

https://wordpress.org/documentation/wp-admin/post.php?post=16358338&action=edit

**Comment by Leonardus-Nugraha** [comment]
Reviewed and closed this. Added category and subcategory for the article, and fixing headings formatting (sentence case)
Thanks @mrfoxtalbot !
