### ISSUE TITLE
[HelpHub]: Search Block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#948]
Article:  https://wordpress.org/documentation/article/search-block/

## Update for 6.3
- [x] add button only with expandable input [50487](https://github.com/WordPress/gutenberg/pull/50487)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article.

**Comment by Joe4510** [comment]
@femkreations Can you please assign me this?

**Comment by Joe4510** [comment]
The **Button only** option helps to display only the Search button and hide the search input text field.

![Button-only](https://github.com/WordPress/Documentation-Issue-Tracker/assets/70191331/80a1a05f-7952-4076-a06f-b2ab53fb3f39)

**Comment by Joe4510** [comment]
Article: [](https://wordpress.org/documentation/article/search-block/) has several screenshots that must be updated to reflect the recent changes.

I have compiled it here - [](https://docs.google.com/document/d/19OwUj-5asRqGS8d7g5lby8dfvIjKSS781GD6lWJ4fxs/edit)

**Comment by Joe4510** [comment]
Article: https://wordpress.org/documentation/article/search-block/ has several screenshots that must be updated to reflect the recent changes. 

I have compiled them here - `https://docs.google.com/document/d/19OwUj-5asRqGS8d7g5lby8dfvIjKSS781GD6lWJ4fxs/edit`

**Comment by Joe4510** [comment]
Article: https://wordpress.org/documentation/article/search-block/ has several screenshots that must be updated to reflect the recent changes.

I have compiled them here - https://docs.google.com/document/d/19OwUj-5asRqGS8d7g5lby8dfvIjKSS781GD6lWJ4fxs/edit

**Comment by Joe4510** [comment]
@femkreations Can you please check?
