### ISSUE TITLE
[HelpHub]: More Options

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#949]
Article:   https://wordpress.org/documentation/article/more-options/

## Update for 6.3
- [ ] Tweak copy for block settings menu "Insert..." to "Add..." [50444](https://github.com/WordPress/gutenberg/pull/50444)
- [ ] Tweak remove block label to make it simpler [49529](https://github.com/WordPress/gutenberg/pull/49529)
- [ ] Remove unwrap from transforms and add ungroup to more blocks [50385](https://github.com/WordPress/gutenberg/pull/50385)
- [ ] Reusable blocks: Rename to 'Patterns' and add option to also add a non-synced Pattern  [51144](https://github.com/WordPress/gutenberg/pull/51144)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article.

**Comment by mrfoxtalbot** [comment]
I have updated the screenshots in the "More Options" article as part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/899

@femkreations, could you please take a look and mark this issue as solved if everything looks good?

**Comment by femkreations** [comment]
Thanks @mrfoxtalbot The doc looks great. 

1. Can you pls make sure the headings match the new labels in the menu? 
2. The content under Remove block also pls update to match the label.

**Comment by mrfoxtalbot** [comment]
Done, thank you for spotting that @femkreations! 
- [x]  Can you pls make sure the headings match the new labels in the menu?
- [x] The content under Remove block also pls update to match the label.

I also fixed this
- [x]  Update the "Lock Block" screenshots so they match the 6.3 options.

**Comment by femkreations** [comment]
Awesome work. Thank you. Closing this tracker @mrfoxtalbot
