### ISSUE TITLE
[HelpHub]: Social Icons Block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#953]
Article:  https://wordpress.org/documentation/article/social-icons/

## Update for 6.3
- [ ] Manually set Snapchat label color [51237](https://github.com/WordPress/gutenberg/pull/51237)
- [ ] Update the link and mail block variation's icons [49952](https://github.com/WordPress/gutenberg/pull/49952)
- [ ] Add color classes so icon colors correctly reflect changes in Global Styles [51020](https://github.com/WordPress/gutenberg/pull/51020)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article.

**Comment by NewYorkerLaura** [comment]
@femkreations I can take this on for 6.3

**Comment by estelaris** [comment]
Add to the list of available icons:

- Bluesky
- Discord
- Gravatar
- Threads
- X

Remove

- Skype

**Comment by NewYorkerLaura** [comment]
@andreawetzel feel free to take this over I am no longer contributing to documentation. Happy to have a contributor with time to take this one.

**Comment by andreawetzel** [comment]
Closing as part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/2233 - confirmed icon list is up to date
