### ISSUE TITLE
[HelpHub]: Post Content Block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#954]
Article:  https://wordpress.org/documentation/article/post-content-block/

## Update for 6.3
- [x] Make the Post Content block available as a child of the Query block [51405](https://github.com/WordPress/gutenberg/pull/51405)
- [x] Add Paragraph prompt to Post Content when empty. [50623](https://github.com/WordPress/gutenberg/pull/50623)
- [x] Removes the Post Content block from the inserter in the post editor. [50620](https://github.com/WordPress/gutenberg/pull/50620)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article.

**Comment by christophermhinds** [comment]
I'll take this one.

**Comment by christophermhinds** [comment]
@femkreations a modified version of this article is published. 

Please have someone more experienced from the team review this and let me know if there are any issues or corrections I need to make.

**Comment by slagsbulte** [comment]
I can work on this @femkreations

**Comment by slagsbulte** [comment]
_Add Paragraph prompt to Post Content when empty_

This could be added to the `Post Content Block` section, maybe at the end of it?

Text:

The inner blocks contain an empty paragraph as a template when the Post Content block doesn't already have content in it.

![image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/48683441/efb999ca-1819-4e93-b942-b60993608e31)

Alt text for the image: A screenshot of the empty paragraph in inner block when the block doesn't have any other content in it.

**Comment by sagargurnani99** [comment]
> - Make the Post Content block available as a child of the Query block [51405](https://github.com/WordPress/gutenberg/pull/51405)
> - Add Paragraph prompt to Post Content when empty. [50623](https://github.com/WordPress/gutenberg/pull/50623)
> - Removes the Post Content block from the inserter in the post editor. [50620](https://github.com/WordPress/gutenberg/pull/50620)

I have made the changes suggested by @femkreations in the article for the first two points. The 3rd point needs no documentation as the post content block is removed.

So, this is now ready to be reviewed.

**Comment by atachibana** [comment]
@sagargurnani99
I reviewed and found all but one to be completed.
Unfortunately, Post Content block has been renamed Content block. We need to completely re-edit this page, though this issue is closed for now.
