### ISSUE TITLE
[HelpHub]: Group Block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#955]
Article:  https://wordpress.org/documentation/article/group-block/

## Update for 6.3
- [ ] Remove Quote transform. [50424](https://github.com/WordPress/gutenberg/pull/50424)
- [ ] Allow blocks to be dragged onto it in its placeholder state. [49361](https://github.com/WordPress/gutenberg/pull/49361)
- [ ] Try adding a grid layout type. [49018](https://github.com/WordPress/gutenberg/pull/49018)
- [ ] Remove unwrap from transforms and add ungroup to more blocks [50385](https://github.com/WordPress/gutenberg/pull/50385)
- [ ] Add block variations transformation in block switcher [50139](https://github.com/WordPress/gutenberg/pull/50139)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article.

**Comment by zzap** [comment]
Hey @bobmatyas, thanks for your interest in this issue! 🍪🍪🍪<br>If you have any questions, do not hesitate to ask them in our <a href='https://wordpress.slack.com/archives/C02RP4WU5'>#docs</a> Slack channel.<br>Enjoy and happy contributing ❤️<br><br>P.S. This is bot comment.

**Comment by bobmatyas** [comment]
Add "Transform To" section under "Block Toolbar":

<img width="492" alt="Transform to tool for the Group block" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/45246438/5dbc4f31-cb71-400d-bfba-96cbdaad5327">


> When you click on the Transform button you can convert the Group block into another block type by using the existing content.

> You can transform the *Group* block into a **Row**, **Stack**, **Columns**, or **Cover** block.

**Comment by bobmatyas** [comment]
Changelog entry:

> Added "Transform To" section

**Comment by jcortx** [comment]
@forumfern and myself  (@vitkory) are working on this doc together for contributor day!

@femkreations @Leonardus-Nugraha

**Comment by jcortx** [comment]
Contribution Day Doc Updates:

- Using [Bob's screenshot here ](https://github.com/WordPress/Documentation-Issue-Tracker/issues/955#issuecomment-1691837003)will work with removing quote transform update.

- Allow blocks to be dragged onto it in its placeholder state -[ using Video from PR](https://github.com/WordPress/gutenberg/pull/49361) - we should insert this information/update under [Making a Group](https://github.com/WordPress/Documentation-Issue-Tracker/issues/955#issuecomment-1691837003) or within its own section.

> From the list view, drag Blocks onto the Group Blocks placeholder to add it to an existing group or to create a group.

---

Grid Layout

 - Adding a Group Block image needs to be updated to show Grid
 
 First Image
<img width="349" alt="Screenshot 2024-09-17 at 11 54 37" src="https://github.com/user-attachments/assets/9f29f77b-0982-4b46-b87b-44f54a8c55ad">

 Second Image
<img width="389" alt="Screenshot 2024-09-17 at 11 47 57" src="https://github.com/user-attachments/assets/4ce54ad1-6618-4779-aac5-d1078fde63d1">

- Block Variations image needs to be updated to show Grid
<img width="707" alt="Screenshot 2024-09-17 at 11 51 21" src="https://github.com/user-attachments/assets/7bbe65f0-9ddd-452c-8799-42516c1f7bf3">

> We should likely make a mention that if the user using Grid in Group block  - that they can adjust the maximum column width within the grid or link to Grid user settings. 

Under Adding Content

We chose not to markup this image so that you can use it in other locations of the doc if needed - but this would need tobe marked up to designate how the user sees Settings and Styles
<img width="275" alt="Screenshot 2024-09-17 at 12 03 06" src="https://github.com/user-attachments/assets/cc128360-fed7-4fa4-a48e-a2e14223dd98">

Under Group Block Settings 

This image needs to be updated to show Grid
<img width="275" alt="Screenshot 2024-09-17 at 12 05 02" src="https://github.com/user-attachments/assets/0db36460-90aa-4645-96b8-c29af2500546">

---

Updating Block Toolbar Settings - Words

<img width="275" alt="Screenshot 2024-09-17 at 12 08 06" src="https://github.com/user-attachments/assets/15b0ca27-1a4a-4d2c-bf08-e838032a07e5">

Create a new section for Group Settings or use the More Options settings section to include this image which shows "Ungroup" vs "unwrap". 

---
