### ISSUE TITLE
[HelpHub]: Quote Block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#956]
Article:  https://wordpress.org/documentation/article/quote-block/

## Update for 6.3
- [x] Remove unwrap from transforms and add ungroup to more blocks [50385](https://github.com/WordPress/gutenberg/pull/50385)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article.

**Comment by zzap** [comment]
Hey @bobmatyas, thanks for your interest in this issue! 🍪🍪🍪<br>If you have any questions, do not hesitate to ask them in our <a href='https://wordpress.slack.com/archives/C02RP4WU5'>#docs</a> Slack channel.<br>Enjoy and happy contributing ❤️<br><br>P.S. This is bot comment.

**Comment by bobmatyas** [comment]
Under "Transform To" (  https://wordpress.org/documentation/article/quote-block/#transform-to ) replace the screenshot with:

<img width="372" alt="Transform to tool for the Quote block" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/45246438/76c591b6-2b19-41bb-9a82-4c09a11e6c6b">

Change the text to:

> You can transform the *Quote* block into a **Columns**, **Group**, or **Pullquote** block. You can also change the style of the *Quote* block from **Default** to **Plain**.
