### ISSUE TITLE
[HelpHub]: Site Logo Block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#958]
Article:  https://wordpress.org/documentation/article/site-logo-block/

## Update for 6.3
- [x] Add logo replace flow in Inspector controls. [49992](https://github.com/WordPress/gutenberg/pull/49992)
- [ ] Adjust copy of Site Logo Block [49540](https://github.com/WordPress/gutenberg/pull/49540)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article.

**Comment by ktyfuller604** [comment]
I can work on this one @femkreations

**Comment by ktyfuller604** [comment]
New Introduction video to reflect the change in copy and the new media option in sidebar settings. 

https://d.pr/v/RwdJEi

**Comment by LizaBogatyrev** [comment]
Alt tags for images:
Image 1: 
"Add or replace site logo in the media gallery - block settings view"
https://user-images.githubusercontent.com/38542929/263012678-78fe0bee-d8fa-4122-b473-b501b882bf28.png

Image 2: 
"Add site logo to media gallery - block settings view before media is added"
https://user-images.githubusercontent.com/38542929/263010777-feb7d844-4f99-4fe3-8d08-09ef7c8c1f37.png

Image 3:

"Add site logo to media gallery - block settings view after media has been added"
https://user-images.githubusercontent.com/38542929/263010858-f6605275-e398-4b7f-82e4-cdd0b971232b.png

**Comment by LizaBogatyrev** [comment]
Sentence case check: 
New content: reviewed, all good
Original article: replace current post title "Site Logo Block" with "Site Logo block"

**Comment by LizaBogatyrev** [comment]
Changelog 
2023-09-14
Updated content for WordPress 6.3

**Comment by LizaBogatyrev** [comment]
@zzap Ready to post!

**Comment by sagargurnani99** [comment]
Case check: All good.
Screenshots check: All good
Alt tags check: Tags are in sentence case which is good. But, the tags suggested by you appear a bit lengthy to me. It is just an opinion and #NotABlocker.

@LizaBogatyrev can the quoted text below be a numbered list please instead of a paragraph?
> Click Add media to add an image to the Site Logo block. Once an image has been added, click the image name to replace the image with another in your media gallery, upload a new image, or remove the image by resetting the media.

**Comment by Leonardus-Nugraha** [comment]
Thanks @LizaBogatyrev for your contribution and @sagargurnani99 for reviewing and suggesting improvements!
Content is updated, I've also applied the suggestions from Sagar to make the content in a list format.
