### ISSUE TITLE
[HelpHub]: Pagination Block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#959]
Article:  https://wordpress.org/documentation/article/pagination-block

## Update for 6.3
- [x] allow hiding the label text [50779](https://github.com/WordPress/gutenberg/pull/50779)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article.

**Comment by Rashigupta2999** [comment]
@femkreations I am working on this.

**Comment by femkreations** [comment]
Assigned to you. Thank you!

**Comment by Rashigupta2999** [comment]
I have prepared the draft. Kindly review.
https://docs.google.com/document/d/16ygsJj9KgbcEKQB8JmTUmpjXAR5kjwIu31UmEkHHXaI/edit?usp=sharing

**Comment by anandau** [comment]
All looks good. Just add alt text to images.

**Comment by Leonardus-Nugraha** [comment]
Thanks! article is reviewed and updated, all good!
