### ISSUE TITLE
[HelpHub]: Verse Block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#964]
Article:  https://wordpress.org/documentation/article/verse-block/

## Update for 6.3
- [ ] Adopt border supports [48021](https://github.com/WordPress/gutenberg/pull/48021)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article.

**Comment by femkreations** [comment]
Thanks for the content. Can you pls also add the Border support screenshots and info?  This is missing in the article. Thank you @p14i
