### ISSUE TITLE
[HelpHub]: Embed Block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#971]
Article: https://wordpress.org/documentation/article/embed-block/

## Update for 6.3
- [ ] A margin option is added to the Embeded preview block [39384](https://github.com/WordPress/gutenberg/pull/39384)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article.

**Comment by nith53** [comment]
**Dimension Controls**

The Embed block also has dimension controls located in the **Styles** tab, that allows you to add margins to the embeds preview block.



![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/141323754/8abbde14-143c-4d21-ab18-261436a076ba)

If needed, via the _Margin options_, you can also adjust the various borders of the margin individually.



![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/141323754/2a48a0a3-5062-4c54-b42d-6a7f822a1165)

**Comment by femkreations** [comment]
I've assigned this to you @nith53 Thank you

**Comment by nith53** [comment]
https://docs.google.com/document/d/1VPcjUOq-abdJ_cmUbTJ3CSwaZ0vAMT2wfjQ1qcfNNZs/edit?usp=sharing

The doc contains all the needed updates. Ready for review.

**Comment by atachibana** [comment]
This issue is covered by #2328.
