### ISSUE TITLE
[HelpHub]: Dimension Settings overview

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#973]
Article: https://wordpress.org/documentation/article/dimension-controls-overview/

## Update for 6.3
- [x] Spacing: Optimize & condense unlinked spacing controls. [50660](https://github.com/WordPress/gutenberg/pull/50660)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. Some of the PRs have great videos that can be added to the article.
