### ISSUE TITLE
[HelpHub]: Block based Widgets Editor

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#974]
Article:  https://wordpress.org/documentation/article/block-based-widgets-editor/

## Update for 6.3
- [ ] Widget Editor: Update settings icon [51029](https://github.com/WordPress/gutenberg/pull/51029)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article.

**Comment by Joe4510** [comment]
**Widget Editor**

![Widgets Editor](https://github.com/WordPress/Documentation-Issue-Tracker/assets/70191331/1cdcec44-d933-4c92-b599-1738677cae64)

**Comment by Joe4510** [comment]
@femkreations Can you please assign me this?

**Comment by Joe4510** [comment]
Article: https://wordpress.org/documentation/article/block-based-widgets-editor/ has screenshots that must be updated. 

I have compiled them here - https://docs.google.com/document/d/1e0BCCDBPto_7m8KDJ6PmkRQPA8nmiSUKgyGJlUd0fBY/edit

**Comment by Joe4510** [comment]
@femkreations  Can you please check?

**Comment by atachibana** [comment]
#2167 closed this issue.
