### ISSUE TITLE
[HelpHub]: Filters Settings Overview

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#975]
## New page for 6.3
- [x] Create a new article for the Filters Settings Overview.
- [x] Make sure the URL slug under Permalink is: filters-settings-overview

## Update for 6.3
- [x] add block controls on the inspector [49838](https://github.com/WordPress/gutenberg/pull/49838)

## Tasks
Add link to the filters-settings-overview page in the: 
- [x] [Image block](https://wordpress.org/documentation/article/image-block/) page, 
- [x] [Cover block](https://wordpress.org/documentation/article/cover-block/) page,
- [x]  [Gallery block](https://wordpress.org/documentation/article/gallery-block/) page and 
- [ ] [Media block](https://wordpress.org/documentation/article/media-text-block/) page.

## WHY
Create a Filters overview page with the Duotone controls. In the future, the Filters will expand to add more controls, and having the details in one place makes it easier to maintain.

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article.

**Comment by foosantos** [comment]
I'm starting to work on this one now. :)

**Comment by foosantos** [comment]
Hi @femkreations! Could you review this for me?

* I created the page [Filters Settings Overview](https://wordpress.org/documentation/article/filters-settings-overview/).
* I edited [Image Block](https://wordpress.org/documentation/article/image-block/), [Cover Block](https://wordpress.org/documentation/article/cover-block/), and [Gallery Block](https://wordpress.org/documentation/article/gallery-block/) to add this mention and "centralize" about this filter.
* I don't think it is an option for [Media & Text Block](https://wordpress.org/documentation/article/media-text-block/) yet, right? I haven't added mentions about it there.

PS: I have been away from the team for a long time, so I might have missed a few things from it. Please let me know, and I would be happy to edit accordingly.

**Comment by zzap** [comment]
Hey @foosantos, thanks for your interest in this issue! 🍪🍪🍪<br>If you have any questions, do not hesitate to ask them in our <a href='https://wordpress.slack.com/archives/C02RP4WU5'>#docs</a> Slack channel.<br>Enjoy and happy contributing ❤️

**Comment by foosantos** [comment]
(already worked on it, but assigned to me to follow the new workflow)

**Comment by Leonardus-Nugraha** [comment]
Thank @foosantos ! I've reviewed it and made some little edits. All good!
