### ISSUE TITLE
[HelpHub]: Add block variations transformation in block switcher

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#976]
## Update the pages listed below for the following issue
- [ ] Add block variations transformation in block switcher [50139](https://github.com/WordPress/gutenberg/pull/50139)

## List of pages
- [ ] [Stack block page](https://wordpress.org/documentation/article/stack-block/)
- [ ] [Categories block page](https://wordpress.org/documentation/article/post-categories-block/)
- [ ] [Tag block page](https://wordpress.org/documentation/article/post-tags-block/)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by jennydupuy** [comment]
Hi,
The pages:

- [Group Block](https://wordpress.org/documentation/article/group-block/)
- [Row Block](https://wordpress.org/documentation/article/row-block/)

are also concerned by this issue.

**Comment by femkreations** [comment]
Thanks @jennydupuy for chiming in. I have added the issue separately for those two block pages referenced here #955 #699

**Comment by zzap** [comment]
Hey @bobmatyas, thanks for your interest in this issue! 🍪🍪🍪<br>If you have any questions, do not hesitate to ask them in our <a href='https://wordpress.slack.com/archives/C02RP4WU5'>#docs</a> Slack channel.<br>Enjoy and happy contributing ❤️<br><br>P.S. This is bot comment.

**Comment by bobmatyas** [comment]
I made the changes to the group and row blocks on their separate issues:

- https://github.com/WordPress/Documentation-Issue-Tracker/issues/955
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/699

**Comment by bobmatyas** [comment]
For "Categories Block" ( https://wordpress.org/documentation/article/post-categories-block/ ):


<img width="322" alt="Categories-Transform-To" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/45246438/09b1e3b0-4339-4d8e-bd01-e1a269c5d47f">

ALT TEXT: Transform To options in the Categories block

Updated Text:

> Click on the Transform button to convert the Stack block into **Tags**, **Columns**, or **Group** block.

**Comment by bobmatyas** [comment]
For "Post Tags Block" ( https://wordpress.org/documentation/article/post-tags-block/ ):


<img width="330" alt="Tags-Transform-To" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/45246438/f6d0354f-b1af-4c27-8e78-f7f7ed47cd96">


ALT TEXT: Transform To options in the Post Tags block"

Updated Text:

> Click on the Transform button to convert the *Post Tags* block into **Categories**, **Columns**, or **Group** block.

**Comment by andreawetzel** [comment]
The stack block article has been updated: https://wordpress.org/documentation/article/stack-block/
