### ISSUE TITLE
[HelpHub]: Paragraph Block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#978]
Article:  https://wordpress.org/documentation/article/paragraph-block/

## Update for 6.3
- [ ] Footnotes: try with post meta [51201](https://github.com/WordPress/gutenberg/pull/51201)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article.

**Comment by huzaifaalmesbah** [comment]
good work

**Comment by NewYorkerLaura** [comment]
@femkreations I can take this one on for 6.3

**Comment by Zebedeu** [comment]
@femkreations I will work on it in case someone is not working.

**Comment by Zebedeu** [comment]
@zzap is anyone currently working on this?

**Comment by zzap** [comment]
Looks like not. You can take it

**Comment by Zebedeu** [comment]
Instead of the icon, the existing video in the article contains the text 'Preview'.



![Image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/12781593/2cc26171-8bf6-4e5b-94ec-b7eface72e95)

**Comment by Zebedeu** [comment]
- [ ]  Make sure all screenshots are relevant to the latest version
- [ ]  Make sure videos, if any, are up to date
- [X]  Add ALT tags for the images
- [X]  Make sure the headings are in sentence case
- [X]  Convert all reusable blocks to a ‘regular block’.
- [ ]  Update the changelog at the end of the article


The points 3, 4, and 5 are already in compliance.

**Comment by Zebedeu** [comment]
In the following paragraph, it was not mentioned whether the mentioned shortcuts are for MAC or Windows: "_The Paragraph block also supports keyboard shortcuts for text formatting, making creating and customizing content easier. For example, you can convert texts into headings using keyboard shortcuts: Alt + Shift + Number 1-6. The numerical keyboard shortcuts represent Heading 1 to Heading 6. If you want to change them back to texts, press Alt + Shift + 0._"

**Comment by Zebedeu** [comment]
My video proposal
https://github.com/WordPress/Documentation-Issue-Tracker/assets/12781593/e83c2248-e27e-4830-b7a0-0353f1e9e49b

**Comment by zzap** [comment]
@docs-reviewers, this is ready for /review

**Comment by shawnco** [comment]
I'm down to review this

**Comment by shawnco** [comment]
Findings:

The article has a long GIF showing how to use the paragraph block. Would it make more sense for this to be a video? That way readers can re-watch parts they miss, skip parts, etc.

The first image under "Block settings" is outdated

> Additionally, you can add links, inline images, and highlight to the text content.

Should this be "highlights" (plural)?

> The _paragraph_ block provides dimension settings options

Should this say _Paragraph_ to be consistent?

> The “Advanced” tab lets you add HTML anchor

The quotes around Advanced isn't consistent with how other sections of that menu are referenced

**Comment by sagargurnani99** [comment]
@Zebedeu this issue is done with the 1st review. Please make changes as per the suggestions by the reviewer.

**Comment by Zebedeu** [comment]
> Descobertas:
> 
> O artigo traz um longo GIF mostrando como usar o bloco de parágrafo. Faria mais sentido se fosse um vídeo? Dessa forma, os leitores podem assistir novamente às partes que perderam, pular partes, etc.
> 
> A primeira imagem em "Configurações de bloqueio" está desatualizada
> 
> > Além disso, você pode adicionar links, imagens embutidas e realçar o conteúdo do texto.
> 
> Deveriam ser "destaques" (plural)?
> 
> > O bloco _de parágrafo_ fornece opções de configurações de dimensão
> 
> Isso deveria dizer que _o parágrafo_ é consistente?
> 
> > A guia “Avançado” permite adicionar âncora HTML
> 
> As aspas em torno de Avançado não são consistentes com a forma como outras seções desse menu são referenciadas

"The paragraph block provides various options to adjust its dimensions, such as width and height, allowing you to customize the text layout to ensure visual consistency." Do you agree with this explanation?

**Comment by Zebedeu** [comment]
@sagargurnani99 Updates have been made according to all revisions.
